### ISSUE TITLE
Support for mimic joints

### ISSUE THREAD

**Issue by costashatz** [raisimTech/raisimlib#1]
Thanks for the new release!

This is a copy of https://github.com/leggedrobotics/raisimLib/issues/37. I do not see any support for mimic joints in this version (except if it is hidden and I cannot see it).

**Comment by jhwangbo** [comment]
You are right. I figured out it is very hard to implement mimic joint in RaiSim. So I put it at the end of my todo list.

I will also be using a robot with four-bar linkages. You can find a good kinematic tree that approximates a four-bar linkage. Currently, that is the best way.
