### ISSUE TITLE
unable to get raisimUnity to work with raisimGymTorch in Linux

### ISSUE THREAD

**Issue by ashish-kmr** [raisimTech/raisimlib#10]
Hi, 

I tried launching the raisimUnity executable in the linux folder, but it doesn't seem to do anything (doesnt launch / doesnt crash either). I tried downloading the binaries from the raisimUnity repository. The linux executable from there successfully launches, but when I try to connect it to the raisimGymTorch example, it seems to give a TCP packet error, and the raisimGymTorch runner.py example says "disconnected 0". 

It would also be super useful to have an example code to just load and visualize a pretrained policy, because i ran into some troubles trying to run raisimUnity headless.

**Comment by jhwangbo** [comment]
What is your GPU? Did you install Vulkan as described here? http://raisim.com/sections/Installation.html

To make the graphics more attractive, I had to use Vulkan but it is not compatible with some old gpus.

The executable from leggedrobotics repo doesn't work. It is for the old version and I will close it in Nov.

**Comment by jhwangbo** [comment]
What do you mean by "run raisimUnity headless"? Do you mean without visualization?
The example code already has a section where it shows pretrained policies. All you have to do is copy-paste that section into a different python code

**Comment by ashish-kmr** [comment]
I followed the installation instructions of vulkan for AMD on Ubuntu. I am trying to set up the code on my laptop to develop which does not have an nvidia gpu.  I subsequently plan to use the code on a remote machine which has an nvidia-gpu, but does not have a display. 

When I launch ./raisimUnity.x86_64, it doesn't seem to do anything (no error either), and I also don't see video recordings saved. 

The output I see is when I launch the raisimUnity file is: 
Set current directory to <home path>/raisimUnity/linux
Found path: <home path>/raisimUnity/linux/raisimUnity.x86_64

**Comment by jhwangbo** [comment]
When you run it on a remote machine, set `render: false` in the config file. After it saves policies, you should just copy-paste them to your local machine to display.

I'll also upload opengl version of raisimUnity. We used it internally because some of my students didn't have a good laptop and had the same issue. I still need to clean it up and think about a nice way to manage both versions. Due to ICRA deadline, I can probably finish it by the weekend.

**Comment by jhwangbo** [comment]
btw, you can also use raisimOgre in Linux. https://github.com/raisimTech/raisimOgre

**Comment by ashish-kmr** [comment]
Are there instruction on how to use raisimOgre with the provided raisimGymTorch example for visualization?

**Comment by jhwangbo** [comment]
our old repo of raisimGym has an example https://github.com/leggedrobotics/raisimGym/tree/master/raisim_gym/env
This only works for the old version (which will be deleted in Nov) but the visualization part is the same.

**Comment by ashish-kmr** [comment]
I was able to add the visualization code and files to the raisimGymTorch and then successfully compile it. When I now try to launch the runner.py file, an all black window pops up and then the program crashes with a segmentation fault. Do you know the best way to debug this?

**Comment by jhwangbo** [comment]
You should use the built-in debug app. I added instructions here
https://github.com/raisimTech/raisimlib/blob/master/raisimGymTorch/README.md

A few important things to check
1. Check if your camera is looking at the robot. Examples can be found in raisimOgre
2. Check if your initial position is bad. For this, visualize the world without integration

**Comment by ashish-kmr** [comment]
> When you run it on a remote machine, set `render: false` in the config file. After it saves policies, you should just copy-paste them to your local machine to display.
> 
> I'll also upload opengl version of raisimUnity. We used it internally because some of my students didn't have a good laptop and had the same issue. I still need to clean it up and think about a nice way to manage both versions. Due to ICRA deadline, I can probably finish it by the weekend.

Just checking on raisimUnity on a laptop -- is it likely to happen by this weekend? Even a not clean version which I can setup on my side would be super helpful. I have been able to setup everything else in the code except for visualization, so that is the bottleneck right now.

**Comment by ashish-kmr** [comment]
> You should use the built-in debug app. I added instructions here
> https://github.com/raisimTech/raisimlib/blob/master/raisimGymTorch/README.md
> 
> A few important things to check
> 
> 1. Check if your camera is looking at the robot. Examples can be found in raisimOgre
> 2. Check if your initial position is bad. For this, visualize the world without integration

Would (1) and (2) lead to segmentation fault? Or just a blank screen?

**Comment by jhwangbo** [comment]
I'll finish the opengl version this weekend. It's already there and it's used by a couple of laptop users here. I need to clean it up.
To check the segmentation fault, you should use valgrind. Yes, my list doesn't lead to a segmentation fault.

**Comment by jhwangbo** [comment]
I pushed the opengl version. pull and check if it works on your machine.

**Comment by ashish-kmr** [comment]
Yes, it works!! Thank you so much!
