### ISSUE TITLE
Raisimgym stops at initial random state  

### ISSUE THREAD

**Issue by Pala-Ah** [raisimTech/raisimLib#101]
I have tried to implement a similar setup as in the paper "Control of a Quadcopter with Reinforcement Learning" (https://arxiv.org/pdf/1707.05110.pdf) and in the previous version of Raisimgym (the version before the official v1.0, the example with the hummingbird). 

there are no issues with simulating a few hundred regular environments with the position and velocities being zero. Strangely enough, if I try to set random positions and velocities inside the Environment.hpp, the simulation stops abruptly with the following setup:

position: random number [-1, 1]
orientation: rantom quaternion, normalized
velocity:  random number [-2, 2]
angular velocity:  random number [-5, 5]

I tried simulating fewer environments removing the ground because maybe it might be a contact issue but the issue still occurs with the exception "Update Object Position, Read Data Timeout"

**Comment by jhwangbo** [comment]
Have you tried to run the debug app with Valgrind? This can be due to a memory issue.

Another possibility is due to the fact that the random sampler might not be thread-safe. If so, you have to create the random sampler with a ``thread_local`` tag. But I cannot tell much more without seeing your code.

**Comment by Pala-Ah** [comment]
No, I did not try the debug app yet. I'll run it.

For every environment I am running, I am setting the initial state with the following method:
```cpp
void reset() final {
    setNRandomStates(1, true, 2, 5);
    robot_->setState(gc_init_, gv_init_);
    updateObservation();
}
.
.
.
void setNRandomStates(double pos, bool rot_bool, double vel, double angVel){
    for (int i=0; i<3; i++){
        gc_init_(i) = generateRandomValue(-pos, pos);
        gv_init_(i) = generateRandomValue(-vel, vel);
        gv_init_(i+3) = generateRandomValue(-angVel, angVel);
    }
    if (rot_bool) {
        for (int i = 0; i < 4; i++) {
            gc_init_(i + 3) = generateRandomValue(-1, 1);
        }
        gc_.segment(3, 4) /= gc_.segment(3, 4).norm();
    }
}
.
.
.
double generateRandomValue(double MIN, double MAX){
    std::random_device rd;
    std::default_random_engine eng(rd());
    std::uniform_real_distribution<double> distribution(MIN, MAX);

    return distribution(eng);
}
```
It just works fine, if I don't allow a random orientation (rot_bool = false). Just to have tried it, I used this method for the anymal example without any further modification to make it easier to follow the issue, with the same results. Sure, the anymal can't fly, but still, it has to fall for the few seconds of simulation time.  I also removed the ground (to avoid collision issues). Nonetheless, the whole simulation runs very slow, maybe 10-30 times slower, even without visualization, but only if the orientation is also set randomly.

I also tried out the other integration methods like Runge-Kutta, etc.

**Comment by jhwangbo** [comment]
Please post the output of the valgrind. Without it, I cannot help.
std::random_device should not be created in a multi-threaded environment. I am also not an expert on this. But this is often not thread-safe.

**Comment by Pala-Ah** [comment]
I am using the random device for another simulation setup in the Environment.hpp with n random targets instead of initial states, without any issues. If it is just a coincidence, then there must be another way to generate random values?

My problem is, I cannot run the debug app. I tried to run it according to the description on https://raisim.com/sections/RaisimGymTorch.html but I get a segfault error. I have run it on Clion with the path to rsc and the path to the cfg file in the arguments with no success. Honestly, I am sure I am overseeing something, so is there anything to consider? I am also getting a segfault by running via console.

I also don't want to take up yout time too much, but the issue is easily and provisional reconstructed with the anymal example, the code I posted above and the removed ground. I can't imagine it to be a setup issue. Maybe it is indeed the random device issue. I'll try to find another way to generate random values. But as I said, the issue only occurs with random orientation.

**Comment by jhwangbo** [comment]
> My problem is, I cannot run the debug app. I tried to run it according to the description on https://raisim.com/sections/RaisimGymTorch.html but I get a segfault error. I have run it on Clion with the path to rsc and the path to the cfg file in the arguments with no success. Honestly, I am sure I am overseeing something, so is there anything to consider? I am also getting a segfault by running via console.

That is the point. You get segfault because there is an error in the code. The whole point of the debug_app is to see where it segfaults so that you can fix it. You should run it with GDB and Valgrind to spot the error.

**Comment by Pala-Ah** [comment]
I found the issue. it was indeed the random device, so I changed the method to generate random states. However, I am still using a random device, but I had to put it into the Environment argument and initialize it, as you did in the quadcopter example of the former RaisimGym version.
Thank you for your help, I really appreciate it.
