### ISSUE TITLE
[bug report] RaisimSbGymVecEnv problem 

### ISSUE THREAD

**Issue by app1ep1e** [raisimTech/raisimLib#102]
when i ran the anymal example in raisimGymTorch/stable_baselines, i get the following error
```
Can't instantiate abstract class RaisimSbGymVecEnv with abstract methods env_is_wrapped
```

**Comment by jhwangbo** [comment]
thank you for reporting. I fixed the issue. It will be pushed with mjcf wrapper soon

**Comment by jhwangbo** [comment]
a fixed has been pushed
