### ISSUE TITLE
CMake Error at CMakeLists.txt:51 (install):   install DIRECTORY given no DESTINATION!

### ISSUE THREAD

**Issue by abdul-mannan-khan** [raisimTech/raisimLib#104]
Hello, I am trying to install RaiSim on Ubuntu 20.04. I am following all the step mentioned in [here](https://raisim.com/sections/Installation.html). However, upon compiling, I am getting following error. 

```
CMake Error at CMakeLists.txt:44 (install):
  install DIRECTORY given no DESTINATION!


CMake Error at CMakeLists.txt:51 (install):
  install DIRECTORY given no DESTINATION!

```

Due to this error, I guess, when I run `make install -j4`, I get following error
`make: *** No rule to make target 'install'.  Stop.`

Any suggestion will be appreciated. Thank you.

**Comment by jhwangbo** [comment]
You have to replace "$LOCAL_INSTALL" with the actual path where you want to install RaiSim. When there is "$" sign, it means it is a variable

**Comment by abdul-mannan-khan** [comment]
Thank you. I replaced it with the path where i wanted to install and it worked. However, I am confused about activation key. Is RaisSim open source or is it paid? If it is Open source, may I get the activation key please? Thank you.
