### ISSUE TITLE
System.Exception: Rs.UnityRemote: UpdateObjectionPosition - Server is terminating

### ISSUE THREAD

**Issue by abdul-mannan-khan** [raisimTech/raisimLib#105]
Hi, 

I am trying to follow [this](https://www.youtube.com/watch?v=RoTYz_cqK7w&t=182s) online lecture about RaiSim. I tried to run example `raisimLib\raisimPy\examples\robots.py`. However, I got following error from unity 

```
System.Exception: Rs.UnityRemote: UpdateObjectionPosition
Server is terminating 
 at raisimUnity.RsUnityRemote.ReadAndCheckServer (raisimUnity.ClientMessageType type) [0x0010f] in <c18c1d...>:0
 at raisimUnityRsUnityRemote.Update () [0x002c5] in <c18c1d...>:0
 at raisimUnityRsuException..ctor (System.Exception ex, System.String message) [0x00037] in <c18c1d...>:0
```

I am using Linux 20.04. 
Thank you for your help.

**Comment by jhwangbo** [comment]
Are you using windows? Then you have to compile raisimPy first

**Comment by abdul-mannan-khan** [comment]
Sorry, I am using Linux 20.04. How can I solve this problem for Linux? Thank you for your response.

**Comment by jhwangbo** [comment]
I forgot to push compiled files. Ill do it next week. In the meantime, you can compile it yourself following the installation instruction

**Comment by abdul-mannan-khan** [comment]
Thank you so much Professor for your kind response. I shall study how to compile it.

**Comment by jhwangbo** [comment]
I pushed the compiled ones
