### ISSUE TITLE
Plans to support CUDA or OpenMP

### ISSUE THREAD

**Issue by tomlankhorst** [raisimTech/raisimLib#106]
Are there any plans to move some of the computational load from the CPU to the GPU with CUDA or OpenCL? 
Or, any plans to support OpenMP for running raisim in computer clusters?

**Comment by jhwangbo** [comment]
Where do you need openmp? Do you want to simulate a large number of objects in one environnent?

I am not working on cuda or opencl computation pipeline. But i am working on implementing a new algorithm to speed up simuation by a factor of 3 or more.

**Comment by tomlankhorst** [comment]
Thanks for your quick reply Jemin. 

We're running Raisim on some compute cluster setup. 
A GPU node has 8 RTX 2080Ti's and a 128 core processor. 

However, people using Raisim typically request just 1 GPU but 64 or 128 cores because that speeds up their work. 
The resource usage is very skewed this way (All cores are occupied but 7 GPUs are doing nothing). 
In other words, the core/GPU ratio is 128/1. 

First, having Raisim run on a GPU too would help a lot in more efficiently using the available resources by reducing the core/GPU ratio. 
I think a core/GPU ratio of 16/1 would be ideal since that reflects the setup of our (and other) clusters, but also that of typical user desktops (especially with Intel CPUs). 

Alternatively, having Raisim support OpenMP would allow us to scale to more than 128 cores (e.g. 512 cores), distributed on the cluster, without monopolizing a single GPU server (of which 7 GPUs would be doing nothing). Core/GPU ratios of >128 are not a big problem as long as we are able to combine non-GPU and GPU servers.

**Comment by jhwangbo** [comment]
GPU support is not planned. I dont see it very promising. What seems more promising is new arm based cpus. Currently my M1 mac air is faster than my 3950x cpu on a single thread. I think arm based cpus will boost performance per price by a factor of 3 or more. GPU falls behind in this category.

I guess you want to parallelize learning not RaiSim. I dont have time to working on it now. I dont have access to such machine either.

**Comment by tomlankhorst** [comment]
I agree that ARM architecture looks very promising. However, x86 will stay mainstream for a few years at least. 

Thanks for your reply.
