### ISSUE TITLE
Change fixed joint angles through api?

### ISSUE THREAD

**Issue by PascalEgli** [raisimTech/raisimLib#107]
Is it possible to add a feature that allows for changing joint angles of _fixed_ joints through the api (and not only in the urdf)? 
thanks.

**Comment by PascalEgli** [comment]
i have a serial manipulator with an asymmetric, floating base, with the first joint around the vertical axis. this first joint i want to keep fixed, but i would like to be able to change the fixed joint position. one way of doing it is by changing the rpy in the urdf. however, it would be nice to do it through the api. a workaround would be to make that joint movable in the urdf and use the raisim pd controller to hold it at a fixed joint position which is not as nice as change the fixed position through the api.

**Comment by jhwangbo** [comment]
you can use the urdf template feature exactly for this purpose. Similar to Xacro, you can specify a variable as ``@@Height``. Then you can pass the parameters when you initialize the articulated system (using the method with ``std::unordered_map``). You can simply create it again if you want a different robot. 

Somehow the example was not pushed. I am trying to do a proper version control now. So the example will be included in v1.005, which will be pushed soon

**Comment by jhwangbo** [comment]
I pushed the example
