### ISSUE TITLE
Contact forces on specific link

### ISSUE THREAD

**Issue by studigem** [raisimTech/raisimLib#116]
Hi Jemin

I use a very simple hook as an end effector, this hook is created using and urdf and fixed joints. There is a horizontal rod and perpendicular to it a shorter rod forming this hook. I am now only interested in the contact forces on the shorter rod, is there a way to only evaluate the forces acting on the shorter rod? Eg. a way to see on which link a contact acts?
The way it is done in the online documentation (wantedIdx = system->getBodyIdx("wantedLink") and wantedIdx == contact.getlocalBodyIndex()), doesen't work apparently due to the joints being fixed.
On another note, I think in the online documentation for the Articulated Systems (https://raisim.com/sections/ArticulatedSystem.html) in the Kinematics/Frames code example there is an error, it says:
auto footFrameIndex = world.getFrameIdxByName("foot_joint");
This creates an error and I think world has to be replaced by anymal. With this change it works in my case.
Thanks in advance and best regards,
Matthias

**Comment by jhwangbo** [comment]
I push that feature in the next push. I'll let you know when it is ready. Thank you for pointing out the mistake in the documentation. It will be fixed in the next push as well

**Comment by studigem** [comment]
Amazing thanks for the fast response.

**Comment by jhwangbo** [comment]
This feature is added by the recent push (v1.1). You can get a pair of collision bodies for each contact and they contain ``name``. The name convention is described here https://raisim.com/sections/MaterialSystem.html#id1

Note that there are many other changes including a few backward-incompatible ones. Test and let me know if you find any issues
