### ISSUE TITLE
x axis body velocity fluctuation

### ISSUE THREAD

**Issue by awesomericky** [raisimTech/raisimLib#117]
Hello. Thank you for great simulator.

I am trying to learn a velocity command tracking controller.
Below is the figure of evaluated result. Orange line and green line each indicates velocity command input and measured x axis body velocity. (Just ignore blue line)

I am wondering why there is some large fluctuation in measured x axis body velocity. Is it due to the fluctuation of body frame orientation respect to the world frame? Or could there be some causes while computing the instantaneous velocity in the simulator?

<img src="https://user-images.githubusercontent.com/58288696/120755188-97cc5500-c548-11eb-988d-8dc17b1ffa4d.png" width="400">

**Comment by jhwangbo** [comment]
Is this ANYmal model RL example? I am not sure what I see here.

If this is ANYmal model, this graph looks perfectly fine. The fluctuations are inevitable. You will see the same pattern in human walking speed as well. This can be explained by an inverted pendulum model.

I cited a paper in my 2019 Sci Ro paper which explains this fluctuation. Maybe that reference can help
