### ISSUE TITLE
Scaling the length of the force/torque visualizations

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#118]
Hi Jemin,
It seems to me that the length of the force/torque visualizations has a fixed length. If that's the case, I think it would be helpful to scale their length linearly with the magnitude of the vector. This should give a better sense of the external wrench during debugging. Thanks!

**Comment by jhwangbo** [comment]
The length should be proportional to the magnitude. You can scale them using the ``Contact Forces" slider.

**Comment by weixuanzhang** [comment]
I see. Thanks!
