### ISSUE TITLE
Coherence of Dynamics if Moving COM during Simulation

### ISSUE THREAD

**Issue by pjlorentz** [raisimTech/raisimLib#119]
Hello, 
We have a robot with a body and an arm. We want to move the arm but we do not know its exact kinematic model. However we have a lookup table that links the robot COM with the position of the arm. Is Raisim able to simulate the physics correctly if we modify the position of COM at each iteration with updateMassInfo()?

**Comment by jhwangbo** [comment]
https://raisim.com/sections/ArticulatedSystem.html#get-and-modify-robot-description-in-code

Yes, it should work.
