### ISSUE TITLE
raisimUnityOpenGL failed to record video

### ISSUE THREAD

**Issue by cyoahs** [raisimTech/raisimlib#12]
Hello.

I am trying to migrate my old code to this new version of raisimlib. The origin version of raisimUnity works well on my local machine with GTX 1080, but when I move to the opengl version of raisimUnity, the video recording function failed. It only generate a 262k small [file](https://drive.google.com/file/d/1BU4Hetzp6Xs0il3VmvyHLQ9UIHjynwMF/view?usp=sharing).

My OS is ubuntu 1804 and everything works fine when using the old raisimUnity and even older raisimOgre.

**Comment by jhwangbo** [comment]
Unity3D does not provide proper video recording functionality with OpenGL. There is the ReadPixels function, but this is a blocking call and it reduces the frame rate to ~10Hz. Unity3D with Vulkan on the other hand provides an asynchronous method for this.

So I am leaning towards not supporting video recording for the Opengl version.
