### ISSUE TITLE
Get contact coefficients between two materials in the runtime

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#120]
Hi Jemin,
Is there a function to get the friction coefficient of a given material pair during run time? I could not find it anywhere in the documentation. Thanks!

**Comment by jhwangbo** [comment]
It's not possible yet. but I just made the functionality to do so. It will be added in the next version.

**Comment by weixuanzhang** [comment]
Great. Thanks!

**Comment by jhwangbo** [comment]
This should be added by the recent push (v1.1). Note that there are many other changes including a few backward-incompatible ones. Test and let me know if you find any issues
