### ISSUE TITLE
ArticulatedSystem.cpp:380] /rsc/anymal/urdf/anymal.urdf does not exist

### ISSUE THREAD

**Issue by abdul-mannan-khan** [raisimTech/raisimLib#121]
I tried to run `python3 raisimGymTorch/env/envs/rsg_anymal/runner.py` but I got following error 

`[2021:06:09:10:27:50 ArticulatedSystem.cpp:380] /rsc/anymal/urdf/anymal.urdf does not exist`

I tried to search for the ArticulatedSystem.cpp file so that I could change the address but I could not find it. I tried copying my `/rsc/anymal/urdf/anymal.urdf` and placed it inside the folder where I was running `runner.py` but it did not help.  I understand that I am doing some very stupid mistake which I do not know. I appreciate if someone could give me some clue about the problem so that I could solve it. Thank you.

**Comment by jhwangbo** [comment]
have you checked the code? have you copied the file somewhere?

`anymal_urdf_file = os.path.dirname(os.path.abspath(__file__)) + "/../../rsc/anymal/urdf/anymal.urdf"
`
This is the line that loads `anymal.urdf`. If should search the resource directly relative to the python file.

**Comment by abdul-mannan-khan** [comment]
The problem is solved.
