### ISSUE TITLE
how to visualize simulation?

### ISSUE THREAD

**Issue by ZhaomingXie** [raisimTech/raisimLib#122]
Hi 
I successfully build raisimLib and raisimOgre. I can run examples in raisimLib and raisimOrge.
However, I don't know how to turn on visualization for the raisimPy/raisimTorchGym examples, when I run them I can see the simulation is running but I have no idea how to visualize them.
It is probably just some simple steps that I missed, but will appreciate any help on this. BTW, I am able to see the visualization when running examples in raisimOgre.
Thanks!

**Comment by jhwangbo** [comment]
You can use raisimUnity to visualize a RaiSim World. Please check this link
https://raisim.com/sections/RaisimUnity.html
