### ISSUE TITLE
AddArticulatedSystem ignores joint order

### ISSUE THREAD

**Issue by EricVoll** [raisimTech/raisimLib#124]
Hello,

I am adding an Articulated system from a urdf-file  [link](https://github.com/EricVoll/amp_motion_conversion/blob/master/urdf/humanoid.urdf) using `raisim::World::addArticulatedSystem`. After that I am printing out the joint names like this:
```c++
    auto movable_joint_names = robot_ -> getMovableJointNames();
    for (int i = 0; i < movable_joint_names.size(); i++){
      std::cout << movable_joint_names[i] << std::endl;
    }
```
The joint order should (according to the documentation) be the same as [here](https://github.com/EricVoll/amp_motion_conversion/blob/28d807207bdd2c5e588123527d2f459c7954d46c/src/run.py#L139) - in the order the joints appear in the urdf. But in my case the code above prints this:

<details>
  <summary>Click to see console output!</summary>
  
ROOT
root_chest_joint1
root_chest_joint2
root_chest_joint3
chest_neck_joint1
chest_neck_joint2
chest_neck_joint3
chest_right_shoulder_joint1
chest_right_shoulder_joint2
chest_right_shoulder_joint3
right_elbow
chest_left_shoulder_joint1
chest_left_shoulder_joint2
chest_left_shoulder_joint3
left_elbow
root_right_hip_joint1
root_right_hip_joint2
root_right_hip_joint3
right_knee
right_knee_right_ankle_joint1
right_knee_right_ankle_joint2
right_knee_right_ankle_joint3
root_left_hip_joint1
root_left_hip_joint2
root_left_hip_joint3
left_knee
left_knee_left_ankle_joint1
left_knee_left_ankle_joint2
left_knee_left_ankle_joint3
</details>

As you can see, the order is incorrect. The right hip appears in the urdf before the right shoulder. Even when passing in the joint order explicitely during instance creation, the output doesn't change.

<details>

```c++
auto joint_names = std::vector<std::string>({
      "root_chest_joint1",
      "root_chest_joint2",
      "root_chest_joint3",
      "chest_neck_joint1",
      "chest_neck_joint2",
      "chest_neck_joint3",
      "root_right_hip_joint1",
      "root_right_hip_joint2",
      "root_right_hip_joint3",
      "right_knee",
      "right_knee_right_ankle_joint1",
      "right_knee_right_ankle_joint2",
      "right_knee_right_ankle_joint3",
      "chest_right_shoulder_joint1",
      "chest_right_shoulder_joint2",
      "chest_right_shoulder_joint3",
      "right_elbow",
      "root_left_hip_joint1",
      "root_left_hip_joint2",
      "root_left_hip_joint3",
      "left_knee",
      "left_knee_left_ankle_joint1",
      "left_knee_left_ankle_joint2",
      "left_knee_left_ankle_joint3",
      "chest_left_shoulder_joint1",
      "chest_left_shoulder_joint2",
      "chest_left_shoulder_joint3",
      "left_elbow"
      });

    robot_ = env_->addArticulatedSystem(urdf_path, "", joint_names);

```
</details>

Is there something wrong with my urdf or what else could be the issue? I can of course just re-map the inputs to fit raisim's joint order, but that doesn't seem like a nice solution.

Thanks,
Eric

**Comment by jhwangbo** [comment]
Raisim tries to follow the joint order from the urdf. But there is one consrraint: a child cannot preceed a parent. If this is violated in the urdf file, raisim moves the parent before the child.
