### ISSUE TITLE
how to set contact friction in urdf

### ISSUE THREAD

**Issue by hxydebug** [raisimTech/raisimLib#125]
I want to try the wheel robot control, but when I set the material of gound to "steel", and then add the label to the wheel link in urdf, like this :
`<material name="rubber">
        <contact name="steel"/>
 </material>`
then add the code bellow：
`world.setMaterialPairProp("steel", "rubber", 1.5, 0.15, 0.001);`
I found no difference from that with default coefficient. 
so I don't know why it doesn't work and hope this question can be solved.

**Comment by jhwangbo** [comment]
`name="rubber` does not do anything. You have to change it to `<contact name="rubber">`
