### ISSUE TITLE
Simulation problems

### ISSUE THREAD

**Issue by MusubaPy** [raisimTech/raisimLib#127]
Hi Jemin

I am having problems with raisimGymTorch.

Sometimes during training I get this result:

https://user-images.githubusercontent.com/11860297/121918681-f8287700-cd3e-11eb-87e4-f2f3c04ae743.mp4

The only solution is to start continuing learning with the last successful simulation. Any ideas where to look for the error and how?

Thank you for your patience!

======================================================================================
P.S. This same code can give normal results:

https://user-images.githubusercontent.com/11860297/121919312-94527e00-cd3f-11eb-91dc-ba4411af3819.mp4

**Comment by jhwangbo** [comment]
The policy is trapped in a place where termination is its local minimum. This is a very common issue. You have to design a better reward function to eliminate this issue.

**Comment by MusubaPy** [comment]
Thanks for the quick response,
Could you advise on how to make the reward function better? I mean, what are the rules for setting up policies?

I would be grateful if you advise sources.

**Comment by jhwangbo** [comment]
Try to have positive rewards instead of negative ones.

**Comment by abdul-mannan-khan** [comment]
Hello @MusubaPy 

May I ask you a quick question? How did you get that left hand panel with all the signals as shown in your video "2021-06-10-17-34-53policy_2500.mp4"? I appreciate your kind response. Thank you so much.

**Comment by jhwangbo** [comment]
That is available only in raisimOgre at the moment. I am working on implementing the same functionalities in raisimUnity
