### ISSUE TITLE
how to resolve the issue of a robot body which is under the surface. 

### ISSUE THREAD

**Issue by abdul-mannan-khan** [raisimTech/raisimLib#128]
Hello Jemin

I am facing the problem regarding robot body. My robot body is under the surface. 

https://user-images.githubusercontent.com/22067958/122745819-58ca2d80-d2c4-11eb-8cd5-b15f64aead2a.mp4

I know it sounds little too basic but any clue will be helpful. 
Here is my detail. The robot is modeled in SolidWorks and URDF is generated from it using the [add-in](http://wiki.ros.org/sw_urdf_exporter). I have tested the robot in ROS (RViz and Gazebo). It works fine in Gazebo and it does not submerge in the surface. It remain on the ground. However, when I open it in RaiSim, it is under the surface. Could you please give me any clue to how to resolve this issue? Thank you.

**Comment by jhwangbo** [comment]
can you share the urdf?

on the left panel, you can turn off the visualization of visual bodies and turn on visualization of collision bodies. Can you do that and see what is going on?

**Comment by abdul-mannan-khan** [comment]
Dear Jemin,

Thank you so much for your kind response. 
I have sent my urdf package at your email address (info.raisim@gmail.com). I have tried highlighting collision bodies here. 


https://user-images.githubusercontent.com/22067958/122843569-b9944d00-d33a-11eb-898c-20832b5d4914.mp4

 Thank you so much for your help.

**Comment by jhwangbo** [comment]
did you start the simulation while the robot is submerged? did you set the height such that no parts are initially submerged?

**Comment by abdul-mannan-khan** [comment]
Yes. This was a very stupid mistake; I am sorry for that. I did not fully grab the idea of adjusting the coordinates before starting the simulation. Your comment helped me resolve the issue. Thank you for your help. Here is the updated code for future reference. 

```
import os
import numpy as np
import raisimpy as raisim
import time

raisim.World.setLicenseFile(os.path.dirname(os.path.abspath(__file__)) + "/../../rsc/activation.raisim")
anymal_urdf_file = "/home/khan/raisim_ws/raisimLib/rsc/anymal/urdf/anymal.urdf"

atlas_urdf_file = "/home/khan/raisim_ws/raisimLib/rsc/atlas/robot.urdf"


quad_robot_urdf_file = "/home/khan/raisim_ws/test/quad_robot_20210621_e/urdf/quad_robot_20210621_e.urdf"


dummy_inertia = np.zeros([3, 3])
np.fill_diagonal(dummy_inertia, 0.1)

world = raisim.World()
world.setTimeStep(0.001)
server = raisim.RaisimServer(world)
ground = world.addGround()

anymal = world.addArticulatedSystem(anymal_urdf_file)
anymal.setName("anymal")
anymal_nominal_joint_config = np.array([0, -1.5, 0.54, 1.0, 0.0, 0.0, 0.0, 0.03, 0.4, -0.8,
                                        -0.03, 0.4, -0.8, 0.03, -0.4, 0.8, -0.03, -0.4, 0.8])
anymal.setGeneralizedCoordinate(anymal_nominal_joint_config)
anymal.setPdGains(200*np.ones([18]), np.ones([18]))
anymal.setPdTarget(anymal_nominal_joint_config, np.zeros([18]))

# my robot URDF file
quad_robot = world.addArticulatedSystem(quad_robot_urdf_file)
quad_robot.setName("quad_robot")
quad_robot_nominal_joint_config = np.zeros(quad_robot.getGeneralizedCoordinateDim())
quad_robot_nominal_joint_config[2] = 1.5
quad_robot_nominal_joint_config[3] = 1.5 # z - axis -initial hegight of the robot  
quad_robot.setGeneralizedCoordinate(quad_robot_nominal_joint_config)

server = raisim.RaisimServer(world)
server.launchServer(8080)

world.integrate1()
time.sleep(3)
### get dynamic properties
# mass matrix
mass_matrix = anymal.getMassMatrix()
# non-linear term (gravity+coriolis)
non_linearities = anymal.getNonlinearities()
# Jacobians
jaco_foot_lh_linear = anymal.getDenseFrameJacobian("LF_ADAPTER_TO_FOOT")
jaco_foot_lh_angular = anymal.getDenseFrameRotationalJacobian("LF_ADAPTER_TO_FOOT")

for i in range(50000):
    world.integrate()
    time.sleep(0.01)

server.killServer()
```
