### ISSUE TITLE
Is the license bound to the hostname of the machine?

### ISSUE THREAD

**Issue by cyoahs** [raisimTech/raisimLib#132]
I tried to change the hostname of the machine through `hostnamectl set-hostname xxxx` and then it raised the following error:

```
[2021:07:01:17:28:31 license.hpp:74] The license was issued to another machine 52C4DA28D8140A508372EF28XXXXXXXXX
```

After changing the hostname to the origin one, it works correctly. Emmmmm......

Perhaps changing the hostname is kind of common or normal operation. Will this binding be removed in the feature?

**Comment by jhwangbo** [comment]
the license is bound to a specific user of the machine

**Comment by cyoahs** [comment]
> the license is bound to a specific user of the machine

Really? On our server (ubuntu), all users on that machine can use the same license to activate raisim.

**Comment by jhwangbo** [comment]
There is a legal bound. By accepting the software license agreement (which you did when you asked for the license key), you agreed not to share the key. 

RaiSim only checks the hostname as you noticed. So in theory you can share it if you have one big server machine.

**Comment by cyoahs** [comment]
Got it! Thanks for your reminder.
