### ISSUE TITLE
Incorrect appearance raisim unity

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#134]
I noticed that since the merge pull request #114 (d4343d458a9ddbb2745840c84287335ad4ba8a95), the color of the surface cannot be correctly displayed in raisim unity. In this example:
[AerialInteraction.zip](https://github.com/raisimTech/raisimLib/files/6763960/AerialInteraction.zip)
The surface is supposed to show blue (and it worked on previous commits), but instead shows magenta.
I am using Ubuntu 18.04

**Comment by jhwangbo** [comment]
I'll push the fix with the new version. There is going to be a major version change soon. The fix will be included there

**Comment by weixuanzhang** [comment]
Great thanks!

**Comment by jhwangbo** [comment]
This should be fixed by the recent push (v1.1). Note that there are many other changes including a few backward-incompatible ones. Test and let me know if you find any issues
