### ISSUE TITLE
Collision group setting doesn't work on xml configuration file

### ISSUE THREAD

**Issue by SeungHunJeon** [raisimTech/raisimLib#135]
I wanted to make ray on collision group (1), in cpp raisim function works properly such as 
**auto compound = world->addCompound(children, (mass) 10000, (com) {0, 0, 0}, (inertia) inertia, (collision group) raisim::COLLISION(1), (collisionMask) -1);**
But when i tried to make environment using xml file configuration such as 
**compound name="compound" mass="1000" com="0 0 0" body_type="kinematic" collisionGroup="1" collisionMask="-1"**
The ray test didn't work.. the ray only concentrated on collision group 1 (couldn't find specific collision group 1). I tried to find out that 'collision' parameter works or not, but collisionMask parameter worked well. So I guess only collision group parameter setting on xml file configuration might be a problem.

**Comment by jhwangbo** [comment]
Please read https://raisim.com/sections/Contact.html
You should also study bit operations https://www.geeksforgeeks.org/bitwise-operators-in-c-cpp/

raisim::COLLISION(1) is collision group 2. In binary, it is 000000.....000010.
