### ISSUE TITLE
Install error "Incorrect padding"

### ISSUE THREAD

**Issue by ZQX323** [raisimTech/raisimLib#139]
Hello,

Today, I try to install raisim in my another PC. However, it occurs error when I test the examples. 

```
(base) zqx@LC0:~/raisim_workspace/raisimLib/build/examples$ ./anymals 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Incorrect padding
Aborted (core dumped)
```

It occurs errors even I try a very simple code:
```

#include "raisim/RaisimServer.hpp"
#include "raisim/World.hpp"

int main(int argc, char* argv[]) {
 auto binaryPath = raisim::Path::setFromArgv(argv[0]);
  raisim::World::setActivationKey(binaryPath.getDirectory() + "\\rsc\\activation.raisim");

  /// create raisim world
  raisim::World world;
}
```

The problem of this code is  `raisim::World world`, do you have any idea of this problem?

Best

**Comment by jhwangbo** [comment]
when did you pull? I am currently working on multiple fixes on the new version. Could you make sure that you have the latest one?

**Comment by jhwangbo** [comment]
You haven't requested a new key. Did you use the one for other PC's? Then a new key will do the trick.

**Comment by ZQX323** [comment]
Thank you very much for your reply. I am sure that I am using the latest version, and I applied for the license on June 23. I have not been able to use it these days, and there will be no errors in the activate license function. Could there be a problem with the license file?

**Comment by jhwangbo** [comment]
The license file is checked in the constructor of the World class. If there is an error in the constructor of the World class, it is most likely to be related to the license file.

Can you check if the machine id on the activation file matches the machine id that you see when you run "checkMyMachine" executable (the one that you downloaded from the google form)

**Comment by jhwangbo** [comment]
and can you also check if it works on old commits? for example this one: 335adf398699da766129e1c67e40f4f7fd5734d0

**Comment by jhwangbo** [comment]
I could reproduce your error with your key. I'll get back to you after solving this issue.

**Comment by ZQX323** [comment]
I have check the machine ID, it is same as the activation key. And I have tried old commit, it did not work.

**Comment by jhwangbo** [comment]
I fixed the issue but I need to thoroughly check if I didn't screw up others' activation keys. I'll push the fix in a couple of days.

**Comment by ZQX323** [comment]
Any way I can use it during these days?

**Comment by jhwangbo** [comment]
can you pull and try again?

**Comment by jhwangbo** [comment]
I tested the fix on 20 keys so it should be sufficnetly safe

**Comment by ZQX323** [comment]
Thank you very much, it works right now!

But it seems that there is a bug in raisimOgre.

https://github.com/raisimTech/raisimOgre/blob/ea88c614214b227a776b4a48744b90d96cdd593e/src/OgreVis.cpp#L1271

When I build, it will say ```
error: no match for ‘operator*’ (operand type is ‘raisim::Vec<3>’ {aka ‘const raisim::Mat<3, 1>’})
           matvecmul(contact.getContactFrame(), *contact.getImpulse(), zaxis);
```
Do you think it is caused by new version of RaiSimLib?

Fixed the error by remove * before contact.getImpulse()

**Comment by jhwangbo** [comment]
I also pushed a fix for raisimOgre. You can pull it and try again
