### ISSUE TITLE
ROS node example

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#144]
I would like to use the raisim simulator in the ros framework. I.e., the controller is publishing ros messages and there is a "raisim_node" that listens to these ros messages and update the dynamics. Is there already an instruction or an example I could use to start with? This would save me (I guess also other people some time to find the correct setup). Thanks!

**Comment by Alex-Beh** [comment]
@weixuanzhang Hello, may I know are you trying to display the joint angles that being simulated by the raisim and display it in RVIZ? Which simulator are you plannint to us? Raisim or Gazebo?

**Comment by weixuanzhang** [comment]
> @weixuanzhang Hello, may I know are you trying to display the joint angles that being simulated by the raisim and display it in RVIZ? Which simulator are you plannint to us? Raisim or Gazebo?

@Alex-Beh Hi, I am using the ROS framework with Gazebo simulation (including the rotors_gazebo_plugin) for aerial robots. I wished to replace the physics engine with raisim. This seems to be not possible. Now my goal is to replace the gazebo with raisim (including the visualization)
