### ISSUE TITLE
The custom matrix types are not mentioned in the new document

### ISSUE THREAD

**Issue by cyoahs** [raisimTech/raisimLib#148]
Hello.

I found the document for the custom types for matrix like `raisim::Vec` in this [page](https://slides.com/jeminhwangbo/raisim-manual#/3/2) is missing in the new [documentation](https://raisim.com/index.html).

Although old users are already familiar with them, I think it is important for new users. I hope it can be added to the current documentation if you have time.

Thanks!

**Comment by jhwangbo** [comment]
Here you are,
https://raisim.com/sections/Math.html
