### ISSUE TITLE
Unity crashes on startup 

### ISSUE THREAD

**Issue by elijahstangerjones** [raisimTech/raisimLib#151]
Running on Ubuntu 18.04
Both the standard and OpenGl version of the unity executable freeze on startup. None of the buttons respond and after about 20 seconds it says it has stopped responding, if I don't kill the executable it will freeze up my whole system. Tried running from terminal and from the gui to no avail.
Vulkan is installed and am running the latest Nvidia drivers. 
Any thoughts/ tips on debugging this?

**Comment by jhwangbo** [comment]
What did you run? the examples?
Can you also share ``Logs/raisim_error_log.txt" after it crashes?

**Comment by elijahstangerjones** [comment]
Yeah none of the examples work but the crash happens before I even run the raisim itself, just opening the unity causes the crash. 
The log is empty?

**Comment by jhwangbo** [comment]
Can you tell me about your pc spec more? What are your CPU and GPU? Do you have enough ram for both of them?

**Comment by elijahstangerjones** [comment]
AMD 3700x 
Nvidia 3070 
32GB of Ram

**Comment by jhwangbo** [comment]
can you run ``htop`` and ``watch nvidia-smi`` and see what blows up? My guess is that it is either the cpu memory or gpu memory.

**Comment by elijahstangerjones** [comment]
Looking at it all, during the failure the Unity exectuable uses:
1Gb of Vram 
0.5Gb of RAM 
And is using 100% of one core of my CPU

**Comment by jhwangbo** [comment]
100% when you are not running the simulation? Then this sounds like timed loops are not running properly.
Does this happen on other PCs in your lab?

**Comment by jhwangbo** [comment]
Does the GUI panel on the left respond to your mouse inputs during the initial 20 seconds?

**Comment by elijahstangerjones** [comment]
No, that is the way I know its crashed. I go to unclick auto connect and it never responds.

**Comment by elijahstangerjones** [comment]
This is the only machine this happens on as far as I'm aware. Yes 100% when not running any simulation

**Comment by elijahstangerjones** [comment]
Is the RaisimUnity opensource? Would it be possible to access the source setup to run it from the unity editor to see whats going wrong?

**Comment by elijahstangerjones** [comment]
When I run the Raisim with a default address (8080) it gives a bind error. Could the Unity error be related to this?

**Comment by jhwangbo** [comment]
RaisimUnity is not open-source but I can share the repo with you. I was just cleaning up some files so I can share. Give me a few hours. You will get access to the repo tonight.

Since it is not a memory problem, it is probably a tcp/ip issue. There is nothing much it does when it is not running simulation. But I guess it is better if you can test it because this only happens on your machine

**Comment by jhwangbo** [comment]
I invited you for the repo. Please do not share the code. Let me know if you spot an issue

**Comment by elijahstangerjones** [comment]
Thank you. 
When I run from unity as standard it still crashes.
When I change the auto connect button to be default off it runs totally fine. Might be worth setting that as the default so it doesn't get itself into the crash loop if the default port is broken for some reason. 
Thanks for all your help, this should be resolved.

**Comment by jhwangbo** [comment]
Maybe 8080 port is already occupied by another program on your machine. 

I prefer to keep the auto-connect option for beginners. I think I can add an exception around the auto-connect loop so that it doesn't hang. I'll check if it is possible

**Comment by elijahstangerjones** [comment]
Yeah netstat doesn't show anything on 8080 but its definitely an issue with that. Not sure why I can't see anything wrong with the port though. 

An exception sounds good.

**Comment by jhwangbo** [comment]
I think the issue is in the UIController.cs, line 526.``_remote.EstablishConnection(20);``
can you change that line to 
`                            isAutoConnecting = true;
                            _remote.EstablishConnection(20);
                            isAutoConnecting = false;`
and see if it freezes?

**Comment by jhwangbo** [comment]
auto connect is now off by default
