### ISSUE TITLE
pybindings and parameters for curricula

### ISSUE THREAD

**Issue by sheim** [raisimTech/raisimLib#155]
There are several parameters that are currently hard-coded in the `Environment.hpp`, such as PD gains, initial state (`gc_init_`) etc., which we would like to expose through pybind, mainly to do curriculums from the python side. Because `Environment.hpp` is inheriting things, it seems like things would need to be modified in RaisimLib though, not just in our `Environment.hpp`.

I imagine you've already exposed at least some of these for your own curriculums, did you solve this some other way (e.g. putting this into the "action space", but not under the control of the policy)?

**Comment by jhwangbo** [comment]
You have to add the method to change the param in ``Environmnet.hpp``, make a vectorized version in ``VectorizedEnvironment.hpp`` and append the vectorized method in ``raisim_gym.cpp``.

**Comment by sheim** [comment]
Yeah, that's what I found, but this means each project would have a different branch of raisimLib, depending on what needs to be exposed. I thought maybe you have a different approach to avoid this, so that these changes are all on only in the `Environment.hpp`. But this will work, thanks!

**Comment by jhwangbo** [comment]
You should copy paste the raisimGymTorch folder to somewhere else and modify it there. You can edit a few lines in the cmake file and it will work

**Comment by sheim** [comment]
In case others look for this:

1. implement the method in your robot's `Environment.hpp`
  **note** if you're setting a variable, make sure to typecast it properly, usually with `robot_->set(myVar.cast<double>());`.
2. add the virtual method to the superclass `RaisimGymEnv.hpp`
3. add the actual binding in `raisim_gym.cpp`
4. Implement the parallelized interface in `VectorizedEnvironment.hpp`
5. Add it to the gym python interface in `RaisimGymVecEnv.py`

**Comment by jhwangbo** [comment]
thx for posting
