### ISSUE TITLE
documentation mistake

### ISSUE THREAD

**Issue by sheim** [raisimTech/raisimLib#157]
In [dynamics](https://raisim.com/sections/ArticulatedSystem.html#dynamics), it states

> The total potential energy due to the gravity is a sum of for all bodies. This quantity can be obtained by `getEnergy()`. 

This should of course be `getPotentialEnergy()` (and perhaps add a line that `getEnergy()` is a convenient way to the total energy).

**Comment by jhwangbo** [comment]
I fixed the typo. Thx for reporting
