### ISSUE TITLE
Raisimpy-example : 'no module raisimpy' on Windows 

### ISSUE THREAD

**Issue by miercat0424** [raisimTech/raisimLib#158]
Got an e-mail about activation keys , and then 
I followed the documents in Raisim-Install page
set the System variables  "C:\raisim_workspace\raisimlib" like this 
after that i execute RaiSimUnity

I started newtonsCradle.py on rasimPy-Example folder ( used VSCode IDE )
the 'no module raisimpy' error showed up

In Linux ,writing 'export_raisim_py' on terminal solved this problem ,
But I don't know how to solve this on Windows OS
can u help me ?

**Comment by jhwangbo** [comment]
You have to compile raisimpy yourself on Windows. The install instruction is given in the doc
