### ISSUE TITLE
setExternalForce does not work under Integration scheme RUNGE_KUTTA_4

### ISSUE THREAD

**Issue by Pala-Ah** [raisimTech/raisimLib#16]
When using the integration scheme RUNGE_KUTTA_4, external forces don't work. I tried it in my own simulation and with one of the examples "wheeledRobot.cpp". With the other integration schemes it works fine. I also made sure to put the external force into the integration loop.

**Comment by jhwangbo** [comment]
a fix has been pushed. let me know if you still have an issue

**Comment by Pala-Ah** [comment]
I wanted to try it out but with the new push I have some other issues when I try to build with cmake. I have already installed libeigen3-dev: 

-- The CXX compiler identification is GNU 5.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found raisim: /home/pala/raisimLib/raisim/linux/include  
-- raisim:
--   Version: 1.0.0
--   Includes: /home/pala/raisimLib/raisim/linux/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;Eigen3::Eigen;raisim::raisim
/usr/include/eigen3
-- Found PythonInterp: /home/pala/anaconda3/envs/raisim/bin/python3.6 (found version "3.6.12") 
-- Found PythonLibs: /home/pala/anaconda3/envs/raisim/lib/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.4.3
-- The C compiler identification is GNU 5.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- raisim:
--   Version: 1.0.0
--   Includes: /home/pala/raisimLib/raisim/linux/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;Eigen3::Eigen;raisim::raisim
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
CMake Error at thirdParty/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Target "raisimpy" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  raisimPy/CMakeLists.txt:13 (pybind11_add_module)


CMake Error at thirdParty/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Target "raisimpy" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  raisimPy/CMakeLists.txt:13 (pybind11_add_module)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "xmlRader" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:59 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "visualObjects" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:54 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "newtonsCradle" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:53 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "wheeledRobot" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:52 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "laikago" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:45 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "atlas" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:47 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "heightMapUsingPng" links to target "Eigen3::Eigen" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:51 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "meshes" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:44 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "anymals" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:56 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "anymal_speed_test" links to target "Eigen3::Eigen" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:40 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "balls" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:46 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "primitives" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:43 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "heightmap" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:48 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "robots" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:49 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "rayDemo" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:55 (create_executable)


CMake Error at examples/CMakeLists.txt:29 (add_executable):
  Target "materials" links to target "Eigen3::Eigen" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  examples/CMakeLists.txt:50 (create_executable)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

(raisim) pala@pala-ThinkPad-T480s:~/raisimLib/build$ make install

Scanning dependencies of target xmlRader
[  2%] Building CXX object examples/CMakeFiles/xmlRader.dir/src/xml/xmlReader.cpp.o
[  4%] Linking CXX executable xmlRader
/usr/bin/ld: cannot find -lEigen3::Eigen
collect2: error: ld returned 1 exit status
examples/CMakeFiles/xmlRader.dir/build.make:107: recipe for target 'examples/xmlRader' failed
make[2]: *** [examples/xmlRader] Error 1
CMakeFiles/Makefile2:184: recipe for target 'examples/CMakeFiles/xmlRader.dir/all' failed
make[1]: *** [examples/CMakeFiles/xmlRader.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jhwangbo** [comment]
if you are using raisim in Linux, pull and test again. it should be fixed now

**Comment by Pala-Ah** [comment]
thank you. Yes I am using the Linux version. I'm now having another problem  with rayDemo after pulling, when I am building with make install: 

[ 65%] Building CXX object examples/CMakeFiles/rayDemo.dir/src/server/rayDemo.cpp.o
/home/pala/raisimLib/examples/src/server/rayDemo.cpp: In function ‘int main(int, char**)’:
/home/pala/raisimLib/examples/src/server/rayDemo.cpp:44:9: error: ‘struct raisim::PolyLine’ has no member named ‘width’
   line->width = 0.05;
         ^
/home/pala/raisimLib/examples/src/server/rayDemo.cpp:55:17: error: passing ‘const raisim::RayCollisionList’ as ‘this’ argument discards qualifiers [-fpermissive]
     if(col.size() > 0) {
                 ^
In file included from /home/pala/raisim_install/include/raisim/World.hpp:28:0,
                 from /home/pala/raisim_install/include/raisim/RaisimServer.hpp:39,
                 from /home/pala/raisimLib/examples/src/server/rayDemo.cpp:4:
/home/pala/raisim_install/include/raisim/rayCollision.hpp:65:10: note:   in call to ‘std::size_t raisim::RayCollisionList::size()’
   size_t size() {
          ^
examples/CMakeFiles/rayDemo.dir/build.make:81: recipe for target 'examples/CMakeFiles/rayDemo.dir/src/server/rayDemo.cpp.o' failed
make[2]: *** [examples/CMakeFiles/rayDemo.dir/src/server/rayDemo.cpp.o] Error 1
CMakeFiles/Makefile2:562: recipe for target 'examples/CMakeFiles/rayDemo.dir/all' failed
make[1]: *** [examples/CMakeFiles/rayDemo.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jhwangbo** [comment]
It seems like that the examples are linking against the old version. Please delete the old version (or simply LOCAL_INSTALL) and try again

**Comment by Pala-Ah** [comment]
you were right, now everything works fine. Thank you!
