### ISSUE TITLE
raisim and ROS

### ISSUE THREAD

**Issue by mrsp** [raisimTech/raisimLib#160]
Hello 

I've written a raisim ROS wrapper and currently I am simulating the NAO robot. 

Nevertheless, sometimes when I launch my ROS  wrapper node I get the following in Unity 
![raisim1](https://user-images.githubusercontent.com/1980837/129176241-b5ddfe61-c1b6-4abc-88dc-dc9e0c252237.png)

Seems like some raisim staff are not initialized properly (or there is a race condition) could you provide some feedback please? The code is very simple and available at https://github.com/mrsp/raisim_ros/blob/main/src/nao_ros.cpp

Relaunching the same node again a few times and it works.
![raisim2](https://user-images.githubusercontent.com/1980837/129176589-0e770f5b-219b-4ba0-8cc0-ffbdd4b46fdd.png)

Thanks in advance

**Comment by jhwangbo** [comment]
how stable is your ROS loop? Does faster loop rate resolve this issue?

**Comment by jhwangbo** [comment]
Yes. ``RaisimServer`` creates a thread when you call ``launchServer``. This periodically reads the robot state and sends it to RaisimUnity. The RaisimSever is header-only and you can read the implementation

**Comment by mrsp** [comment]
After a bit debugging. I've found that the loop takes some microseconds ~ 100μs which is acceptable.
The first values e.g. getState(q,dq) are the correct state values and not NaN values.

The NaN occurs after the first:

server.integrateWorldThreadSafe();

Any idea why this is happening?

I've also tried different loop rates e.g. 1hz 10hz 100hz 1000hz same problem happening.

**Comment by jhwangbo** [comment]
Timestep of 0.01s for a humanoid robot is really small. I would go much lower, e.g., ~0.002s.

Since it sometimes works, I think the issue is either memory or thread-related. Have you checked the code with Valgrind? Can you also share a minimum code to reproduce the error?

**Comment by mrsp** [comment]
Indeed it is but is the hardware loop for NAO. Nevertheless, as I've mentioned,I've tried already the 0.001s loop same issue.

Here is a repo (https://github.com/mrsp/raisim_ros),  kindly clone, configure urdf/license paths in config/nao_params.yaml then:

catkin_make

roslaunch raisim_ros nao.launch 

If you have an issue with raisim not found change the list(APPEND CMAKE_PREFIX_PATH /home/master/raisim_build) in the CMakeLists.txt

Many thanks in advance

**Comment by jhwangbo** [comment]
I dont use ROS and I cannot invest that much time for you. You can try the things that i memtioned. If you dont want to, i cannot help you anymore

**Comment by mrsp** [comment]
Although the code is very simple/straightforward and that why I've linked it to you, It is impossible to reproduce this error without having ROS installed in your machine, you should have mentioned that to me.

I'll try the valgrind as you suggested. If you're interested to find out why raisim doesn't work as intended with ROS I can share my findings.

**Comment by jhwangbo** [comment]
> Indeed it is but is the hardware loop for NAO. Nevertheless, as I've mentioned,I've tried already the 0.001s loop same issue.
Your simulation dt doesn't have to be the same as the hardware loop. You can integrate multiple times in a single hardware loop

My former colleagues have a raisim ros implementation: https://github.com/leggedrobotics/ocs2/tree/main/ocs2_raisim_ros
This might help

**Comment by mrsp** [comment]
I will check it out thanks for mentioning it.

**Comment by dvogureckiy99** [comment]
How make `catkin build`, that I can run raisim through command `roslaunch raisim unity.launch`?
