### ISSUE TITLE
Discontinuous contact force jumping between zero and non-zero value during sliding

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#161]
Hi Jemin,
In the following example, at the beginning of the simulation when the robot is around 2.1 m in the x direction, the robot contact force outputs numbers jumping between zero and non-zero values although visually it is in contact. This can also be visualized using the arrow. In addition, you can observe that sometimes when the robot is not moving (stoped by the terrain), the contact force is still zero during the simulation. Do you have an idea why this is happening? 
[RaisimAerialInteraction.zip](https://github.com/raisimTech/raisimLib/files/6977050/RaisimAerialInteraction.zip)

**Comment by jhwangbo** [comment]
If the computed contact force is slightly higher than the actual solution, the box will lift and lose contact. As far as I know, this is unavoidable in rigid-body simulation.

**Comment by weixuanzhang** [comment]
I think what I observed is different from what you stated, I noticed that this phenomenon happens when the endeffector touches the edge of two meshes:
![interaction_no_contact_force](https://user-images.githubusercontent.com/8019238/129350258-f1ac2705-e349-403f-ba6c-fd2c5e802105.png)
And the contact force switches between zero and non-zero (larger than 1 N) contact forces:
![contact_force_output](https://user-images.githubusercontent.com/8019238/129350391-e6fec66e-eea2-4f18-a94a-816425a5f9bd.png)
Is this an expected behavior?

**Comment by jhwangbo** [comment]
Try to use zero restitution and ``World::setERP(0,0)``. On my machine, this mitigates the issue. But you should expect many zeros due to the first reason i mentioned above.

**Comment by weixuanzhang** [comment]
Great. Thanks for the explanation!
