### ISSUE TITLE
Set camera position and look at not working

### ISSUE THREAD

**Issue by feracero** [raisimTech/raisimLib#166]
Hi Jemin, I have noticed the raisim server method setCameraPositionAndLookAt() does not work as expected. 
![Screen Shot 2021-08-17 at 17 41 58](https://user-images.githubusercontent.com/46450880/129766353-7bff47fa-1b38-418e-ba17-411457c2abda.png)
Based on the server request class definition, I assumed there was a typo on the first line and changed it to:
`serverRequest_.push_back(ServerRequestType::SET_CAMERA_TO);`
however after recompiling it still does not work as expected.

Have not managed to figure out if this is a problem on the Unity application side...

**Comment by jhwangbo** [comment]
a fix has been pushed. Now ``meshes.cpp`` file tests this feature
