### ISSUE TITLE
Only half or less performance of Linux on Windows

### ISSUE THREAD

**Issue by yosagi** [raisimTech/raisimLib#168]
I ran the "speed_test" example on Windows10 and Ubuntu20.04 on the same machine (Ryzen 7 1800X 3.6GHz) and got these results.

On windows with the executable in mt_release directory:
```
❯ .\speed_test.exe
The simulation of ANYmal, 4 contacts is running at: 53.1208 kHz
The simulation of ANYmal, 0 contact is running at: 110.754 kHz
The simulation of Atlas is running at: 1.56531 kHz
average number of contacts 19.1467
The simulation of Atlas, no ground is running at: 15.8907 kHz
average number of contacts 2.72415
chain10 dof is 30
The simulation of Chain10 (30 dof) is running at: 74.7943 kHz
chain 20 dof is 60
The simulation of Chain20 (60 dof) is running at: 37.1333 kHz
```

On Linux with an executable built with RelWithDebInfo configuration:
```
$ ./speed_test 
The simulation of ANYmal, 4 contacts is running at: 119.232 kHz
The simulation of ANYmal, 0 contact is running at: 231 kHz
The simulation of Atlas is running at: 3.1737 kHz
average number of contacts 21.6697
The simulation of Atlas, no ground is running at: 15.1423 kHz
average number of contacts 6.99478
chain10 dof is 30
The simulation of Chain10 (30 dof) is running at: 188.679 kHz
chain 20 dof is 60
The simulation of Chain20 (60 dof) is running at: 94.162 kHz
```

What makes these differences? Are there any tips to get similar performance on windows as Linux?

**Comment by jhwangbo** [comment]
The compiler makes the difference. In windows, I used MSVC. In linux, I used Clang. Maybe it is also about the linker, but I am not sure... 
I also observe a wide range of performance across compilers on Linux.

**Comment by yosagi** [comment]
Thanks for the comment. So, there is nothing I can do as a library user, right?

**Comment by jhwangbo** [comment]
If you are interested in RL, the best thing you can do is to switch to Ubuntu. If you want to do something else, probably speed is not going to make a big difference because RaiSim can already simulate a robot much faster than real-time on Windows.
