### ISSUE TITLE
visualization with mesh files in raisimUnity

### ISSUE THREAD

**Issue by Pala-Ah** [raisimTech/raisimLib#17]
Is there anything to consider with using mesh files in raisimUnity? When I try to visualize the the hummingbird mesh from the previous raisimGym example with raisimOgre, only three of four arms of the base are visualized in raisimUnity. The fourth arm has still physical properties, but is just not visible. 

![Screenshot-2020-11-05-03-03-29](https://user-images.githubusercontent.com/60257014/98259490-7e4b3680-1f82-11eb-8666-e143f0db351a.png)

Also changing the colour didn't work out for me. I have set the colour of the mesh according to the anymal.urdf file:

```
  <link name="hummingbird/base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="../meshes/hummingbird.dae" scale="1 1 1"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.12"/>
      </geometry>
  </link>

  <joint name="hummingbird/base_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="hummingbird/base_link"/>
    <child link="hummingbird/base_link_inertia"/>
  </joint>

  <link name="hummingbird/base_link_inertia">
    <inertial>
      <mass value="0.68"/>
      <!-- [kg] -->
      <origin xyz="0 0 0"/>
      <inertia ixx="0.007" ixy="0.0" ixz="0.0" iyy="0.007" iyz="0.0" izz="0.012"/>
    </inertial>
    </collision>
  </link> 
```

**Comment by jhwangbo** [comment]
The color should be defined inside the mesh file. Currently, the color in the URDF file is ignored.

I think the mesh issue is due to its size. I will investigate

**Comment by jhwangbo** [comment]
The mesh has too many triangles. You have to resize the mesh.

**Comment by Pala-Ah** [comment]
simplifying and reducing mesh size worked out for me. thank you.
