### ISSUE TITLE
Compatibility of the license file between windows and linux

### ISSUE THREAD

**Issue by yosagi** [raisimTech/raisimLib#172]
I want to switch Windows and Linux on the same machine, but machine ids on the different platforms are not identical.
It is convenient if I can use the same license file on the same device regardless of running OS (Windows, WSL, Linux).
Could you consider this in the future release?

**Comment by jhwangbo** [comment]
The machine ID checks the account name. If you have a server machine that multiple users use, only the one who purchased the license should be able to use it. So I cannot make the activation key cross-platform.
