### ISSUE TITLE
Questions about the importance of GPUs 

### ISSUE THREAD

**Issue by jangmingyu** [raisimTech/raisimLib#176]
I'm trying to set up my computer for Raisim this time, and I know that Raisim supports CUDA as well. If the GPU performance is good, does the learning rate performance increase a lot? If not, I'd like to invest more in the CPU side.

**Comment by jhwangbo** [comment]
RaiSimGym supports GPU. RaiSim doesn't. The training time highly depends on your network structure and simulation environment. In the example setup, the CPU computation costs 10 times more than GPU computation. If you disable GPU, it might take about two times more overall.
