### ISSUE TITLE
Force random spikes at standing position

### ISSUE THREAD

**Issue by MichaelMarav** [raisimTech/raisimLib#183]
Hello,

We have been using raisim to simulate the NAO robot. We've noticed that when we spawn the robot, without giving any moving command, the robot starts to drift over time on its own (after 5-10 mins it's noticeable). We plotted the forces of each foot and there are some random spikes which probably propagate and cause the robot to slightly move clockwise.
![forceSpikes](https://user-images.githubusercontent.com/59025730/132661816-122c734d-a283-4e85-93f1-ddfbf1abe263.png)

After about five minutes of the simulator just open, this the pose of the robot:
![Screenshot from 2021-09-09 12-33-43](https://user-images.githubusercontent.com/59025730/132661972-c9441a38-d1f4-4bc6-981e-1b8e66f783d7.png)

We tried to change the variable dt from 0.01 to 0.001 and didn't seem to make much difference. The output was:

![Force001](https://user-images.githubusercontent.com/59025730/132662261-2ec64cf3-f66c-4f3f-9a29-df143a4a466b.png)

To compute the force, we use the following code:

for (auto &contact : NAO->getContacts())
    {
      // if (contact.skip())
      //   continue; /// if the contact is internal, one contact point is set to 'skip'
      if (RfootIndex == contact.getlocalBodyIndex())
      {
        footForce = contact.getContactFrame().e().transpose() * contact.getImpulse().e() / dt;
        RLegGRF += footForce;
        COPR += contact.getPosition().e() * footForce(2);
        footTorque = (contact.getPosition().e() - RfootPosition).cross(footForce);
        RLegGRT += footTorque;
        //cout<<"Right Contact Point "<<(contact.getPosition().e() ).transpose()<<" "<<contact.isObjectA()<<endl;
        if (contact.isObjectA())
          RSS = true;
      }
      if (LfootIndex == contact.getlocalBodyIndex())
      {
        footForce = (contact.getContactFrame().e().transpose() * contact.getImpulse().e()) / dt;
        LLegGRF += footForce;
        //cout<<"Left Contact Point "<<(contact.getPosition().e()).transpose()<<" "<<contact.isObjectA()<<endl;
        COPL += contact.getPosition().e() * footForce(2);
        footTorque =  (contact.getPosition().e() - LfootPosition).cross(footForce);
        LLegGRT += footTorque;
        if (contact.isObjectA())
          LSS = true;
      }
    }

**Comment by jhwangbo** [comment]
this is probably due to the shaky PD controller. Are you using the built-in one? Do you also see rotation if there is no actuation?

**Comment by MichaelMarav** [comment]
> this is probably due to the shaky PD controller. Are you using the built-in one? Do you also see rotation if there is no actuation?

Thanks for the reply.
Yes we are using the built-in one. And also yes, there is a rotation when there is no actuation.

**Comment by MichaelMarav** [comment]
@jhwangbo  Thanks for the reply.
Yes we are using the built-in one. And no there is no rotation when there is no actuation. The robot remains completely still.

**Comment by jhwangbo** [comment]
Sorry for getting back to you late. I was busy with RAL and ICRA deadlines.

You have to use your own controller then. The PD controller is not a normal PD controller. It is model-based control and it is making a few assumptions like that is no contact. You can apply any generalized force you want so you can implement your own controller

**Comment by MichaelMarav** [comment]
@jhwangbo 

Assuming I want to implement a PD law of the form \tau  = Kp*(theta_d-theta) + Kd*(\dot{theta_d)-\dot{theta}) where \tau is the joint torque and theta,\dot{theta} the joint angle/velocity. I just call the  inline void setGeneralizedForce(const Eigen::VectorXd &tau)
and integrate() the world afterwards?

**Comment by jhwangbo** [comment]
Yes. Don't forget that the generalized force includes forces on the main body. Its dimension is the number of DOF's of the system.

**Comment by MichaelMarav** [comment]
@jhwangbo 
Ok, thank you very much!
