### ISSUE TITLE
Loading Mujoco File with Actuated Base Position

### ISSUE THREAD

**Issue by christsa** [raisimTech/raisimLib#184]
Hi Jemin

I want to actuate the floating base of a model. 
I've tried the two following things:

1. Adding a free joint and actuating it via PD control
2. Instead of a free joint, add 6 DoF and add it to a fixed body

Unfortunately, neither of them worked.  Both models can be loaded in the simulator. However, when trying to add control components, they either are not actuated (case 1.) or they disappear (case 2.). 

Here is a snippet of the version where I added the 6 DoF as a combination of prismatic and revolute joints, and a fixed base.
Also note that I had to split up the floating base into two different bodies, since adding all 6DoF to one body made the model not being loaded in the sim even without control components.

```
<body name="root" pos="0 0 0">
<geom name="base_fixed" pos="0 0 0.0" rgba="0 0 1 1" size="0.0175" type="sphere" contype="1" conaffinity="1"/>
<body name="palm" pos="0 0 0">
<joint axis="1 0 0" damping="1" name="palmx" pos="0 0 0" range="-2 2" type="slide"/>
<joint axis="0 1 0" damping="1" name="palmy" pos="0 0 0" range="-2 2" type="slide"/>
<joint axis="0 0 1" damping="1" name="palmz" pos="0 0 0" range="-2 2" type="slide"/>
<geom name="dumy_palm_rot" pos="0 0 0.0" rgba="0 0 0 1" size="0.0075" type="sphere" contype="1" conaffinity="1"/>
<body name="palm_rot" pos="0 0 0">
<joint axis="1 0 0" damping="1" name="palmrx" pos="0 0 0" range="-3.14 3.14" type="hinge"/>
<joint axis="0 1 0" damping="1" name="palmry" pos="0 0 0" range="-3.14 3.14" type="hinge"/>
<joint axis="0 0 1" damping="1" name="palmrz" pos="0 0 0" range="-3.14 3.14" type="hinge"/>
<geom name="C_palm" pos="-0.0427474 -0.00253755 0.0096626" quat="0.624456 -0.0462835 0.779687 0" size="0.0075 0.0438992" type="capsule" contype="1" conaffinity="1"/>
```

Would you know any solution to this?

Thanks for the help.

**Comment by jhwangbo** [comment]
I finished and tested the fix. I'll push it tonight

**Comment by jhwangbo** [comment]
the fix has been pushed. Let me know if it doesn't work for you
