### ISSUE TITLE
How to add new rewards in RAISIM

### ISSUE THREAD

**Issue by SKYLEO98** [raisimTech/raisimLib#192]
Hello, I really appreciate your support since I started to implement RAISIM.
In raisim, as I read in the environment.hpp and rewards.hpp about the record function to add a rewards function.

void record (const std::string& name, float reward, bool accumulate = false) {
    RSFATAL_IF(rewards_.find(name) == rewards_.end(), name<<" was not found in the configuration file")
    RSISNAN_MSG(reward, name<<" is nan")

    if(!accumulate)
      rewards_[name].reward = 0.f;
    rewards_[name].reward += reward * rewards_[name].coefficient;
    rewards_[name].integral += rewards_[name].reward;
  }

rewards_.record("torque", anymal_->getGeneralizedForce().squaredNorm());
rewards_.record("forwardVel", std::min(4.0, bodyLinearVel_[0]));

My model is an robotic excavator without moving the crawlers so it is considered as a 6-dofs manipulator (this excavator consists of tilt-roll DOFs between the bucket and arm so it expands more 2 DOFs). 
I set an initial position for the bucket tip and a different target position then I calculate the error.
-------------------these lines were added in the void updateObservation() ---------------------
    anymal_->getFramePosition(bucketID, bucketPosUpdateRaisim);
    bucketPosUpdate = bucketPosUpdateRaisim.e();
    bucketPosTarget << 2.95, 0.00, 1.14;
    bucketPosErr = (bucketPosUpdate - bucketPosTarget)*100;
-------------------------------------------------------------------------------------------------
(These above lines were added in the void updateObservation() )

Then, I added the rewards for error for x, y and z, also inactivated two preceding rewards
-------------------these lines were added  in the environment.hpp  ---------------------
//rewards_.record("torque", anymal_->getGeneralizedForce().squaredNorm());
//rewards_.record("forwardVel", std::min(4.0, bodyLinearVel_[0]));
rewards_.record("bucketPositionX", 1 / (std::max(5.0, std::abs(bucketPosErr[0]))));
rewards_.record("bucketPositionY", 1 / (std::max(5.0, std::abs(bucketPosErr[1]))));
rewards_.record("bucketPositionZ", 1 / (std::max(5.0, std::abs(bucketPosErr[2]))));
-------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/90736860/134839056-174f4c93-ac2c-4538-b036-9ffb63c48dc2.png)
As you can see from the image during the learning, I cout the target position, updateposition, current error and rewards,
target position is [2.95 0 1.14] (unit is meter)
update position is [3.01749 -0.036871 1.00742]  (unit is meter)
error is [-90.0407 -0.100142 -15.5597]  (error is converted to cm unit to prevent the value below 1)
rewards sum is 23.968

I checked the result after 1600 iterations, the manipulator just hold and vibrates around the initial position. 
I wonder if I conducted the right code for adding the rewards in environment file?

I hope your consideration for this RAISIM issue, not learning issue due to the reward issue during modifying the environment in RAISIM.

**Comment by jhwangbo** [comment]
Did you add the coefficient in the cfg.yaml?

**Comment by SKYLEO98** [comment]
Thank you for your soon reply.

I also added three coefficients for bucketPositionX, bucketPositionY and bucketPositionZ with same value as 0.7 in the cfg.yaml

**Comment by jhwangbo** [comment]
I don't get your question. If you are not sure if the reward is added, you can just cout the reward and check.

**Comment by jhwangbo** [comment]
This question is nothing to do with RaiSIm and RaisimGym. I cannot help you with RL...
