### ISSUE TITLE
iteration lasts infinite time with one thread left

### ISSUE THREAD

**Issue by fanshi14** [raisimTech/raisimLib#194]
Hi Jemin,

I have met the problem several times, that learning stuck into one iteration in the middle of learning.
When checking `htop`, there is only one CPU thread keeps 100% usage, while other threads have finished their jobs and change to 0%.
If repeating the same experiments, the problem does not always happen but appear in different iteration numbers if happening.

It seems hard to debug, may I ask your hint that the stuck comes from simulator or pyTorch learning?

Thank you in advance.
Fan

**Comment by jhwangbo** [comment]
I guess you are talking about your learning example.

There is no infinite loop (e.g., while loop) in RaiSim. I also doubt that pyTorch has such a loop. Do you have a while loop in your ``Environment.hpp`` file?

Did you also check it with Valgrind+Debug_App? An illegal memory write can create such a loop.

**Comment by jhwangbo** [comment]
I am closing this issue until I get a further response.

**Comment by fanshi14** [comment]
I found a memory leak in my code with Valgrind.
Then after long-time test, the problem does not happen any longer.
Thank you, Jemin.
