### ISSUE TITLE
License for a server

### ISSUE THREAD

**Issue by kniranjankumar** [raisimTech/raisimLib#195]
Hi, thanks for maintaining this awesome library!
We have a cluster with a few dozen nodes and a manager that allocates resources as required by the users. To run raisim on this server, do I have to get a new license for each node or Is there a better way to do this?

I saw the following in the license email - 
"You cannot run RaiSim on a third-party server machine unless you have a master key. We provide a master key to customers who has more than 3 active commercial licenses."

But is there any alternative for an academic license?

**Comment by jhwangbo** [comment]
There is no alternative for an academic license. If such a master key is leaked, this will critically impact our sales.
