### ISSUE TITLE
Raisim License for Multiple Computers

### ISSUE THREAD

**Issue by costashatz** [raisimTech/raisimlib#2]
Thanks for the new release!

With the new license scheme, are there any options available for a license that enables us using raisim in multiple computers? An example use case would be a cluster where we compile in one PC and then run our programs in multiple different PCs.

Thanks in advance!

**Comment by jhwangbo** [comment]
You can apply multiple times for multiple activation keys. Then your name should be suffixed by the key number, e.g., "costaschtaz1",
