### ISSUE TITLE
Wrong relationship between angular velocity and roll, pitch, yaw

### ISSUE THREAD

**Issue by ZQX323** [raisimTech/raisimLib#20]
Hello,

I use the following code to get the roll, pitch, and yaw. I think they should be angular positions between robot coordinate and world coordinate. 

```
            q_ = anymal_->getGeneralizedCoordinate().e();
            Eigen::Matrix<double, 4, 1> quat = q_.segment<4>(3);
            double r, p, y;
            Math::MathFunc::QuattoEuler(quat, r, p, y);
```

And I calculate angular velocity with respect to world coordinate and robot coordinate using the following code. Turned out they are not the derivative of roll, pitch, and yaw. Did I make some mistakes? 
```
            u_ = anymal_->getGeneralizedVelocity().e();
            R_b_ = Math::MathFunc::quatToRotMat(quat);
//          auto bodyAngularVel = R_b_.transpose() * u_.template segment<3>(3);
            auto bodyAngularVel = u_.segment<3>(3);

```

**Comment by jhwangbo** [comment]
No, they should be different. Euler angles are like axis-by-axis rotations. I dont know a good ref for that but maybe wiki can help you.
