### ISSUE TITLE
ReadData timeout! after setting material pair properties

### ISSUE THREAD

**Issue by MichaelMarav** [raisimTech/raisimLib#202]
Hello,

I am simulating the ATLAS robot using raisim. I tried to change the friction coefficients between the robot and the ground. The material of the atlas is "", which I assume is the default material. After reading the documentation I added the following to my code.

```
raisim::World world;

auto ground = world.addGround(0.0,"glass");

world.setMaterialPairProp("", "glass", 0.15, 0.1, 0.15);
```
If I change friction to 0, it is indeed applied to the robot. But when the friction value is > 0, although the robot moves forward as expected, when it tries to move sideways raisim crashes with the following error in the unity window:

![error](https://user-images.githubusercontent.com/59025730/136364787-e2e03cba-ef8f-4c84-961b-f1a29d657e49.png)

And the following message in the terminal:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
./run_atlas.sh: line 50:  5960 Aborted                 (core dumped) LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH "$PATHOFBIN" --from $DIR $@
```

If I remove the `world.setMaterialPairProp(...)`, everything works just fine. I also tried tweaking the input parameters but nothing changed.

**Comment by jhwangbo** [comment]
I could reproduce it with the existing example. The issue is that the default material is "default" not "". But it shouldn't terminate even if it cannot find the material pair. It should just use the default setting. I fixed this and push
