### ISSUE TITLE
    obDim_ = 34; how to set this value

### ISSUE THREAD

**Issue by SKYLEO98** [raisimTech/raisimLib#204]
Hello, in the environment.hpp, there is a line to set the obDim =34
How can I determine this value for obDim?

Besides, in the runner.py 
cfg = YAML().load(open(task_path + "/cfg.yaml", 'r'))
# create environment from the configuration file
env = VecEnv(excavatorRL.RaisimGymEnv(home_path + "/rsc", dump(cfg['environment'], Dumper=RoundTripDumper)), cfg['environment'])

Do I have to add my urdf model in the home_path + "/rsc"?

**Comment by jhwangbo** [comment]
obDim is the dimension of the observation. It's something that you design.
Print out what is home_path+"/rsc" is. Then just copy-paste your files there
