### ISSUE TITLE
Joint limits error

### ISSUE THREAD

**Issue by grizzi** [raisimTech/raisimLib#206]
Hi, 
I have been experiencing the following error: 
```
revolute/prisimatic joint limit is not working well :  gv 6.74677e+12 7.39126e+11 9.99869e+12 0.03125 -8.18541e+12 1.72003e+14 1.10458e+14 -2.67287e+13 -6.20539e+14 -3.65148e+13 -2.49202e+15 2.49879e+15
```

I have difficulty to debug such a problem as the error string is not so informative. The robot is a 7dof arm + 2 finger gripper + an omnidirectional planar base (modeled as two prismatic joints and a revolute one). Thanks in advance for any tip!

EDIT: I am using raisim v1.1.0

**Comment by grizzi** [comment]
Thanks for your answer. It happens once after which the sim crashes. The robot described above is simulated with the builtin PD controller.

The simulation is reset using the actual robot joints odometry. Can the divergence be given by resetting with a noisy joint velocity values?

**Comment by jhwangbo** [comment]
As I wrote above, this error is nothing to do with the joint limit. It means that the GV exploded. There are too many possible reasons. You should first run Valgrind and debug your code first.

**Comment by grizzi** [comment]
After longer investigation, I found this was due to another bug in the code. Thanks in any case for the support!
