### ISSUE TITLE
ERP settings

### ISSUE THREAD

**Issue by grizzi** [raisimTech/raisimLib#210]
Hi, 
this issue is to understand how to optimally tune the simulator. In my simulation, a gripper is applying a big force onto the handle of an articulated object. After a continuous contact, the gripper seems to slowly compenetrate the handle under the action of the applied force until the gripper completely trapasses the object. 

I immagine this is due to the numerical errors during integration. Setting the ERP to 1 with `sim_.setERP(1., 0.);` the phenomenon does not show up anymore. I understand that the simulator is applying some sort of correction but the documentation does not say much about this param and the actual effects is has on simulation accuracy. It rather says that ` It often has very minimalistic impact on simulation` and that it has no physical meaning. 

Could you shed some light here? Thanks!

**Comment by jhwangbo** [comment]
This penetration can happen if the two objects have very different masses. In this case, the contact problem becomes much harder. One thing you can try is to increase the solver iteration. Try if this helps: ``world.setContactSolverParam(1.0, 1.0, 1.0, 200, 1e-8)``.
 I'll update the doc to describe ERP more thoroughly
