### ISSUE TITLE
Abnormal behaviour of sliding across several height map

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#212]
It seems that with the newest version, when the robot slides across several height maps, the first transition results to weird jumps of the robot

https://user-images.githubusercontent.com/8019238/137812946-dcac91ca-e7cf-491e-8c94-e3ba584df836.mp4

while later the transition works perfectly fine:

https://user-images.githubusercontent.com/8019238/137812989-0a978166-b787-4145-83af-1945404dcea2.mp4

Do you have an idea why this is happening? Thanks! Here is also the source code:
[Example.zip](https://github.com/raisimTech/raisimLib/files/7368778/Example.zip)

**Comment by jhwangbo** [comment]
That is definitely strange. I'll look into it today

**Comment by weixuanzhang** [comment]
Hi Jemin, 
any updates on this? Thanks!

**Comment by jhwangbo** [comment]
Sorry for getting back to you late. The heightmap is a bunch of lines and faces. I guess this is unavoidable. One way is to reduce the time step. You can play with the ERP variable as well.

**Comment by weixuanzhang** [comment]
No worries. Thanks for your feedback and I will have a look into the ERP variable.

**Comment by weixuanzhang** [comment]
For the record, setERP(0.1, 0.1) helps to mitigate the issue.
