### ISSUE TITLE
Set external torque in body frame

### ISSUE THREAD

**Issue by ecuniato** [raisimTech/raisimLib#217]
The method setExternalTorque(size_t bodyIdx, const Vec<3> &torque_in_world_frame) only allows for setting torques is the world frame. It would be useful to have another method to set torques in the body frame, as we already have with:
setExternalForce(size_t bodyIdx, Frame frameOfForce, const Vec<3> &force, Frame frameOfPos, const Vec<3> &pos)

**Comment by jhwangbo** [comment]
I pushed the method for linux version. other versions will follow
