### ISSUE TITLE
Question about setMaterialPairProp

### ISSUE THREAD

**Issue by chongt123** [raisimTech/raisimLib#225]
When I use the setMaterialPairProp function to change my robot feet friction with the terrain in my simulation (every reset) and train my networks (pytorch), I got the error:

terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

But when I loaded trained networks and then train them, the simulation worked for a little episodes.

What should I do for that?

Thank you for your help!!!

**Comment by jhwangbo** [comment]
Do you have the latest version? I remember fixing this issue

**Comment by chongt123** [comment]
> Do you have the latest version? I remember fixing this issue

The latest version works. Thanks so much.
