### ISSUE TITLE
windows error compiling raisimGymTorch

### ISSUE THREAD

**Issue by Wjzsearcher** [raisimTech/raisimLib#226]
The raisimLib was successfully compiled on windows.
However when I tried to compile raisimGymTorch by "python setup.py develop", there was nothing generated under raisimGymTorch/raisimGymTorch/env/bin. The files were not compiled well as shown below, about **Command line warning D9002: ignoring unknown option**
Any insights on how to resolve this? Is there anthing wrong with Visual Studio 2019?

**Powershell output:**
PS F:\program_study\raisimLib\raisimGymTorch> python setup.py develop
running develop
running egg_info
writing raisim_gym_torch.egg-info\PKG-INFO
writing dependency_links to raisim_gym_torch.egg-info\dependency_links.txt
writing requirements to raisim_gym_torch.egg-info\requires.txt
writing top-level names to raisim_gym_torch.egg-info\top_level.txt
reading manifest file 'raisim_gym_torch.egg-info\SOURCES.txt'
writing manifest file 'raisim_gym_torch.egg-info\SOURCES.txt'
running build_ext
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- pybind11 v2.6.2
-- Found PythonInterp: E:/program/Anaconda3/python.exe (found version "3.7.6")
-- Found PythonLibs: E:/program/Anaconda3/libs/python37.lib
-- raisim:
--   Version: 1.1.0
--   Includes: F:/program_study/raisimLib/raisim/win32/mt_debug/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;raisim::raisim
raisim os win32
raisim arch
-- Configuring done
-- Generating done
-- Build files have been written to: F:/program_study/raisimLib/raisimGymTorch/build/temp.
    Checking Build System
    Building Custom Rule F:/program_study/raisimLib/raisimGymTorch/CMakeLists.txt
cl : Command line warning D9002: ignoring unknown option“-fopenmp” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-fPIC” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-O3” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-g” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-mno-avx2” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-fopenmp” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-fPIC” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-O3” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-g” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-mno-avx2” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
  raisim_gym.cpp
cl : Command line warning D9002: ignoring unknown option“-fopenmp” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-fPIC” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-O3” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-g” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
cl : Command line warning D9002: ignoring unknown option“-mno-avx2” [F:\program_study\raisimLib\raisimGymTorch\build\temp.win-amd64-3.7\Release\rsg_anymal.vcxproj]
  Yaml.cpp

**Comment by jhwangbo** [comment]
is that all of the message? is there any error?

**Comment by Wjzsearcher** [comment]
Thanks for reply, at last I successfully started runner.py, but there were some errors about tensorboard and tensorflow. The policy training could be visualized. Are these errors important for training?
````````````````````````````````````````````````````
E:\program\Anaconda3\envs\pytorch\python.exe F:/program_study/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py
Exception in thread Reloader:
Traceback (most recent call last):
  File "E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\__init__.py", line 46, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\program\Anaconda3\envs\pytorch\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\program\Anaconda3\envs\pytorch\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\backend\event_processing\data_ingester.py", line 100, in _reload
    self._multiplexer.AddRunsFromDirectory(path, name)
  File "E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 202, in AddRunsFromDirectory
    for subdir in io_wrapper.GetLogdirSubdirectories(path):
  File "E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\backend\event_processing\io_wrapper.py", line 206, in GetLogdirSubdirectories
    if not tf.io.gfile.exists(path):
  File "E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\lazy.py", line 68, in __getattr__
    return getattr(load_once(self), attr_name)
  File "E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\lazy.py", line 100, in wrapper
    cache[arg] = f(arg)
  File "E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\lazy.py", line 53, in load_once
    module = load_fn()
  File "E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorboard\compat\__init__.py", line 49, in tf
    import tensorflow
  File "E:\program\Anaconda3\envs\pytorch\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 149, in __enter__
  File "<frozen importlib._bootstrap>", line 94, in acquire
_frozen_importlib._DeadlockError: deadlock detected by _ModuleLock('tensorflow.python') at 1579685294664

[RAISIM_GYM] Tensorboard session created: http://localhost:6006/
Visualizing and evaluating the current policy
----------------------------------------------------
     0th iteration
average ll reward:                       -0.3149552060
dones:                                   0.017175
time elapsed in this iteration:          25.8820
fps:                                       1545
real time factor:                            15
std: 
[2.7023168 2.7161872 2.7022595 2.7157562 2.7169547 2.7056487 2.702694
 2.713164  2.7128372 2.7076957 2.7082825 2.7229156]
----------------------------------------------------
`````````````````````````````````````````````````````

**Comment by jhwangbo** [comment]
Could you share how you solved the issue?
The tensorboard is a good visualization tool. It might be useful for some debugging jobs. But it is not fundamental to the training.
I think your pytorch version does not support your tensorboard version. Did you install them prior to your current RaiSim project?

**Comment by Wjzsearcher** [comment]
In the first place, although there was no important error when I ran the setup.py, the error below occurred when I ran runner.py.

````````
E:\program\Anaconda3\envs\pytorch\python.exe F:/program_study/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py
Traceback (most recent call last):
  File "F:/program_study/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 2, in <module>
    from raisimGymTorch.env.bin import rsg_anymal
ImportError: DLL load failed: Module not found
```````````````````

With some effort, I copied all the raisim*.dll to raisimGymTorch/raisimGymTorch/env/bin, then the issue was solved.

**For error about tensorboard**
Just as you saied, I installed them prior to my current RaiSim project. My pytorch was 1.10.0, tensorboard was 2.4.0. Do I need to uninstall the tensorboard if I want to solve this issue?

**Comment by jhwangbo** [comment]
The proper way to do it is to add the path of the raisim in your environment variable as described in https://raisim.com/sections/Installation.html

You have to install the tensorboard version that is supported by your pytorch version. You can find the version instructions in the pytorch website
