### ISSUE TITLE
How can I calculate the internal contact force between bodies connected by a fixed joint?

### ISSUE THREAD

**Issue by emreutku** [raisimTech/raisimLib#228]
Hello,
I am trying to obtain the contact forces between two bodies connected by a fixed joint. The location of the fixed joint is highlighted by a red circle in the photo below. I tried to use getContacts method but I could not obtain a meaningful result. As far as I have seen in my simulations Raisim only calculates the ground reaction forces and the forces between bodies which are not connected directly. Is it possible to obtain these internal contact forces within Raisim?
Thank you for your help!
![image](https://user-images.githubusercontent.com/51458858/143833870-70687afd-9755-4639-aae8-eab4a4c7b303.png)

**Comment by jhwangbo** [comment]
A fixed joint essentially merges two bodies. It does not compute any force elements. At the moment, it is not possible to compute the force at fixed joints.

**Comment by emreutku** [comment]
Do you have any suggestion for computing these kind of internal contact forces? Is it also impossible to compute the force at any other kinds of joints such as revolute joints?

**Comment by jhwangbo** [comment]
The only way I can think of is to convert the fixed joint to a 6-dof joint and use the built-in PD controller.

**Comment by emreutku** [comment]
Thanks for the advice. Another method is to connect two solid bodies by a small cube with a defined stiffness. If we know the distance between any two sides of the cube then we can estimate the 3 dimensional contact force by using the spring equation(F=k*x) However, we have to be able to know the distance between any two sides of the cube. Is this applicable in Raisim?

**Comment by jhwangbo** [comment]
I am not sure what you mean by "a small cube with a defined stiffness". You cannot simulate a compliant body in RaiSim
