### ISSUE TITLE
About the simulation speed

### ISSUE THREAD

**Issue by jangmingyu** [raisimTech/raisimLib#230]
Hello, I am currently trying to do reinforcement learning through a robot with 29 joints. The size of the robot is about 12m, and reinforcement learning is performed by applying the URDF format, and the repetition rate of one reinforcement learning is about 400FPS. This rate is considered too slow.

1. Could it be slow due to multiple collisions issues?

2. If so, does disabling collisions between all links solve the problem?

3. Will reducing the size of the robot improve speed?

I would appreciate it if you could give me a brief comment.

I'll attach the URDF file.

[Full_model_Light.zip](https://github.com/raisimTech/raisimLib/files/7644778/Full_model_Light.zip)

**Comment by jhwangbo** [comment]
1. check internal contacts. Probably you have unrealistic internal collisions even in a nominal configuration
2.  how many collision bodies do you have? it can slow down if you have more than 200

**Comment by jangmingyu** [comment]
Thanks for the quick reply.

Are you referring to the part where the internal contact is overlapped between links?

Does increasing the size of the robot have a worse effect on its speed when there is internal contact?

**Comment by jhwangbo** [comment]
`Are you referring to the part where the internal contact is overlapped between links?` - yes
`Does increasing the size of the robot have a worse effect on its speed when there is internal contact?` - no

**Comment by jangmingyu** [comment]
Thanks I solved the problem!
