### ISSUE TITLE
getGeneralizedCoordinate gives half of the actual floating base orientation

### ISSUE THREAD

**Issue by erimcanozcinar** [raisimTech/raisimLib#231]
I am trying to get floating base orientation in terms of euler angle. However, getGeneralizedCoordinate gives half of the actual torso orientation. I compare the result from getGeneralizedCoordinate function with unity display and result from getGeneralizedCoordinate function is exactly the half of the unity display. I also tried to rotate torso 10 degree but again getGeneralizedCoordinate function gives 5 degree. Why getGeneralizedCoordinate function gives half of the actual orientation?

**Comment by jhwangbo** [comment]
getGeneralizedCoordinate returns a quaternion. How did you convert it? Unity displays rotation vector

**Comment by erimcanozcinar** [comment]
I did not noticed that getGeneralizedCoordinate function returns quaternion. My mistake. When I convert quaternion to euler angles it works fine. Thank your for your fast reply.
