### ISSUE TITLE
cannot work with LCM

### ISSUE THREAD

**Issue by chinahuangyong** [raisimTech/raisimLib#234]
hello,
i try to use lcm in raisim project, but when i launch sever, i get  Segmentation fault in Linux.

my computer is DELL inspiron 3891
the system is Ubuntu18.04.5
lcm version is V1.4.1

**Comment by jhwangbo** [comment]
You have to provide all details of the issue. Provide the minimum reproduceable code. Which line does it segfault? Does it segfault without LCM? Why do you suspect that it is a raisim problem?

I am closing this issue until I get full details.
