### ISSUE TITLE
Raisim Sphere Passing Through URDF Objects

### ISSUE THREAD

**Issue by DenoYx** [raisimTech/raisimLib#235]
Hello,

I am trying to build a setup for the ball balancing task using **the Franka Emika Panda URDF, a tray, and a sphere.** I added the tray to the end effector of the Panda in the URDF file but when I add the sphere to the setup either as a separate URDF or with "addsphere" command in Visual Studio, the ball is passing through the tray and just contacts with the robot. 

- I tried to put just a box instead of a tray in order to understand if the mesh of the tray is causing this situation, but still it did not work.

- Also I tried to put one more mock link and the joint between tray and Panda, but still could not solve the problem.

I am going to add a video to be able to visualize the issue. Thanks in advance.

**Video:** https://drive.google.com/file/d/1xlmi2zY6T_YjpFG7_CJdoBq2EqIDMGx_/view?usp=sharing

**Comment by jhwangbo** [comment]
can you just visualize the collision bodies?

**Comment by DenizYilmazx** [comment]
> can you just visualize the collision bodies?

Here is the video with just collision bodies. I also add the contact forces and points for better understanding.

**Video:** https://drive.google.com/file/d/1QEZ4p-06IiXi4tsl-SGij4orD5gYI31o/view?usp=sharing

**Comment by jhwangbo** [comment]
can you share the urdf?

**Comment by jhwangbo** [comment]
and maybe the code that you used

**Comment by DenoYx** [comment]
> can you share the urdf?

I added both meshes and URDF and .cpp files.

[Panda_2.zip](https://github.com/raisimTech/raisimLib/files/7710544/Panda_2.zip)

**Comment by jhwangbo** [comment]
why do you have two origins for collision bodies?

**Comment by DenoYx** [comment]
> 

I forgot to comment out the second origin. The first one is for the box and the second one was for the mesh. This part will be as follows,

```
		<link name="tray">
	<inertial>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<!-- <origin rpy="0 0 0" xyz="-0.2 -0.1 0"/> -->
			<mass value="1"/>
			<inertia ixx="0.226" ixy="-0.02473" ixz="0.01" iyy="0.191" iyz="-0.002" izz="0.132"/>
		</inertial>
		<visual>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<!-- <origin rpy="0 0 0" xyz="-0.2 -0.1 0"/> -->
		  <geometry>
			<box size="0.2 0.4 0.04"/>
			<!-- <mesh filename="../meshes/collision/Tepsi.obj" scale="0.001 0.001 0.001" /> -->
		  </geometry>
		</visual>
		<collision>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<!-- <origin rpy="0 0 0" xyz="-0.2 -0.1 0"/> -->
		  <geometry>
			<box size="0.2 0.4 0.04"/>
			<!-- <mesh filename="../meshes/collision/Tepsi.obj" scale="0.001 0.001 0.001" /> -->
			<!-- <sphere radius ="0.2"/> -->
		  </geometry>
		</collision>
	</link>
```

**Comment by jhwangbo** [comment]
does that change the simulation result?

**Comment by DenoYx** [comment]
> does that change the simulation result?

Unfortunately, it does not change the result. Both with the box and the tray(mesh) the result is same.

**Comment by jhwangbo** [comment]
The reason is that you are overwriting the raisim dynamics with setGeneralizedCoordinate. If you call this function in every loop, you are not simulating the system... You should hold the robot in position using a position controller (like the one included in RaiSim)
