### ISSUE TITLE
Robot model color change related

### ISSUE THREAD

**Issue by jangmingyu** [raisimTech/raisimLib#240]
Hi Bo Jemin Hwang, I'm running Lysim this time, it's not a big problem, but I have a question.

As shown in the figure below, it was confirmed that the color of the link changes when the joint of the link changes over a certain range.

![스크린샷, 2021-12-20 00-58-00](https://user-images.githubusercontent.com/37793152/146681827-9bdf5b3c-d9a5-41b8-99b4-6c0650ed84fb.png)

All links have the same material and color. Is it an internal contact issue? Does the color change due to internal contact?

**Comment by jhwangbo** [comment]
I think the color is from the mesh itself. If you send me the urdf and mesh files, I can check them later today

**Comment by jangmingyu** [comment]
[Full_model_skeleton_2.zip](https://github.com/raisimTech/raisimLib/files/7742749/Full_model_skeleton_2.zip)

thank you. URD file is attached.

I would appreciate it if you could take a look when you have time.

**Comment by jhwangbo** [comment]
the color tags in URDF all have different values.
