### ISSUE TITLE
Collision Mismatch on Borders of Heightmaps

### ISSUE THREAD

**Issue by Wang-Zhicheng** [raisimTech/raisimLib#241]
Hi there,

I have been trying to create uneven and discrete terrain with pits like in _BipedWalker-Hardcore_ environment(pic1) , and I chose to put a series of heightmaps in the RaiSim world with _world::addHeightmap()_, since it is impossible to generate vertical height variance within a single heightmap, and heavy boxes may slip when robot stepping on it. 
pic1: wanted environment be like:
![BipedWalker](https://user-images.githubusercontent.com/50918255/147078993-2591ccf8-f80e-4bf0-ae4a-ca209848c87d.jpg)

The problem is when my robot steps on the edge of the small heightmap, the heel is still in the height map, but the CoG seems to go over the edge in to the pit. However, the robot can still step on something flat, and the contact points between the foot and void can be rendered. I used _addBox()_ to test it(_pic2_):
pic2: box test with the heightmaps
![hm1](https://user-images.githubusercontent.com/50918255/147079039-22e51e1a-a0ec-45bc-a4ce-6bcec9b1f006.png)

The blue box on the right side, its most part is out of the heightmap, but it made contact with something. It seems like the heightmap is bigger than I can see(I tried with both 'visual bodies' and 'collision bodies' mode and the heightmap showed no differences). The other possible explanation is that the box can have four contact points on corners of its bottom face as long as it has a smallest part made contact with the heightmap.

I also tried to cover the heightmaps with some planks, and most of the contact things become normal(_pic3_). However I found some cubes floating in the air under the heightmaps(_pic4_) while most of them just dropped into void. I wonder if object whose horizontal coordinate is within the range of ground or heightmaps will slowly float upward?
pic3: right situation
![hmpp](https://user-images.githubusercontent.com/50918255/147079063-15cc1835-9429-4744-a3de-46147310f492.png)

pic4: floating objects
![hmppf](https://user-images.githubusercontent.com/50918255/147079106-234bdb1d-cbf4-4b67-af59-d0e265a3a77d.jpg)

Are my guess above right? And is there any other recommended methods to create terrain I wanted?

Hope for the reply. Appreciations.

**Comment by jhwangbo** [comment]
do you have the latest version? I thought this issue is already addressed

**Comment by Wang-Zhicheng** [comment]
I am afraid I am using the latest one.
I even tried download and re-install the current version, but nothing changed.

**Comment by Wang-Zhicheng** [comment]
I don't know if there's anything to do with my way of adding the height map: I created a 2x2 vector and filled it with 0.0, an then I added a heightmap with only 4 values( it's actually a simple flat plane). I am not sure if its resolution is too low.

**Comment by jhwangbo** [comment]
can you share a minimum reproducible code?

**Comment by Wang-Zhicheng** [comment]
Sorry, I have tried again with latest master and purged all cached files.
Things are better now, the objects on the edge are no longer stuck on the heightmap, despite that some of the cubes on the  were sinking through the heightmap.
like this:
![Screenshot-2021-12-23-08-39-43 (2)](https://user-images.githubusercontent.com/50918255/147242879-b746f5e6-d75e-4abb-afb2-e0921761781b.png)
If it is normal then I guess this issue can be closed.

code attached.(CPP file in TXT format)
[heightMapGenTest.txt](https://github.com/raisimTech/raisimLib/files/7769364/heightMapGenTest.txt)

**Comment by jhwangbo** [comment]
I investigated this issue for a while. I don't think there is an efficient way to solve the boundary issue. This only happens at the boundaries...
