### ISSUE TITLE
abnormal tort performance when using same controller in raisim and minicheetah-simulator

### ISSUE THREAD

**Issue by Abedcoder** [raisimTech/raisimLib#248]
Dear Professor Jemin Hwangbo:

I am trying to transfer my simulaiton platform form minicheetah-simulator to raisim. 

As the video below shows, my controller can work normal in `51` and `1` state(joint PD control), but when it transited to `4` state, which is to controll quadruped to walk in tort gait(MPC+WBC), it walked abnormal in raisim, and in minicheetah-simulator window, you can see the unitree A1 is more unstable than raisim, that's weird.

After that, I showed my controller can walk normally in minicheetah-simluator, in fact, my controller has been verified in real unitree A1, too. 

So, I'm confused why did my code worked abnormally in raisim while it worked normally in minicheetah-simulator and real quadrupeds. Will set foot and ground with material pair work? Or did I missed some specific steps after `addArticulatedSystem` ? 

Thank you

https://user-images.githubusercontent.com/68320458/150104540-135ad65c-59da-4048-8907-17bc4d713f22.mp4

**Comment by jhwangbo** [comment]
I am not sure what the video shows. I am sorry but your question is also not very clear.

The two simulators are very different. The biggest difference is the contact model. The minicheetah simulator only uses a point contact while RaiSim uses proper 3d collision geometry. There are differences in friction, damping, etc.

The material can also make the difference. Check the friction coefficient in the minicheetah and change it in RaiSim accordingly.

**Comment by Abedcoder** [comment]
> I am not sure what the video shows. I am sorry but your question is also not very clear.
> 
> The two simulators are very different. The biggest difference is the contact model. The minicheetah simulator only uses a point contact while RaiSim uses proper 3d collision geometry. There are differences in friction, damping, etc.
> 
> The material can also make the difference. Check the friction coefficient in the minicheetah and change it in RaiSim accordingly.

I'm sorry not to be clear enough. My puzzle lies in why my controller worked well in real robot but really unstable in raisim, and how should I solve this question. 

I konw it might be very basic, but after read documents in raisim.com , I still don't konw how to  `Check the friction coefficient in the minicheetah and ***change it in RaiSim*** accordingly`, can you give me some instructions or links?  Thank you!

**Comment by jhwangbo** [comment]
The best way to find it is to go to raisim.com and search for "friction"

**Comment by jhwangbo** [comment]
I am closing this issue. Let me know if you have further questiosn

**Comment by Abedcoder** [comment]
Hi, I've tried `setMaterialPairProp` with ground and foot, but it didn't get better. At last, I've found it's my fault to use `v[k+1] - v[k]) / dt` to approximate `acceleration form IMU`. So, did raisim provided an API already? I have searched docs and APIs, but found no one, thank you.

**Comment by jhwangbo** [comment]
The finite difference is the best you can do to get acceleration.

BTW, did you change the generalized velocity convention? The angular velocity of the base is expressed in the world frame in RaiSim. This is not so common convetion

**Comment by Abedcoder** [comment]
thank you sir, I've tried anyother way to aovid using acceleration. And your notification about angular velocity is very helpful!
