### ISSUE TITLE
class raisim::ArticulatedSystem’ has no member named ‘getLinkCOM’

### ISSUE THREAD

**Issue by lagnx** [raisimTech/raisimLib#251]
The 'getLinkCOM' function seems to be cancelled after the update, where can I find the description of the 'getLinkCOM' function, and what function should I use instead?

**Comment by jhwangbo** [comment]
The word "link" was incorrect and thus removed. You should use ``getBodyCOM``. Links are the links that you define in the URDF. Bodies are set of links that contain movable bodies. In other words, links with fixed joints are combined to its parent and form a body
