### ISSUE TITLE
No window

### ISSUE THREAD

**Issue by amoran-symbio** [raisimTech/raisimLib#252]
When I run python examples no window appears. "ps" shows that there is a process running, but nothing is visible.

Advice?

Ubuntu 20.04
Lenovo ThinkPad w/ Nvidia GPU

**Comment by jhwangbo** [comment]
run raisimUnity and check "autoConnect"

**Comment by jhwangbo** [comment]
The visualization runs in a separate process. Please check https://raisim.com/sections/Introduction.html#visualizer

**Comment by dvogureckiy99** [comment]
I have the same issue, but I get:
![Screenshot from 2023-02-18 12-48-34](https://user-images.githubusercontent.com/65085868/219853813-8c28f58f-b283-4d87-9237-30226e90defc.png)

**Comment by dvogureckiy99** [comment]
You should write in black and white that for visualization you need run in parallel either raisimUnity or raisimUnreal and only after it run example.
