### ISSUE TITLE
Simulation results according to PD gain 

### ISSUE THREAD

**Issue by Hyeonjin-k** [raisimTech/raisimLib#261]
Hello

This time, I have a question while conducting reinforcement learning through raisim.

We are currently controlling the position through the coordinates of a specific object in the URDF.

In the meantime, it was confirmed that changing the PD gain value greatly affects the simulation. The question is below.

1. If the PD gain value is increased, the simulation speed for reinforcement learning is significantly lowered. Can you understand the reason?

2. If you increase the PD gain value, I want to know why the Nan value is returned from getPosition(), which gets the coordinates of a specific object.

**Comment by jhwangbo** [comment]
High PD gains can cause instability. This is true on the real robot as well. It can also increase the training time if it creates more collisions. You can try to implement your own PD controller and check the stability. If yours is stable, then that must be a RaiSim bug.
