### ISSUE TITLE
Insert new model problem

### ISSUE THREAD

**Issue by Hyeonjin-k** [raisimTech/raisimLib#267]
Hello, this time, I tried to run a simulation by inserting a new model. However, I have a problem with writing.

1. The model import is successful and the joint information is ok. However, in runney.py, it does not progress beyond the env=VecEnv part, so it does not go to the learning stage.

2. As a result of checking the obj file, there are some that exceed 40Mb. Maybe there is a problem with the capacity?

**Comment by jhwangbo** [comment]
yes, reduce the mesh size to below ~200kB
