### ISSUE TITLE
example of contact force in raisimpy

### ISSUE THREAD

**Issue by wooseokH** [raisimTech/raisimLib#271]
hello 
I want to use contact simulation with manipulator in raisimpy. below pages, there is no raisimpy example.
https://raisim.com/sections/Contact.html#contacts

could you give me a short example about contact class in raisimpy?

**Comment by jhwangbo** [comment]
They have the same method names. Here is my example in raisimPy. You can append those lines to ``robots.py`` example

```
    contacts = anymal.getContacts()
    if len(contacts) > 0:
        print(contacts[0].getImpulse())
```

**Comment by Durrells** [comment]
hi jhwangbo! I have added those lines to robots.py example, why the length of contacts is zero?
