### ISSUE TITLE
Problem with changing the friction coefficient between robot's feet and ground

### ISSUE THREAD

**Issue by edward9503** [raisimTech/raisimLib#275]
Dear @jhwangbo,

I wanna change the friction coefficient between the robot's feet with the gound in RaisimOgre to a really small value. Previously I have discussed with @jhwangbo at the issue section of RaisimOgre repo, as shown in [here](https://github.com/raisimTech/raisimOgre/issues/26). 

Let me have a short recap: I am using the ANYmal C in raisimOgre. I've followed the tutorials [here](https://raisim.com/sections/MaterialSystem.html) to change the friction coefficient between feet and ground. But this tutorial used the ANYmal B as example that has a different foot link structure in URDF, which turned out that the tutorial didn't work for ANYmal C. 

So I have following questions:

1. Since "LH_FOOT/0" means the first collision body of the link “LH_FOOT”, it is indeed the "LH_shank_fixed" in ANYmal C if I understand correctly from urdf. Right?
2. Then for changing the friction coefficient in ANYmal C, should I use "LH_FOOT" instead of "LH_FOOT/0" (i.e., set "anymal.back()->getCollisionBody("LH_FOOT").setMaterial("LH_FOOT");")?
3. If not, how should I do to select the foot?
4. Moreover, why does the LH_FOOT link of ANYmal C have two collision properties (i.e., one for the adapter and another for the foot), where these properties are separated into link "LH_FOOT" and "LH_ADAPTER" respectively in ANYmal B?
5. In ANYmal B, "LH_FOOT/0" should be the link “ LH_ADAPTER” right? But I checked the collision body of this link, it is also the adapter, which causes the internal collision. So I was confused why "LH_FOOT/0" can be used in ANYmal B and cannot be used in C?

Many thanks in advance.

Best
Shengzhi

**Comment by jhwangbo** [comment]
I guess you want to change the material property of the sphere collision body on ANYmalC, right? That must be this line

https://github.com/raisimTech/raisimLib/blob/803841034d81c11c365a3afd137e886b7b68e181/rsc/anymal_c/urdf/anymal.urdf#L1323

That is the second collision body of "LH_FOOT". So you have to refer to it as "LH_FOOT/1".
