### ISSUE TITLE
cannot install raisim

### ISSUE THREAD

**Issue by IverYangg** [raisimTech/raisimLib#276]
cmake .. -DCMAKE_INSTALL_PREFIX=$LOCAL_INSTALL -DRAISIM_EXAMPLE=ON -DRAISIM_PY=ON -DPYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)")
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:53 (install):
  install DIRECTORY given no DESTINATION!

CMake Error at CMakeLists.txt:60 (install):
  install DIRECTORY given no DESTINATION!

-- Found raisim: /home/iver/raisim_workspace/raisimLib/raisim/linux/include  
-- raisim:
--   Version: 1.1.0
--   Includes: /home/iver/raisim_workspace/raisimLib/raisim/linux/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;raisim::raisim
-- pybind11 v2.9.0 
-- Found PythonInterp: /home/iver/anaconda3/bin/python3 (found version "3.9.7") 
-- Found PythonLibs: /home/iver/anaconda3/lib/libpython3.9.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- raisim:
--   Version: 1.1.0
--   Includes: /home/iver/raisim_workspace/raisimLib/raisim/linux/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;raisim::raisim
-- Configuring incomplete, errors occurred!
See also "/home/iver/raisim_workspace/raisimLib/build/CMakeFiles/CMakeOutput.log".

**Comment by jhwangbo** [comment]
Did you set the environment variable $LOCAL_INSTALL? You should set it to the directory where you want to install raisim
