### ISSUE TITLE
Low Unity visualization quality on Ubuntu

### ISSUE THREAD

**Issue by xeonz1** [raisimTech/raisimLib#278]
Hi,
I am running the example `anymals` and the rendered Unity images are of low quality as you can see from the blurry ANYmal text and reflection on the floor. When rotating the view, one can feel low fps and lagging.
![Screenshot from 2022-03-03 13-27-22](https://user-images.githubusercontent.com/56295370/156502060-60a8a551-6643-4c54-810a-0dcecc984f6b.png)

**Comment by jhwangbo** [comment]
What is your GPU?

You cannot expect video game quality on such a program. Video games are optimized for specific scenes but raisimUnity doesn't know what to visualize ahead of time.

The rendering is not far off from what I expected. The lagging depends on your GPU performance.

**Comment by xeonz1** [comment]
> What is your GPU?
> 
> You cannot expect video game quality on such a program. Video games are optimized for specific scenes but raisimUnity doesn't know what to visualize ahead of time.
> 
> The rendering is not far off from what I expected. The lagging depends on your GPU performance.

You are right. I think it may be something about GPU drivers and Unity.
