### ISSUE TITLE
new master branch fails in Ubuntu

### ISSUE THREAD

**Issue by fanshi14** [raisimTech/raisimLib#28]
Hi Jemin,

I update to the latest master branch, all compiles well. 
But when training with ```runner.py```, it fails with the output:

> Traceback (most recent call last):
  File "raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 2, in \<module>
    from raisimGymTorch.env.RaisimGymVecEnv import RaisimGymVecEnv as VecEnv
ModuleNotFoundError: No module named 'raisimGymTorch.env'

My system is Ubuntu 18.04 and it works well with Dec 9, 2020's version. 
I failed to find the reason. Wonder if you have the similar case?

THX.
Fan

**Comment by jhwangbo** [comment]
did you call ``python setup develop``? this error is basically saying that it doesn't recognize ``raisimGymTorch.env`` directory, which means it is not installed.

**Comment by fanshi14** [comment]
Yes, I called ```python raisimGymTorch/setup.py develop``` and it compiles well.
But exactly, it is not being installed, but I failed to find what is wrong.

**Comment by jhwangbo** [comment]
do you use virtualenv or conda? can you check  /home/xxx/raisim_ws/raisimLibCourt/gym_env/lib/python3.8/site-packages/raisim-gym-torch.egg-link?

**Comment by fanshi14** [comment]
THX Jemin.

I used virtualenv with Python3.8, and I tried conda with Python3.9 as well, but same results.

 /home/xxx/raisim_ws/raisimLibCourt/gym_env/lib/python3.8/site-packages/raisim-gym-torch.egg-link:

> /home/xxx/raisim_ws/raisimLibCourt
.

Seems my system has problems somehow, I rebuild Dec 9, 2020's version and failed as well.

**Comment by jhwangbo** [comment]
``/home/xxx/raisim_ws/raisimLibCourt`` does this directory have ``env`` folder? The way it finds the library is pretty simple. If you get this error ``No module named 'raisimGymTorch.env``, this means that it cannot find the ``env`` directory inside ``/home/xxx/raisim_ws/raisimLibCourt``.

**Comment by fanshi14** [comment]
Thank you Jemin!
I found my stupid problem that I should be inside ```raisimGymTorch``` folder in the first time to run ```python3 setup.py develop```, instead of in ```raisimLib``` folder in the first time to run ```python3 raisimGymTorch/setup.py develop```.
