### ISSUE TITLE
Fedora: symbolic links for libdl.so and libminizip.so.1

### ISSUE THREAD

**Issue by braunjon** [raisimTech/raisimLib#282]
I solved the problems below (not sure if I solved them the right way) but I thought I still post it as a reference. Maybe you could consider this to support this in the future.

On Fedora I had to create two symbolic links that the visualizer works.
`sudo ln -s /usr/lib64/libdl.so.2 /usr/lib64/libdl.so`
`sudo ln -s /usr/lib64/libminizip.so.3.0 /usr/lib64/libminizip.so.1`

If I ran the example ./anymals in the terminal and then clicked on the connect button in the RaySimUnity and also in the RaySimUnityOpenGL visualizer I got the errors below.

Without symlink libdl.so:
```
error logs 
System.Exception: RsUnityRemote: InitializeObjects
Cannot create mesh: libdl.so
libdl.so
  at (wrapper managed-to-native) Assimp.Unmanaged.UnmanagedLibrary+UnmanagedLinuxLibraryImplementation.dlopen(string,int)
  at Assimp.Unmanaged.UnmanagedLibrary+UnmanagedLinuxLibraryImplementation.NativeLoadLibrary (System.String path) [0x00000] in <d40f2b0ad6814d4c8094142d8473733f>:0 
...
```

Without simlink libminizip.so.1:
```
System.Exception: RsUnityRemote: InitializeObjects
Cannot create mesh: Error loading unmanaged library from path: /home/braunjon/raisim_workspace/raisimlib/raisimUnity/linux/raisimUnity_Data/Plugins/libassimp.so

libminizip.so.1: cannot open shared object file: No such file or directory
Error loading unmanaged library from path: /home/braunjon/raisim_workspace/raisimlib/raisimUnity/linux/raisimUnity_Data/Plugins/libassimp.so

libminizip.so.1: cannot open shared object file: No such file or directory
  at Assimp.Unmanaged.UnmanagedLibrary+UnmanagedLinuxLibraryImplementation.NativeLoadLibrary (System.String path) [0x00040] in <d40f2b0ad6814d4c8094142d8473733f>:0 
...
```

**Comment by jhwangbo** [comment]
Thank you for sharing.

**Comment by thomasbbrunner** [comment]
Can confirm that I had a similar problem when running raisim on Ubuntu 22.04.

However, in my case only the libdl.so library required a symbolic link. In my system, I only had the `libdl.so.2` library.

Fixed the problem with:
`sudo ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/x86_64-linux-gnu/libdl.so`
