### ISSUE TITLE
Compile failed on Linux ARM64

### ISSUE THREAD

**Issue by hsqthu2012** [raisimTech/raisimLib#284]
Hi, I'm trying to install raisimLib on my Ubuntu 20.04 ARM64. But I encounter an error `ocs2_ws/src/raisimLib/raisim/linux/include/raisim/helper.hpp:16:10: fatal error: mm_malloc.h: No such file or directory`.

By replacing the `mm_malloc.h` and the function `_mm_malloc()` I bypass this error but another error occurs `/usr/bin/ld: ../../raisim/linux/lib/libraisim.so: error adding symbols: file in wrong format collect2: error: ld returned 1 exit status`.

I wonder if this problem is due to the ARM64 architecture, and if raisim is supported on Linux ARM64.

Thanks!

**Comment by jhwangbo** [comment]
raisim is not supported on arm64+linux. There is no way to make it work because the arm cpus dont have avx2 instructions. What is your device?

**Comment by hsqthu2012** [comment]
Got it. Actually, I'm doing this in a virtual machine on the M1 MacBook. Should I try install RaiSim directly on the Mac environment?

**Comment by jhwangbo** [comment]
Thats the only option for now.

**Comment by hsqthu2012** [comment]
Thanks! I'll try that.
