### ISSUE TITLE
In contact situation, "world.integrate()" command time

### ISSUE THREAD

**Issue by wooseokH** [raisimTech/raisimLib#286]
hello

I have a simulation about manipulation control in contact situation. in a contact situation, "world.integarte()" command has a long calculation time(2ms~3ms) compared to the control sampling time that I want to set 1ms(world.setTimeStep(1ms)).
I'm confused about the order. Should I operate "world.integrate()" in sampling time, or after the sampling time?

For example,
for 
  calculation time(control algoritm)
  time.sleep(Ts-calculation_time) 
  world.integrate()

end

Does this make sense?

**Comment by jhwangbo** [comment]
Why don't you remove sleep if simulation takes a very long time?

**Comment by wooseokH** [comment]
I may not be asking and understanding exactly how the simulation works.

I thought that even in the simulation, as in the actual experiment, the control sampling time should be set by 1 ms.
But thinking about it, since the simulation consists of operations, it doesn't make sense to be applied like the actual experiment.
First of all, the question is, during "world.integrate()" or "time.sleep(), the robot does not move according to the command?
If so, if I set "world.setTimeStep" as 1ms, can I say that the control loop is running at 1ms, even if is slow to see it in unity?

**Comment by jhwangbo** [comment]
The time step is for integration. There is no wait function in integration. You can run your simulation as fast as you want. You should add time.sleep() to slow down the simulation as you want
