### ISSUE TITLE
Solution to objects penetration

### ISSUE THREAD

**Issue by BoySun045** [raisimTech/raisimLib#287]
Hi Raisim Team,
I'm working on my master's thesis using Raisim. And in my current implementation, I need to update the object's positions from time to time. And I just met this penetration issue, where the updated object happens to have penetration with another object in the scene. And I notice that when this happens, the simulation will not automatically solve for it to separate them. Could you please provide any potential solutions to this? Like, how would you suggest solving this problem, or if there is a function I can call to check if two objects have penetration(will be extremely useful)? Thank you so much in advance!
![Screenshot from 2022-03-23 14-41-09](https://user-images.githubusercontent.com/47916663/159713921-3e38f1bd-6ce6-4a21-a0a0-204f18a8ec3c.png)

**Comment by jhwangbo** [comment]
There is no algorithm that automatically splits objects apart. You can integrate it once and get the penetration depths and move them accordingly yourself. But we do not override your setPosition command even if there is an overlap.

**Comment by BoySun045** [comment]
> 

Thank you! Could you please illustrate how to do such integration?
