### ISSUE TITLE
RaisimUnity flash back

### ISSUE THREAD

**Issue by FenglongSong** [raisimTech/raisimLib#290]
Hello,
I'm installing RaisimLib on Ubuntu 20.04.03 running inside VMware Fusion 12 on a Macbook Pro with Intel Core. The RaisimUnity crashes very soon after a black window appears (by opening with double click). If I try to open it from terminal, it gives following information:
`XXX@ubuntu:~/Desktop/raisim_ws/src/raisimLib/raisimUnity/linux$ ./raisimUnity.x86_64`
`Set current directory to /home/XXX/Desktop/raisim_ws/src/raisimLib/raisimUnity/linux`
`Found path: /home/XXX/Desktop/raisim_ws/src/raisimLib/raisimUnity/linux/raisimUnity.x86_64`
`Segmentation fault (core dumped)`
Although raisimUnityOpengl is working, I still want to get a solution to this issue. Could you please give me some advice? Thank you!

**Comment by jhwangbo** [comment]
Did you install Vulkan? You have to install it manually. Even so, Ubuntu does not support Vulkan well and I often see compromising graphics in ubuntu with intel integrated graphics.

**Comment by FenglongSong** [comment]
Yes, I installed Vulkan. I guess the problem would be the Intel integrated graphics. I'll just ignore this issue for now. Thanks for your reply!
