### ISSUE TITLE
How can I get the friction between ground and feet?

### ISSUE THREAD

**Issue by Durrells** [raisimTech/raisimLib#294]
hi, is there any advice to get the friction between ground and feet?

**Comment by jhwangbo** [comment]
You should set the friction. Check this link https://raisim.com/sections/MaterialSystem.html

**Comment by Durrells** [comment]
Thanks for your reply! After setting the friction coefficient，do I need to calculate the friction by myself or there is a function to get the friction directly?

**Comment by jhwangbo** [comment]
https://raisim.com/sections/Contact.html#contacts
