### ISSUE TITLE
How calculate body orientatin?

### ISSUE THREAD

**Issue by dilayysldg** [raisimTech/raisimLib#295]
hi, Im trying to calculate body orientatin but getting an error like in the figure. How can I use this command? RFOri is matrix 3x3. 
![aa](https://user-images.githubusercontent.com/100845442/163399279-c8995430-e993-4938-8585-ec7f6e387636.JPG)

**Comment by jhwangbo** [comment]
You can check the API here: https://raisim.com/sections/ArticulatedSystem.html#api
RFOri should be raisim::Mat<3,3>
