### ISSUE TITLE
Adding box to heightmap

### ISSUE THREAD

**Issue by chongt123** [raisimTech/raisimLib#297]
Hi,

I want to a some boxes and cylinders to my height map to form obstacle. At the same time, I need to get the terrain information.  Is there any way I can do that? 

Thanks.

**Comment by jhwangbo** [comment]
Add a cylinder or a box and set it to a static type

**Comment by chongt123** [comment]
Then how can I get the height of the surface of the box according to the
world frame?

Jemin Hwangbo ***@***.***>于2022年4月21日 周四下午12:13写道：

**Comment by chongt123** [comment]
Using ray test?

Chong Tian ***@***.***>于2022年4月21日 周四下午12:28写道：

**Comment by jhwangbo** [comment]
Yes, the ray test. GetHeight is only for the heightmap

**Comment by chongt123** [comment]
Okay. Thanks so much.

Jemin Hwangbo ***@***.***>于2022年4月21日 周四下午12:39写道：

**Comment by chongt123** [comment]
> Yes, the ray test. GetHeight is only for the heightmap

Hi,

When I use ray test, after I set the collision mask to " RAISIM_STATIC_COLLISION_GROUP",  it still collide with the robot. How  can I solve this problem?

**Comment by chongt123** [comment]
`auto &col = world_->rayTest(lidarPos, rayDirection, 1, true, RAISIM_STATIC_COLLISION_GROUP);`

My code is here.
