### ISSUE TITLE
12th gen intel processor low utilization during RaisimGymTorch

### ISSUE THREAD

**Issue by Berk-Tosun** [raisimTech/raisimLib#303]
Hello,

I have run the RaisimGymTorch example as explained. I noticed that I am getting low cpu utilization: mpstat reports ~33 %, which is verified with htop. Torch uses a dedicated gpu. runner.py reports a real time factor around 500.

My system:

CPU: Intel i7 12700k
OS: Ubuntu 20.04.4 (cannot update because I need ROS support)
Linux Kernel: 5.17.8-051708-generic (ahead of ubuntu 20.04.4 which uses 5.13.x, >5.16 is required for proper 12th gen support + wifi, etc.)

Is there anything that I can do to improve utilization?

Thanks!

**Comment by Berk-Tosun** [comment]
Adjusting the num_threads in the cfg.yaml file fixes it. 12700k has 20 threads, 2 should be reserved for torch-gpu, so I have set it to 18. Utilization gets to ~88%, and real time factor is about 2000 which is great!

**Comment by jhwangbo** [comment]
Yes, you have to tune this for every CPU. There is no method to get the optimal number of CPUs in OpemMp
