### ISSUE TITLE
Changing "posOffset" of collision bodies

### ISSUE THREAD

**Issue by luigicampanaro** [raisimTech/raisimLib#304]
Hello! :)

I was trying to modify the `posOffset` of collision bodies using [this function](https://raisim.com/sections/ArticulatedSystem.html?highlight=urdf#_CPPv4N6raisim17ArticulatedSystem16getCollisionBodyERKNSt6stringE) and checking from the collisions displayed in Unity there was no difference.

Is this the correct way of doing it? It's worth mentioning that I can print out the current offset and it's correct.
`robot->getCollisionBody("RL_foot/0").posOffset.e() << 0.1, 0.1, 0.1;`

I'm not sure it's a visualisation issue or if I'm doing something wrong, thanks in advance anyway!

**Comment by jhwangbo** [comment]
yes, it changes the collision position but doesn't update the visualization. I'll get it fixed soon.

**Comment by jhwangbo** [comment]
I pushed the fix. Previously, there were two containers: one for actual collision computation (which you could get from `getCollisionbodies`) and one for visualization (which you could get from `getVisColOb`). Now I made it such that the actual collision bodies are used for visualization as well.

But you still have to change the visualization objects that you can get from `getVisOb`. Their parameters are different from the collision parameters so you have to change them manually.

**Comment by luigicampanaro** [comment]
Thank you very much, I'll give it a try!
