### ISSUE TITLE
Orientation missmatch between raisim visuals and objects

### ISSUE THREAD

**Issue by braunjon** [raisimTech/raisimLib#305]
Hi,
The orientation of the `raisim::Visuals` seems to be different from the `raisim::SingleBodyObject` when visualizing with unity.

Min. code example (appended to the constructor in raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/Environment.hpp):
```
/// test vis objects
raisim::Vec<4> quat = {0.6, 0.2, -0.6, 0.1};
quat = quat/quat.norm();

raisim::Box *body = world_->addBox(0.02, 0.05, 0.09, 1);
body->setPosition(0, 0, 1);
body->setOrientation(quat);

if (visualizable_) {
    raisim::Visuals *vis_object = server_->addVisualBox("vis_obj", 0.02, 0.05, 0.09);
    vis_object->setPosition(0, 0, 1);
    vis_object->setOrientation(quat.e());
}
```

Unity screenshot:
![object_vs_visual_object](https://user-images.githubusercontent.com/25931090/171371445-99883d89-bb41-4a2e-ad25-9dccb4370b15.png)

**Comment by jhwangbo** [comment]
I was already going to fix this problem. Actually, the issue was the scale conversion from raisim's XYZ coordinate to Unity's XZY coordinate system. I made a fix and will push the Linux version tonight

**Comment by jhwangbo** [comment]
i pushed the fix. Let me know if you still have the issue

**Comment by braunjon** [comment]
Thank you. It is working now for boxes.

1. However when I try to visualise meshes they do not align. 
    I updated the code to test also with cylinder, capsules and meshes. (I can't figure out how to set the radius and length of the capsule that the visual-capsule and raisim-capsule have the same size) 

```
/// test vis objects
std::string obj_file = "teapot.obj";

raisim::Vec<4> quat = {0.6, 0.2, -0.6, 0.1};
quat = quat / quat.norm();
raisim::Mat<3, 3> inertia;
inertia.setIdentity();
const raisim::Vec<3> com = {0, 0, 0};

raisim::SingleBodyObject *body = world_->addBox(0.02, 0.05, 0.09, 1);
body->setPosition(0, 0, 2);
body->setOrientation(quat);

body = world_->addCylinder(0.02, 0.05, 1);
body->setPosition(0.2, 0, 2);
body->setOrientation(quat);

body = world_->addCapsule(0.02, 0.05, 1);
body->setPosition(0.4, 0, 2);
body->setOrientation(quat);

body = world_->addMesh(obj_file, 1, inertia, com);
body->setPosition(0.6, 0, 2);
body->setOrientation(quat);

if (visualizable_) {
    raisim::Visuals *vis_object = server_->addVisualBox("_Box", 0.02, 0.05, 0.09);
    vis_object->setPosition(0, 0, 2);
    vis_object->setOrientation(quat.e());

    vis_object = server_->addVisualCylinder("_Cylinder", 2*0.02, 0.05/2);
    vis_object->setPosition(0.2, 0, 2);
    vis_object->setOrientation(quat.e());

    vis_object = server_->addVisualCapsule("_Capsule", 0.02*7.0,0.05*5);
    vis_object->setPosition(0.4, 0, 2);
    vis_object->setOrientation(quat.e());

    vis_object = server_->addVisualMesh("_Mesh", obj_file);
    vis_object->setPosition(0.6, 0, 2);
    vis_object->setOrientation(quat.e());
}
```

![image](https://user-images.githubusercontent.com/25931090/171863707-fae1ec90-4f50-4542-844e-77085599cbda.png)

2. I think I also discovered a different problem.
    If there is a rasim cylinder object and I name a visual object "Cylinder" wired things happen (raisim-cylinder-object changes in to a different shape (cylinder+box), visual object (box) is at origin).

Code:
```
/// test vis objects
raisim::Vec<4> quat = {0.6, 0.2, -0.6, 0.1};
quat = quat / quat.norm();

raisim::SingleBodyObject *body = world_->addCylinder(0.02, 0.05, 1);
body->setPosition(0.2, 0, 1);
body->setOrientation(quat);

if (visualizable_) {
    raisim::Visuals *vis_object = server_->addVisualBox("Cylinder", 0.02, 0.05, 0.09);
    vis_object->setPosition(0, 0, 1);
    vis_object->setOrientation(quat.e());
}
```
![image](https://user-images.githubusercontent.com/25931090/171867481-8f1e8829-b4d4-4632-86d3-d1beb2af13e1.png)

**Comment by jhwangbo** [comment]
can you pull and test the fix?

**Comment by braunjon** [comment]
Great. It is working for me now. Thanks.
