### ISSUE TITLE
Change the heightmap during training

### ISSUE THREAD

**Issue by Durrells** [raisimTech/raisimLib#306]
Hi there,

I want to change the heightmap with different surface properties during training. I have tried to use removeObject() to remove the old heightmap and add the new heightmap by using addHeightMap() again, but it doesn't work. Is there any suggestion to do that? Thank you very much!

**Comment by jhwangbo** [comment]
What do you mean by that it doesn't work? I already do that for many of my training setups.

**Comment by Durrells** [comment]
Thanks for your reply. I think I have solved the problem.
