### ISSUE TITLE
Relating joint actuation torque to generalized torque

### ISSUE THREAD

**Issue by RobertoRoos** [raisimTech/raisimLib#31]
Like a typical robot, mine has a floating base and is therefore underactuated. Moreover, a joint torque does not directly map to a generalized force, since a joint torque will pull on one joint coordinates but push against another.

If we imagine a box with a single rotating stick, we would have the following:

![equation](https://latex.codecogs.com/gif.latex?%5Cmathrm%7Bn%7D%28q%29%20%3D%208%2C%20%5C%20%5Cmathrm%7Bn%7D%28v%29%20%3D%207%20%5C%5C%20%5Cmathrm%7BM%7D%28q%29%5Cdot%7Bv%7D%20&plus;%20h%28q%2C%20v%29%20%3D%20%5Ctau%20%5C%5C%20%5Cmathrm%7Bn%7D%28%5Ctau%29%20%3D%207%2C%20%5C%20%5Cmathrm%7Bn%7D%28%5Ctau_a%29%20%3D%201%20%5C%5C%20%5Ctau%20%3D%20J_a%20%5Ctau_a%20%3D%20%5Cbegin%7Bbmatrix%7D%200%20%26%200%20%26%200%20%26%200%20%26%200%20%26%20-1%20%26%201%20%5Cend%7Bbmatrix%7D%20%5Ctau_a)

Some actuator jacobian relates the actuator torques to generalized torques.

Is it possible to distinguish between actuated and passive degrees-of-freedom in a URDF robot?  
And would it be possible to find such an actuator jacobian? Or write actual actuation forces directly?
I guess this question is about URDF as much as RaiSim itself.

Thank you in advance!

**Comment by RobertoRoos** [comment]
I posted a little too quickly. One way of recognizing the floating base joints is through `getActuatorLower/UpperLimits()`, the limits will be <-1e150, 1e150>.
(And they are just the first six values of course.)

This still leaves the actuator force relation though.

**Comment by jhwangbo** [comment]
You can check out this method https://raisim.com/sections/ArticulatedSystem.html#_CPPv4N6raisim17ArticulatedSystem12getJointTypeE6size_t

You can check if the first joint type is floating or not. A floating joint is possible only for the first joint.

Your jacobian is not correct. It should be [0 0 0 0 0 0 1]. The generalized force already assumes that there is a reaction force/torque. Generalized force should satisfy tau*gen_vel=power. If we stick to the RaiSim gen vel definition, then the definition of the gen force naturally arises.

**Comment by RobertoRoos** [comment]
Alright. So we could get a selection matrix like:

```
/**
 * Get actuated joint selection matrix
 *
 * Usage: tau = S * tau_a
 *
 * @return S
 */
Eigen::MatrixXd getSelectionMatrix(const raisim::ArticulatedSystem* system) {

    if (system->getNumberOfJoints() == 0) {
        return Eigen::MatrixXd(0, 0); // Robot without any joints at all
    }

    raisim::Joint::Type first_joint_type = system->getJointType(0);

    const int n_dof = system->getDOF();

    if (first_joint_type != raisim::Joint::Type::FLOATING) {

        // All are probably actuated:
        return Eigen::MatrixXd::Identity(n_dof, n_dof);
    }

    // The first 6 DOFs are not actuated:
    Eigen::MatrixXd S(n_dof, n_dof - 6);
    S << Eigen::MatrixXd::Zero(6, n_dof - 6), Eigen::MatrixXd::Identity(n_dof - 6, n_dof - 6);
    return S;
}

//...

    // Use like:

    Eigen::VectorXd tau_a(1);

    tau_a[0] = 0.05; // Wheel torque

    Eigen::VectorXd tau = getSelectionMatrix(robot) * tau_a;

    robot->setGeneralizedForce(tau);
```

And this checks out in a simple simulation (which also confirms the right reaction force):

https://user-images.githubusercontent.com/12717020/102618039-5ed72a00-413a-11eb-8b08-098d5e4452c3.mp4
