### ISSUE TITLE
Video recording function in linux

### ISSUE THREAD

**Issue by Leo05438** [raisimTech/raisimLib#315]
I try to run visualObjects.py in examples folder, but it seems there isn't any mp4 file being recorded. Do I miss some steps?

**Comment by Leo05438** [comment]
Moreover, I want to collect RGBD visual data and the state of each object at the same time. Is there a way that I can store them both in a certain timestamp?

**Comment by Leo05438** [comment]
Moreover, we want to collect RGBD visual data and the state of each object at the same time. Is there a way that we can store them both in a certain timestamp?

**Comment by jhwangbo** [comment]
The video recording seems to work fine. Did you install ffmpeg?

**Comment by jhwangbo** [comment]
I am working on RGBD sensors for unreal. Now it is hard for me to tell how long it takes
