### ISSUE TITLE
Raisim Unity Wrong Contact Direction

### ISSUE THREAD

**Issue by burakozkaynak** [raisimTech/raisimLib#316]
Hello,
On the Unity visualization, the direction of the contact forces is reversed. It was not like that for the previous version of Raisim. Do you have a  suggestion for this?

![Screenshot-2022-06-17-12-33-35](https://user-images.githubusercontent.com/77923283/174272172-ff9b4bc5-6dcf-43dd-9c2a-b2847690845d.png)

**Comment by jhwangbo** [comment]
This is technically fine but confusing for sure. I'll fix this and update it soon

**Comment by jhwangbo** [comment]
I merged the fix. Let me know if it doesn't work for you

**Comment by burakozkaynak** [comment]
It works fine now. Thank You.

**Comment by burakozkaynak** [comment]
Hello again,
We have encountered same problem in RaisimUnity-OpenGL.

**Comment by burakozkaynak** [comment]
Also from the computation side measured contact force is reversed.
