### ISSUE TITLE
Raisim  Reversed Contact Direction

### ISSUE THREAD

**Issue by burakozkaynak** [raisimTech/raisimLib#319]
Hello,

I said before that there is a problem in the visualizer (Unity), but the situation is the same in the simulation part. In addition, Raisim Unity Windows, and Raisim Unity OpenGL Linux  have similar problem for visualizer side.

**Comment by jhwangbo** [comment]
I'll address this issue in the following update. At the moment it does not seem to be an important issue. But thanks for letting me know

**Comment by burakozkaynak** [comment]
You're welcome.

**Comment by jhwangbo** [comment]
The fix has been pushed
