### ISSUE TITLE
About invalid position detected

### ISSUE THREAD

**Issue by fanshi14** [raisimTech/raisimLib#32]
Hey,

I kindly wonder in which case it will trigger:

> An invalid position detected. This is most likely due to an invalid control command.
terminate called without an active exception
Aborted (core dumped)

It will terminate the training process, which really cause destruction.

Thx!
Fan

**Comment by jhwangbo** [comment]
This means that the simulation is not stable. It can be due to 1) unstable controller 2) invalid collision geometry 3) invalid initial state 4) contact solver instability 5) memory error. I cannot tell more from what you provided
