### ISSUE TITLE
Include math.h in raisim/raisim_message.hpp as it uses isnan

### ISSUE THREAD

**Issue by JewelryForge** [raisimTech/raisimLib#325]
In linux version, raisim_message.hpp does not include math.h but is uses isnan.

https://github.com/raisimTech/raisimLib/blob/82d5efa3d823c86d39ca9f5038467e5f9615c8ac/raisim/linux/include/raisim/raisim_message.hpp#L26

Or use `std::isnan` and include `<cmath>`.

thx!

**Comment by JewelryForge** [comment]
It doesn't influence the compilation of raisim itself but custom usages.
Also, raisimGymTorch/raisimGymTorch/env/Reward.hpp uses `RSFATAL_IF` etc. but doesn't include "raisim/raisim_message.hpp".
https://github.com/raisimTech/raisimLib/blob/82d5efa3d823c86d39ca9f5038467e5f9615c8ac/raisimGymTorch/raisimGymTorch/env/Reward.hpp#L45

**Comment by jhwangbo** [comment]
I pushed a fix for win and linux version. mac version will follow soon
