### ISSUE TITLE
Get the jacobian matrix of the contact point?

### ISSUE THREAD

**Issue by edward9503** [raisimTech/raisimLib#326]
Hi @jhwangbo ,

Imagine I have a quadruped standing on the ground. Each foot will contact the ground. Is that possible to get the jacobian matrix of these contact points in RaiSim?

**Comment by jhwangbo** [comment]
You can get the position of the contact points and query the Jacobian. There are so many different Jacobians depending on the convention. Check if you can find the one you need: https://raisim.com/sections/ArticulatedSystem.html#api

**Comment by edward9503** [comment]
Hi @jhwangbo ,

Thanks for the reply. The thing is, I have checked the website, all the jacobian-calling functions need either a bodyIdx or frameIdx as input to obtain the jacobian matrix. Since these indices are based on the "name" from urdf file, the contact point doesn't belong to the kinematic tree of robot in URDF, and hence cannot access the bodyIdx or frameIdx from URDF and cannot get the jacobian at the exact contact point. Is there any method to do this in raisim?

**Comment by jhwangbo** [comment]
https://github.com/raisimTech/raisimLib/blob/82d5efa3d823c86d39ca9f5038467e5f9615c8ac/raisim/linux/include/raisim/contact/Contact.hpp#L128

The contact returns the body index.

**Comment by edward9503** [comment]
@jhwangbo 

Thanks. But this only returns localBodyIndex. Does it matter if I use this index directly as input for the jacobian-calling function?

Moreover, what is the difference between the global and local indexes in raisim?

**Comment by jhwangbo** [comment]
Yes to the first question

World (or global) index is the order of the objects in the world
local (or body) index is the order of the bodies within an object

**Comment by edward9503** [comment]
@jhwangbo 

Thanks. So for instance, for a floating base robot, I use "getSparseJacobian(contact_point_body_Idx, contact_point_position_In_world, jaco)" to get a jaco. Since the generalized velocity convention in RaiSim defines that the first 6 elements are linear and angular velocity in the world frame, I can also get a generalized velocity vector u. Then v = jaco * u is expressed in the world frame, is that correct?
