### ISSUE TITLE
Order of Quaternion Elements in getGeneralizedCoordinate()

### ISSUE THREAD

**Issue by christophecricket** [raisimTech/raisimLib#327]
Hi!
What order are the elements of quaternions stored in if I call `getGeneralizedCoordinate()`? Is it [w x y z] or is it [x y z w]. Based on some of the other issue replies, I think it's [w x y z] but I would like a clarification because I'm trying to debug some issues in my code.

**Comment by jhwangbo** [comment]
It is [w x y z]

https://raisim.com/sections/ConventionsAndNotations.html
