### ISSUE TITLE
How to get acceleration of a body

### ISSUE THREAD

**Issue by chongt123** [raisimTech/raisimLib#328]
Hi professor,

I am wondering how to get the acc of a body? Could you please help me with this problem?

thanks.

**Comment by jhwangbo** [comment]
The only way to get the acceleration is to use time differentiation. Most of the simulations that you know are velocity-based, which means that they compute velocity without computing the acceleration.

**Comment by ClaudioChiariello** [comment]
Hello, I was trying to compute acceleration with time differentiation, But I obtained very high values, and I'm not sure if I did well:: ```

**Comment by jhwangbo** [comment]
The code looks ok to me. Acceleration is often gigantic especially when there are rigid contacts
