### ISSUE TITLE
Depth sensor available in RaisimOgre?

### ISSUE THREAD

**Issue by edward9503** [raisimTech/raisimLib#329]
Hi @jhwangbo ,

recently, I found that the sensor is able to be put into raisimLib. I was wondering is it also possible to simulate the sensing process of sensors in raisimOgre? For instance, I want to use a depth camera on robot. Then can I get the Stereo Vision and depth information?

**Comment by jhwangbo** [comment]
Sensors will not be supported in raisimOgre. I am going to push RGB and depth implementations in raisimUnreal very soon

**Comment by jhwangbo** [comment]
I pushed the sensor implementations in raisimUnreal
