### ISSUE TITLE
Unity Screen Recording - too fast

### ISSUE THREAD

**Issue by braunjon** [raisimTech/raisimLib#331]
Hi,

I simulate for 300 steps using control_dt 1/30s which should result in 10s video.

When I record the Unity window with an external tool I get as expected 10s. But when I record with the python interface or press record in the Unity player I get 4s.

Is this happening to anyone else or is something wrong with my installation?

Thanks for feedback.

**Comment by jhwangbo** [comment]
No, actually that is somehow expected. The server doesn't know how fast you are running your simulation so it is never realtime. In addition, Unity might not record the screen as fast as you want. If you want to have the correct timing, you should run your simulation very slowly (e.g., 1/10 of the speed, in C++) while recording and later do post-process to speed it up by 10.
