### ISSUE TITLE
Get and/or clear current external forces and torques

### ISSUE THREAD

**Issue by RobertoRoos** [raisimTech/raisimLib#34]
Is there a way to find which external forces and torques are active on an `ArticulatedSystem`, set by `setExternalForce()` and `setExternalTorque()`? And a way to reset them all?

An additional comment: so the behaviour of `setExternalForce()` is different from `setGeneralizedForce()`, in the sense that the forces do not persist. I suspect they are being reset on an integration? It might be nice to have it mentioned in the documentation explicitly.

Thank you!

**Comment by jhwangbo** [comment]
I added a method (https://raisim.com/sections/ArticulatedSystem.html#_CPPv4N6raisim17ArticulatedSystem29clearExternalForcesAndTorquesEv)

I also modified the doc on setExternal*
