### ISSUE TITLE
Using Compound Objects in Raisim

### ISSUE THREAD

**Issue by christophecricket** [raisimTech/raisimLib#350]
Hi There!

I'm trying to define a compound object that is composed of two boxes in raisim. There is not much info on this (as far as I can find) in the documentation, but in the source I see I can make a compound object from a vector of `CompoundObjectChild` structs. However, I'm struggling to find how to define the size of the boxes. 

The only non-string members of the struct are `objectType`, `objectParam`, and `trans`. I've set the `objectType` on both my structs to `BOX`, and it seems like `trans` defines the relative position of the boxes, but modifying `objectParam` only seems to change the 4 material properties of the object.

So my question is: Am I understanding all of this correctly? And if so, how can I define the size of the boxes?

**Comment by jhwangbo** [comment]
https://github.com/raisimTech/raisimLib/blob/master/examples/src/server/compound.cpp
This example should answer most of your questions. I am also working on the documentation for compound object

**Comment by christophecricket** [comment]
So I see that in the example, the shape of the capsules was defined through `objectParam`. If I want to make a box with x scaling 0.1, y scaling 0.2, and z scaling 0.3, should I do:
```
child.objectParam[0]=0.1;
child.objectParam[1]=0.2;
child.objectParam[2]=0.3;
```
?

**Comment by jhwangbo** [comment]
Yes, exactly

**Comment by christophecricket** [comment]
Ok thanks, I still have some issues with this, but I think it's an implementation problem on my side, and I found a work-around.

**Comment by jhwangbo** [comment]
I added a description on the parameters

https://raisim.com/sections/SingleBodyObjects.html

**Comment by christophecricket** [comment]
Thanks!
