### ISSUE TITLE
Raisim in Docker

### ISSUE THREAD

**Issue by dtch1997** [raisimTech/raisimLib#353]
Is Raisim compatible with being used inside a (GPU-accelerated) docker container? 

1. Can the activation key for the host machine be used inside the docker container? 
2. Can the Raisim server inside the docker container connect to RaisimUnity running on host machine? 
3. If yes to above two, are there any public examples on how to do it?

**Comment by jhwangbo** [comment]
1. You need a master key for that. We only provide the master key to clients who buy commercial licenses.
2. Yes. You need to map the port on the Docker side. There is nothing you have to do on the RaiSim side.
3. https://docs.docker.com/config/containers/container-networking/
