### ISSUE TITLE
Bug in Vector Math

### ISSUE THREAD

**Issue by PascalEgli** [raisimTech/raisimLib#357]
raisim::Vec<3> v1({1,2,3});
    raisim::Vec<3> v2({4,5,6});
    
    std::cout << "-v1: " << -v1.e().transpose() << std::endl;
    
    raisim::Vec<3> res = (-v1)+v2;
    std::cout << "(-v1)+v2: " << res.e().transpose() << std::endl;
    
    res = -v1+v2;
    std::cout << "-v1+v2: " << res.e().transpose() << std::endl;

    res = v2-v1;
    std::cout << "v2-v1: " << res.e().transpose() << std::endl;

prints: 
-v1: -1 -2 -3
(-v1)+v2: 3 4 5 <------------------------- !!!
-v1+v2: 3 4 5  <-------------------------- !!!
v2-v1: 3 3 3

**Comment by PascalEgli** [comment]
did not pull the latest version.

**Comment by jhwangbo** [comment]
I added the negative operator overloading. It didn't exist before so I am wondering how it compiled
