### ISSUE TITLE
Seeking for explanation for Contact::skip()

### ISSUE THREAD

**Issue by Wang-Zhicheng** [raisimTech/raisimLib#358]
Hi there,

In the [Contact Example](https://raisim.com/sections/Contact.html) the quote says "_if the contact is internal, one contact point is set to 'skip'_". But the detailed definition and the condition that makes contact.skip_ true is not mentioned in the library. Especially the difference between isSelfCollision() and skip().

My personal guess is that skip_ marks the unrealistic contact point created by ABA algorithms, and it's the collision inside the same link. While  isSelfCollision() marks the physical plausible contact point between two links inside an  articulated system.

Please add some further clarification about skip to Contact.hpp

Btw, getting contact impulse from a skipped contact point might cause segmentation fault since the vector is not initialized. Can put that in the documentation too.

**Comment by jhwangbo** [comment]
isSelfCollision() is for both contact points and skip() is only for one of them chosen arbitrarily. I'll improve the doc on this on the next release.

BTW, skip is nothing to do with ABA.

**Comment by jhwangbo** [comment]
I updated the doc. Now the impulse is stored regardless of the body type. This will cause a few unnecessary copy operations but it is much better than confusing users.
