### ISSUE TITLE
Documentation on world XML files

### ISSUE THREAD

**Issue by RobertoRoos** [raisimTech/raisimLib#36]
It's mentioned in https://raisim.com/sections/WorldSystem.html#world that you can also create a world through an XML file. But I can't find any reference on how create such an XML file.

I realise you can export a world to an XML too. If that's the only intended use, it might be good to mention that too.

(And while I have your attention, maybe creating a RaiSim forum would be useful? That might provide a better knowledge database than the issues list.)

Thank you!

**Comment by jhwangbo** [comment]
You have a few examples here https://github.com/raisimTech/raisimLib/tree/master/rsc/xmlScripts

Yes, I definitely have to add proper documentation on the XML scripting part. I'll add it this week.

The downside of a forum is that I have to pay for the server maintenance. Github is free. Is there anything you cannot do with the Github issue list? what's the advantage of a forum over Github?

**Comment by RobertoRoos** [comment]
Alright, examples are will definitely be enough for now.

_About forums:_
Yeah, that's a fair consideration.
I guess there isn't anything I cannot do, but I think finding existing information might be easier. And a forum is better suited for users-amongst-users discussion, while Github issues feel more like users-with-developers.

There are some free forums available. You could give it a go and migrate to a real service if you like it.
Can't you host it on https://raisim.org? Otherwise a VPS starts at 4$ a month. Please contact me directly if you think I might be able to help you! Let's table that part of the discussion otherwise.

**Comment by jhwangbo** [comment]
raisim.com is a static website hosted by github. I cannot create a forum there.

I don't expect much inputs from users. Even for pybullet which has a large community of users, users don't interact much at the forum (https://pybullet.org/Bullet/phpBB3/viewforum.php?f=24&sid=c877c19002be97510433e00ede9de1c9).

I think Github issue has been decent so far. Search is easy. I can label an issue. I can also easily reference a commit. Github will never go out of business (at least until this project becomes inactive).
