### ISSUE TITLE
Will GPU help to boost the simulation speed in Raisim with multiple robots?

### ISSUE THREAD

**Issue by edward9503** [raisimTech/raisimLib#360]
Hi @jhwangbo ,

recently I was trying to run multiple quadrupeds (around 50) in Raisim with RaisimOgre as visualizer. The OS system of my PC is Ubuntu 20.04, without any NVIDIA GPU card. I found that when I run only a few robots, the simulation speed is fine. But when I run a lot of them, the simulation begins to be sluggish. I was wondering if mounting a GPU to my PC will help to boost the simulation.

If yes, which of the following GPU do you think has a better performance on the boosting? 
1. NVIDIA RTX A4500 Graphics Card, which is a professional graphics card.
2. NVIDIA RTX 3080Ti, which is a famous gaming GPU.

Best

**Comment by edward9503** [comment]
Hi @jhwangbo ,

Is there any feedback on this? Thanks in advance.

**Comment by jhwangbo** [comment]
Are you talking about reinforcement learning? Raisim doesn't use GPU. None of them will help.

The reinforcement learning example will be faster with a GPU. I don't know about A4500 but 3080ti is the popular choice

**Comment by edward9503** [comment]
@jhwangbo Thanks. There is one example code runs 50 Aliengo together in RaisimOgre. And my CPU is I7, still feel sluggish. So in this cas only my CPU matters?

**Comment by jhwangbo** [comment]
Yes. Raisim will only use one core of your CPU. 50 Aliengo in one environment can be challenging.

**Comment by edward9503** [comment]
@jhwangbo Can I somehow use multiple cores of CPU to render 50 Aliengo in one environment?

**Comment by jhwangbo** [comment]
No, that's not supported.

**Comment by jhwangbo** [comment]
I am closing this issue. Let me know if you have further questions
