### ISSUE TITLE
Does raisimGymtorch do action normalization?

### ISSUE THREAD

**Issue by LALALADA-SPONGEBOB** [raisimTech/raisimLib#361]
Hi! raisimTech!

While setting my own experimental environment, I got general questions regarding the raisimGymtorch code.

1. It seems like observation space is being normalized. but I wonder if action normalization is being done in the code.
2. I see that implemented action is the difference from the initial position but I wonder why you implemented action as the difference from the  initial position and not as the target joint position. Also I wonder why you scaled the action by 0.3

**Comment by jhwangbo** [comment]
1. no. The linear layer at the end is already doing a good job in action scaling. I didn't find it necessary.
2.  Those are just task-specific normalization of action, which is fixed not learned. They affect the learned performance. They are from my intuition.
