### ISSUE TITLE
What is the physical meaning of each parameter in the terrain generator? Can we make the slipper ground or change its stiffness?

### ISSUE THREAD

**Issue by romansabaek** [raisimTech/raisimLib#362]
Hi Prof. Jemin,

I have some questions about the terrain properties and model dynamics setting in Raisim.
What is the physical meaning of the following parameter in the terrain generator?

terrainProperties.frequency = 0.2;
terrainProperties.zScale = 3.0;
terrainProperties.xSize = 20.0;
terrainProperties.ySize = 20.0;
terrainProperties.xSamples = 50;
terrainProperties.ySamples = 50;
terrainProperties.fractalOctaves = 3;
terrainProperties.fractalLacunarity = 2.0;
terrainProperties.fractalGain = 0.25;

Also, can we change the stiffness of the ground? or make the slippery ground? (like sand and ice)
If there is any detailed documentation or example, it would be very helpful.

**Comment by jhwangbo** [comment]
The terrain generator is a standard perlin noise. You can find a good description here
https://gamedev.stackexchange.com/questions/197861/how-to-handle-octave-frequency-in-the-perlin-noise-algorithm

Raisim is rigid body simulator and you cannot change the stiffness of the ground.
You can change the coefficient of the object. https://raisim.com/sections/MaterialSystem.html
