### ISSUE TITLE
Whether can add mouse interaction function?

### ISSUE THREAD

**Issue by chillybird** [raisimTech/raisimLib#363]
Now, the simulator is very poor in interaction methods. I cannot know the initial orientation or impose my self-defined external force on the robot, and I have to write my code to develop it, but that is weird and not be accepted!

**Comment by jhwangbo** [comment]
Please be polite. I have to ban you from this repo if you are not.

This is definitely an important direction. I am on it. Probably I can push it in a month

**Comment by chillybird** [comment]
> Please be polite. I have to ban you from this repo if you are not.
> 
> This is definitely an important direction. I am on it. Probably I can push it in a month

I apologize for my rude remarks. I am not very good at using english, so I may not be able to correctly control the emotions contained in the sentence.

In addition, thank you for your contributions to RL simulator.

**Comment by jhwangbo** [comment]
Please check the new updates on RaisimUnreal. Now you can pull objects

**Comment by chillybird** [comment]
ok，thank you very much.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Jemin ***@***.***> |
| Date | 09/23/2022 17:02 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [raisimTech/raisimLib] Whether can add mouse interaction function? (Issue #363) |

Please check the new updates on RaisimUnreal. Now you can pull objects
