### ISSUE TITLE
RaisimUnity (Linux) v1.1.4 does not work well

### ISSUE THREAD

**Issue by JewelryForge** [raisimTech/raisimLib#366]
In v1.1.4, RaisimUnity seems to work worse than v1.1.3 in linux. Here are some issues:
- raisim::RaisimServer::focusOn seems to have no effect on RaisimUnity.
- When manually choosing my robot in the "LookAt" menu, the view has already switched to my robot but "LookAt" still shows "Select Object".
- "External Forces" has no effect when clicked in RaisimUnity v1.1.4.

Here are some contrasts:
v1.1.3
![Screenshot-20220906121814-1024x791](https://user-images.githubusercontent.com/66123485/188546741-5e3f5ae8-404c-41d4-b78c-c8d12125e12a.png)

v1.1.4
![Screenshot-20220906121405-1024x804](https://user-images.githubusercontent.com/66123485/188546788-720181d6-c18b-4f07-b3f3-9227e24ff844.png)

**Comment by jhwangbo** [comment]
Yes, I am aware of these issues. I will push the fixes soon.

**Comment by jhwangbo** [comment]
I pushed a fix for Linux and Windows. Mac versions will follow soon. Let me know if you find more issues
