### ISSUE TITLE
Disable contact at runtime

### ISSUE THREAD

**Issue by RobertoRoos** [raisimTech/raisimLib#37]
Is it possible to disable contact for an object or all objects at runtime? Basically I would like to turn my robot into a ghost that's not bothered by other objects.

Maybe by changing the collision group? I couldn't find anything about this in the API.

Thank you!

**Comment by jhwangbo** [comment]
I pushed this feature just now. You can do 

```
  for (auto &colBody : robot->getCollisionBodies()) {
    colBody->setCollisionGroup(GROUP);
    colBody->setCollisionMas(MASK);
  }
```
will add this to doc tmr

**Comment by RobertoRoos** [comment]
Thank you very much!

Follow-up question, is there a mask that disables all contact? 
I tried the following:

    /// Disable all contacts
    const bool enable = false;
    for (auto& colBody : robot->getCollisionBodies()) {

        // Set some non-default collision group
        const auto col_group = raisim::COLLISION(99);
        colBody.setCollisionGroup(col_group);

        // Either let it only collide with itself, or with everything (= -1)
        if (enable) {
            colBody.setCollisionMask(-1);
        } else {
            colBody.setCollisionMask(0);
        }
    }

And linking it only with its own group:

            colBody.setCollisionMask(raisim::COLLISION(99));

But in both cases my robot still lands on the floor (while I want it to go through it)

**Comment by jhwangbo** [comment]
The default collision behavior was "or" which means ``mask2 & group1 || mask1 & group2``. I changed the logic to ``and``. It should work now
