### ISSUE TITLE
Reliability of getPairContactIndexInPairObject()

### ISSUE THREAD

**Issue by Luocheng-Zheng** [raisimTech/raisimLib#375]
Hello. I'm currently doing research on manipulating articulated objects using raisim. The object has two parts, top and bottom. In one of my simulations, the thumb tip obviously touches the bottom. Only the semicircle slice at the top is the "top". The rest is all "bottom".
![Screenshot-2022-09-28-10-09-58](https://user-images.githubusercontent.com/38021867/192879858-88f4845a-a9a0-456a-a9fd-2053b1b87824.png)
![Screenshot-2022-09-28-10-10-17](https://user-images.githubusercontent.com/38021867/192879882-cebf00d1-231c-4cc8-b40a-2d5660387221.png)
![Screenshot-2022-09-28-10-10-35](https://user-images.githubusercontent.com/38021867/192879903-bdb895e7-3a11-455b-87d0-c4b2e8d824f3.png)
However, when I want to detect whether the finger touches the top or the bottom by doing the following (`arctic` is the articulated object, which is a fixed base arcticulated object; `mano_l` is the hand)
```
auto& contact_list_obj = arctic->getContacts();
for(auto& contact: mano_l_->getContacts()) {
    if (contact.skip() || contact.getPairObjectIndex() != arctic->getIndexInWorld()) continue;
    if (contact_list_obj.size() <= contact.getPairContactIndexInPairObject()) continue;
    if (contact_list_obj[contact.getPairContactIndexInPairObject()].getlocalBodyIndex() != top_id) continue;
    ...
}
```
`contact_list_obj[contact.getPairContactIndexInPairObject()].getlocalBodyIndex()` is always equal to `top_id` (1), and never equal to `bottom_id` (0). 

Also, `contact.getPairContactIndexInPairObject()` is sometimes larger than `contact_list_obj.size()` in the fourth line. 

Therefore, I wonder what `getPairContactIndexInPairObject` actually does. Or maybe I didn't use it correctly. Thank you in advance!

**Comment by jhwangbo** [comment]
The description of the methods is here: https://raisim.com/sections/Contact.html
It seems like what you are looking for is getlocalBodyIndex

**Comment by Luocheng-Zheng** [comment]
I still don't understand. It cannot explain why `getPairContactIndexInPairObject()` return a large value.

Also, `getlocalBodyIndex` even returns `top_id` for the pair contact of the contact on thumb tip.

**Comment by jhwangbo** [comment]
Can you share the reproducible code?

**Comment by Luocheng-Zheng** [comment]
Sure. I have send you the invitation to my repo.

**Comment by jhwangbo** [comment]
I figured out the issue. To save time, I do not store contacts if the body type is static. I will think about the fix.

What you do as a workaround is to check the pair object body type using `getPairObjectBodyType()`
