### ISSUE TITLE
Stable baselines evaluation error

### ISSUE THREAD

**Issue by isgeles** [raisimTech/raisimLib#377]
If I try to run the standard stable baselines evaluation after the `model.learn()` method with 

```
from stable_baselines3.common.evaluation import evaluate_policy
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=100)
```

I end up with this error 

```
...
File "/home/raisimLib/raisimGymTorch/raisimGymTorch/stable_baselines3/RaisimSbGymVecEnv.py", line 112, in env_is_wrapped
    target_envs = self._get_target_envs(indices)
AttributeError: 'RaisimSbGymVecEnv' object has no attribute '_get_target_envs'
```

The method `_get_target_envs` is not implemented in the repository. Any ideas on how to fix it?

**Comment by jhwangbo** [comment]
I checked the code and evaluate_policy cannot be used on the raisimGym environment. You have to modify the implementation in rsg_anymal/runner.py for SB3.

Openai Gym VecEnv assumes that there is an individual python environment. But RaisimGym does not operate in this way. The parallelization of RaisimGym is inside C++ (and this is why it is much faster).

**Comment by jhwangbo** [comment]
BTW, the SB3 version has serious performance issues. I am investigating it now but I highly recommend using the RaisimGym version

**Comment by isgeles** [comment]
I am using the RaisimSbGymVecEnv file and it is working if you write your own evaluation method, however, now I am having issues with the observation normalization since the RaisimSbGymVecEnv version never updates the mean/variance stats

**Comment by jhwangbo** [comment]
anymal.py example with SB3 has a much lower performance than my implementation. I figured out a few issues. The biggest one is that it uses shared policy and value configuration.

I'll push the scaling saving methods soon

**Comment by isgeles** [comment]
I fixed the scaling and added a pull request [#384](https://github.com/raisimTech/raisimLib/pull/384), I also trained and tested the anymal environment with stable baselines and it was only successful with the VecNormalize wrapper from SB3, however, taking a lot longer for training.
Is there any reward normalization happening in Raisim?

**Comment by skoo1** [comment]
I added VecNormalize wrapper from SB3 in anybody.py as isgeles wrote and disabled observation normalization in raisim environment wrapper. Now, the ppo in SB3 works as good and fast as the ppo in raisim. I added a pull request #385.

**Comment by isgeles** [comment]
for me, it takes around 10 times more environment simulation steps even with that wrapper
