### ISSUE TITLE
Model investigation example

### ISSUE THREAD

**Issue by RobertoRoos** [raisimTech/raisimLib#38]
Back with more 🙃
A suggestion this time: getting your URDF robot model right can be kind of tricky. And investigating if your joints behave as desired is not trivial.
I would much like to have a RaiSim application where I can:

- Load my robot (or entire world)
- Pause/play simulation
- View the values of the generalized coordinates
- Change the gen. coordinates when paused
- View/change the gen. torques

Much like MuJoCo's `simulate` example:
<img src="https://images2.programmersought.com/439/bf/bf4a7233d3c9c25033942e3e9b37abff.png" width="500px"/>

This would be the perfect way to benchmark a developed URDF file.

I'll see if I can make something like this, but I'm not yet familiar with Ogre.

**Comment by jhwangbo** [comment]
I have a plan to do this. I don't know when I get time for it tho. Right now raisimUnity is just visualizing what's happening on the CPP side. I want to have a UI on the Unity side to fully control the simulation. but I cannot guarantee when I can finish it.

**Comment by jhwangbo** [comment]
I added a joint display panel which you can use to visualize joint frames. This should help you identify joint positions.

Currently, you cannot set the joint position. This is coming soon

**Comment by jhwangbo** [comment]
![Screenshot from 2021-02-21 22-56-10](https://user-images.githubusercontent.com/3340750/108630101-83d37a80-74a6-11eb-9ab1-107fa73d4a67.png)
Now you can display joints and frames as above. You should press ``T`` to go to a transparency mode. I pushed a linux version. Other OS supports will follow tmr.
