### ISSUE TITLE
The norm of quaternion in raisim state is not exactly 1.0

### ISSUE THREAD

**Issue by JewelryForge** [raisimTech/raisimLib#380]
I accidentally find when I run `getState` immediately after run`setState`, the result of `getState` is not quite the same as the value of `setState`. Then I find that the norm of quaternion in raisim state is not exactly 1.0, and the result of the code is quite surprising. Here is a sample code for reproduction:
```c++
robot_->setState(gc_init, gv_init);
Eigen::VectorXd gc, gv;
robot_->getState(gc, gv);

std::cout << "Set Q :" << std::setprecision(20) 
          << gc_init.segment<4>(3).transpose()
          << " norm:" << gc_init.segment<4>(3).norm() << std::endl;
std::cout << "Get Q1:" 
          << gc.segment<4>(3).transpose() 
          << " norm:" << gc.segment<4>(3).norm() << std::endl;

robot_->setState(gc, gv);
robot_->getState(gc, gv);
std::cout << "Get Q2:" 
          << gc.segment<4>(3).transpose() 
          << " norm:" << gc.segment<4>(3).norm() << std::endl;
```
And I get a result like this:
```
Set Q :  0.99011399654963672123 -0.012676811507773463536   0.10198994907542507926 -0.095454819543564828344 norm:1
Get Q1:  0.99011399654963694328 -0.012676811507773467005   0.10198994907542510702 -0.095454819543564856099 norm:1.000000000000000222
Get Q2:  0.99011399654963672123 -0.012676811507773463536   0.10198994907542507926 -0.095454819543564828344 norm:1
```
The quaternion I set has been normalized but raisim seems to normalize it a second time. This somehow affects the consistence of my system. Could you please tell me if it's normal or explain the result? Thank you very much!

**Comment by jhwangbo** [comment]
This looks normal to me. This also depends on the CPU. It is not guaranteed that the same operation gives you the same result down to the last significant digit on different CPU's.
