### ISSUE TITLE
About licensing issues

### ISSUE THREAD

**Issue by jangmingyu** [raisimTech/raisimLib#386]
Hi I was using raisim until recently and got a sign saying my license expired. I'm a student and I'm using an academic license and I'd like to know how to proceed with this issue.

The error display in raisim is as follows.

`THIS LICENSE HAS EXPIRED. PLEASE GET A NEW LICENSE`

Do I need to renew my student license periodically? If so, I would like to know if I can apply on a regular basis.

**Comment by jhwangbo** [comment]
Please fill out the request for again
