### ISSUE TITLE
visualArrow not appearing on raisimUnity

### ISSUE THREAD

**Issue by haogaobill** [raisimTech/raisimLib#388]
Hello professor, 

It seems like my raisimUnity cannot visualize for visualArrow when I use server::addVisualArrow, it works for addVisualBox(), addVisualSphere(), however for addvisualArrow() nothing appeared when I turn on raisimUnity for visualization. Is there something special for visualArrow? my system is Ubuntu 18.04 for a x86_64 chip.

**Comment by jhwangbo** [comment]
It is not implemented yet. This is expected. I'll push it in the next update. For now, you can use two boxes to represent an arrow

**Comment by jhwangbo** [comment]
i pushed the feature
