### ISSUE TITLE
about musculoskeletal example

### ISSUE THREAD

**Issue by fanshi14** [raisimTech/raisimLib#39]
When I checked raisim website, there is a very interesting example of  Biomechanical simulation.
>> Biomechanical simulation, created by Young-Jun Koo, PhD and Seungbum Koo, PhD at Musculoskeletal BioDynamics Lab, KAIST.

I wonder if there is plan to add it to `example`, or do you know if this project is open source?

**Comment by jhwangbo** [comment]
I know the project is closed-source and they don't have a plan to share it.
