### ISSUE TITLE
Unity Connection Issue 

### ISSUE THREAD

**Issue by burakozkaynak** [raisimTech/raisimLib#391]
After running the simulation three or more times, the Unity connection is getting harder. Is there any way to deal with the error given below after starting the simulation? 
After making the file "make anymals" ı use such as "./anymals " this. "./anymals" after doing this, Unity does not connect fast it takes time after multiple runs.
Operating System:: Ubuntu 22

System.Exception: ReadData timeout!
  at raisimUnity.TcpHelper.ReadData () [0x0004c] in <1f2db7d6239b41f8a5dd20578322f5f2>:0 
  at raisimUnity.RsUnityRemote.ReadAndCheckServer (raisimUnity.ClientMessageType type) [0x000a0] in <1f2db7d6239b41f8a5dd20578322f5f2>:0 
  at raisimUnity.RsUnityRemote.Update () [0x0002a] in <1f2db7d6239b41f8a5dd20578322f5f2>:0

**Comment by jhwangbo** [comment]
I have not experienced just issues. But maybe you are referring to the wait time of the server.

When the connection is lost, the server waits 10 seconds for the client to reconnect. After 10 seconds, it accepts a connection from a new client.

This was necessary because visualization clients might take very long to load large meshes.

**Comment by burakozkaynak** [comment]
We encountered the same problem for other Lab PC. I am adding a video below to show the connection issue. We fix this problem by resetting the PC, so it connects to Unity fast. After multiple runs again, it not connecting fast or does not connect.Thank you for help

Ubuntu ver:22.04
RaisimUnity and RaisimUnityOpenGl

https://user-images.githubusercontent.com/77923283/201472695-e9546e21-c6dc-4576-b15d-acc4a7981593.mp4

**Comment by jhwangbo** [comment]
We also have ~30 Pc's in our lab and I cannot find such an issue in any of them. I have a few questions 
1. Do you see this issue in the original raisimLib examples? I see some outputs in the terminal. I guess you modified it.
2. Do you see this issue only in Ubuntu 22.04? I haven't tried 22.04
3. Do you have multiple raisimUnity running on the same PC? There might be a chance that another client is already connected to the server.

**Comment by burakozkaynak** [comment]
Thank you, sir, for your reply. We fixed the problem by reinstalling the Raisim and Graphic Driver of PC's.

Thank you for your patience.
