### ISSUE TITLE
Failed to cmake 

### ISSUE THREAD

**Issue by KwonseungCho** [raisimTech/raisimLib#399]
i set the two variables 
WORKSPACE=/home/user/raisim_workspace
LOCAL_INSTALL=/home/user/raisim_workspace

when I tried cmake
cmake .. -DCMAKE_INSTALL_PREFIX=$LOCAL_INSTALL -DRAISIM_EXAMPLE=ON -DRAISIM_PY=ON

i got error
CMake Error at CMakeLists.txt:52 (install):
  install DIRECTORY given no DESTINATION!

-- raisim:
--   Version: 1.1.5
--   Includes: /home/user/raisim_workplace/raisimLib/raisim/linux/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;raisim::raisim
-- pybind11 v2.9.0 
-- raisim:
--   Version: 1.1.5
--   Includes: /home/user/raisim_workplace/raisimLib/raisim/linux/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;raisim::raisim
-- Configuring incomplete, errors occurred!
See also "/home/user/raisim_workplace/raisimLib/build/CMakeFiles/CMakeOutput.log".

How do i fix did? I have tried change the LOCAL_INSTALL but the result was the same.

**Comment by jhwangbo** [comment]
Just for others: This happens when you don't set the environment variables. This means that ``LOCAL_INSTALL`` is empty
