### ISSUE TITLE
Does slip occur in the Raisim simulator?

### ISSUE THREAD

**Issue by romansabaek** [raisimTech/raisimLib#401]
Dear Professor,

I am trying to develop a learning locomotion controller for a wheeled legged robot via a sim-to-real transfer.
The interesting questions is if RL can handle the slip of the wheel.
To do so, testing slip condition in Raisim would be useful, and I wonder Raisim provides slip condition. 
If so, How can I setup or which parameter should I change in Raisim? 
(I think this issue is also related to how Raisim solves the contact dynamics considering wheel)

I highly appreciate your help and advice.
Looking forward to seeing your answer.

**Comment by jhwangbo** [comment]
this site explains the material system of raisim
https://raisim.com/sections/MaterialSystem.html
