### ISSUE TITLE
Where to place the activation key

### ISSUE THREAD

**Issue by ClaudioChiariello** [raisimTech/raisimLib#402]
Hello everyone, I've just received the activation key and according to raisim documentation, I should place into an hidden folder ".raisim". My problem is that I haven't in my machine this folder, despite I've installed all the packages from the git page: raisimLib, raisimPy, raisimOgre. How this folder can appear? 
Thank you very much, sorry for the inconvenience

**Comment by jhwangbo** [comment]
you should create the directory yourself.
