### ISSUE TITLE
RaisimServer bind error

### ISSUE THREAD

**Issue by HukoOo** [raisimTech/raisimLib#407]
I received the academic license file activation.riseim by email and moved it to the /home/.riseim folder.

After compiled the raisimLib, I run the executable file in the example folder and then error occurred.

> [2022:12:12:12:16:48 RaisimServer.hpp:145] bind error, errno: 98

How can we solve this problem?

**Comment by jhwangbo** [comment]
That means that you are trying to open a port that is already in use. There is a chance that you opened multiple raisim applications. If you want to do so, you have to open the server with different port numbers.
