### ISSUE TITLE
Keyboard/Mouse Integration

### ISSUE THREAD

**Issue by DenizYilmazx** [raisimTech/raisimLib#408]
Hello.

I want to send commands to the simulation from the keyboard or mouse in learning process done through Raisim. For this, I connected the keyboard with the python pynput library. But I can only send commands at certain intervals.

In order to send commands at each step of the robot, I need to use it in the for loop where I call traning functions and the world.integrate() function of Raisim, but I get an error as reached the maximum number of clients you can connect.

Is there a situation such as not connecting to a client other than unity in Raisim? Thanks in advance.

**Comment by jhwangbo** [comment]
This is probably nothing to do with raisim. What you are doing seems fine but maybe the for loop is running too fast.

I also use a keyboard input this way but only in ``test.py`` file with a sleep function.
