### ISSUE TITLE
Getting collisions (contacts) of consumed links

### ISSUE THREAD

**Issue by shafeef901** [raisimTech/raisimLib#413]
I'd like to know if it's possible to get the contact objects of the consumed links. I want to get the contacts of the feet and the calves separately. Here's the error I get when trying to do the same:

> [2022:12:20:11:22:57 ArticulatedSystem.cpp:1833] This is a link name. In RaiSim, links with fixed joints are consumed by a parent with a movable joint. If you want to access a link position, use a frame instead. Frames are attached to all joints, including fixed ones.

**Comment by jhwangbo** [comment]
You can get which collision body is in contact. A collision body is defined in an URDF link. If you have a link called ``Calf``, then its first collision body is called ``Calf/0``.
The two names of the collision bodies that are in contact can be retrieved by ``Contact::getCollisionBodyA::name`` and ``Contact::getCollisionBodyB::name``. You can get if the object is objectA or B using ``Contact::isObjectA``.
I'll update the example in the documentation to make it clear.
