### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by geekflyfly** [raisimTech/raisimLib#417]
**The machine id is changed**. The following is description.
After I install the raisimLib, I run  "./anymals" , it told me "Illegal instruction (core dumped)".
The CPU of my windows is 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz (support AVX2).
 I install ubuntu 20.04 in Oracle VM virtual box 7.0.
Unfortunately, after I  enable the VT-x/AMD-V, my virtual machine still does not support AVX2. 
Then I guess that Hyper-V  causes this problem.
First, in "Turn Windows features on or off", I uncheck Hyper V, Windows Hypervisor Platform and Windows Sandbox;
Second, I disable Memory integrity (reference to https://support.bluestacks.com/hc/en-us/articles/360055244412-How-to-disable-Hyper-V-on-Windows-to-run-BlueStacks-5).
 Finally, the ubuntu 20.04 support the AVX2, I run "./anymals", it returns "The license was issued to another machine", **that is to say, the machine id is changed**!  Can you tell me why? Now I have to get  a new activation key. I  also send this to [info.raisim@gmail.com](mailto:info.raisim@gmail.com)

look forward to your reply.

**Comment by jhwangbo** [comment]
The machine id is for a specific pc, specific OS, specific user. Virtual machine will probably change all of them. 

If you delete the activation key and run the example, it will give you the machine id. Then, restart your PC and do the same . Check the machine id is not changed. If it is consistent, then you should apply for an activation key with that machine id.

**Comment by geekflyfly** [comment]
Thanks for your quick response, I try the way you provided.

**Comment by geekflyfly** [comment]
I have tried the way, but it doesn't work. By the way, upgrade ubuntu 18.04 to 20.04 will change the machine id？ I do this when "log@GLIBC_2.29" appears. I have sent an email for applying a  new activation key using the current machine id.

**Comment by jhwangbo** [comment]
What doesn't work? Does the machine id change?
Ubuntu 18.04 is not supported anymore.

**Comment by geekflyfly** [comment]
The machine id is not changed. The program still returns "The license was issued to another machine".

**Comment by jhwangbo** [comment]
That's totally expected. You created a new "virtual" machine. That has a different machine id.

**Comment by geekflyfly** [comment]
OK, That's all. Thanks. RaiSim is a great platform, it will be perfect if you give a detailed tutorial about that. Some documents on your web are so difficult for a beginner.

**Comment by jhwangbo** [comment]
I have a plan to make tutorial videos and post them on youtube. It will be done within a month.
