### ISSUE TITLE
simulation_dt vs control_dt

### ISSUE THREAD

**Issue by ClaudioChiariello** [raisimTech/raisimLib#421]
Hello everyone, my could be a trivial question, but I don't get the difference between this 2 variables which are defined bot in the cfg.yaml file and in the RaisimGymEnv.hpp (with different values, and this confuses me). What I thought is that the simulation_dt represent the simulation time, that is the time elapsed by one step and another of the RL algorithm. 
In RL, the agent at the time $t$ perform an action $a_t$, and at the time $(t+1)$ receive a reward and the next state $s_{t+1}$. 
Is the distance between  $t$ and $(t+1)$ the simulation_dt??

And the control_dt? I've thought that is something related to the PD controller following the RL controller. 
Anyway, why there are 2 definitions in the cfg.yaml file and RaisimGymEnv.hpp file?
I am not sure about my answer, so thank you for your help =)

**Comment by jhwangbo** [comment]
The difference between $t$ and $(t+1)$ is control_dt. There are ``control_dt/simultion_dt`` simulation steps within one control_dt.
