### ISSUE TITLE
Implementation of raisimGymTorch on self-designed legged robot

### ISSUE THREAD

**Issue by newethan33** [raisimTech/raisimLib#422]
Hello,
I'm trying to train the legged robot in simulation using the PPO model.
Then implement the training results in the real world.
However, my self-designed robot, Mdog,  is different from the legged robots in the Raisim Library, e.g., Anymal.
Does it mean that I have to create an URDF model for Mdog and then train on the Raisim simulation, so that I can implement it in the real world?
Or is there any method to transform the parameters trained on Anymal to the parameters on Mdog?

If it's necessary to change the URDF model, I wonder if there is any way to quickly generate a URDF model according to the mesh file of my legged robot.
Thank you!

**Comment by jhwangbo** [comment]
There is not easy way. You have to change all the mesh files, link dimensions, mass, inertia and joint properties.
