### ISSUE TITLE
std::__ios_failure  Aborted (core dumped)

### ISSUE THREAD

**Issue by geekflyfly** [raisimTech/raisimLib#423]
Hello, I clone  the ([RAISIM_EXAMPLE](https://github.com/raisimTech/raisimExample)), after  cmake and make, I get the error as follows, my raisimLib is v1.1.6.  Thanks.
![image](https://user-images.githubusercontent.com/58647939/213067201-f8df3ed5-6363-4af0-94fd-86e70404d185.png)

**Comment by jhwangbo** [comment]
You ran your code and I don't know what's inside. You should run GDB and figure out which line causes that issue. You should also post your code

**Comment by geekflyfly** [comment]
**I hardly changed it except for the activationKey path.**
here is my code
#include "raisim/World.hpp"
#include "raisim/RaisimServer.hpp"

int main(int argc, char* argv[]) {
  auto binaryPath = raisim::Path::setFromArgv(argv[0]);

  raisim::World::setActivationKey("/home/lzy/.raisim");
  raisim::World world;
  auto laikago = world.addArticulatedSystem(binaryPath.getDirectory() + "\\rsc\\laikago\\laikago.urdf");
  auto ball = world.addSphere(0.1, 1);
  auto ground = world.addGround(-2);
  world.setTimeStep(0.002);

  /// launch raisim server for visualization. Can be visualized using raisimUnity
  raisim::RaisimServer server(&world);
  server.launchServer();

  for (int i=0; i<10000; i++) {
    raisim::MSLEEP(2);
    server.integrateWorldThreadSafe();
  }

  server.killServer();
  std::cout<<"end of simulation"<<std::endl;
}

**Comment by ClaudioChiariello** [comment]
Hi, instead of raisim::World::setActivationKey("/home/lzy/.raisim"); 
use:
raisim::World::setActivationKey("~/.raisim");
