### ISSUE TITLE
Stuck wheel in rolling motion

### ISSUE THREAD

**Issue by ghost** [raisimTech/raisimLib#426]
Hi,

I am working on a two wheeled robot, and observed a strange thing in 1.1.6 (compiled from master branch). 
Detail:
As the robot moving forward, one wheel is like "stuck in the ground". As you can see in the attached videos, the velocity of the wheel suddenly decreases to zero.
The controller was previously tested in raisim 1.1.2.
video:
https://drive.google.com/file/d/1qclGKLv3lSRJ-d3Rbtsal5FfLAJMsEj5/view?usp=sharing
https://drive.google.com/file/d/1k7mmdU3WboN3B44TRTFzXpJOebKVz_dF/view?usp=share_link

**Comment by jhwangbo** [comment]
Do you have a joint limit set? It stops at 5 rad.
