### ISSUE TITLE
Simulation progressiviely slows down when instantiating multiple objects after reset

### ISSUE THREAD

**Issue by shafeef901** [raisimTech/raisimLib#428]
Hi!
I am trying to instantiate multiple `raisim::Box` of different dimensions, orientations and positions as in the picture below.

![Screenshot from 2023-02-03 15-55-04](https://user-images.githubusercontent.com/24255993/216634539-1ed3e5b4-bd22-4602-84a6-a0e276e146c4.png)

I have noticed that the simulation slows down progressively when attempting to instantiate multiple objects after resetting numerous times.

Instantiated using the code below:
```
for (uint j=0; j < numPallets_; j++)
  obj[j] = world->addBox(8, W, H, 100, "default", raisim::COLLISION(-100-j), raisim::COLLISION(0) | raisim::COLLISION(1) | raisim::COLLISION(2))
```
I remove these objects from the world when reset is invoked using the code below:
```
if(obj.size()) {
  for (auto o: obj)
    world_->removeObject(o);
}
obj.clear();
```
And then re-instantiate them again using the code above. 

Any idea why this slowdown could be happening, maybe a possible memory leak?

Thanks in advance.

**Comment by jhwangbo** [comment]
Does it slow down even without the visualizer?

**Comment by jhwangbo** [comment]
Can you also check the memory using "htop" (linux)  or "task manager" (win)?

**Comment by shafeef901** [comment]
> Does it slow down even without the visualizer?

Yes! I've noticed that the fps drops while training my agent without the visualizer. Started from  ~60fps and dropped to 8fps after about 6 hrs of training.


> Can you also check the memory using "htop" (linux) or "task manager" (win)?

htop during beginning of sim (with viz):

![Screenshot from 2023-02-06 11-06-13](https://user-images.githubusercontent.com/24255993/216943658-90e5e8a0-9136-43c4-86d4-ec81dfc83521.png)

htop after couple of minutes in sim (with viz, this image was captured first so explains the time inconsistency):

![Screenshot from 2023-02-06 11-05-11](https://user-images.githubusercontent.com/24255993/216943635-a7626568-d1a5-4844-a243-833b934ec58d.png)

**Comment by jhwangbo** [comment]
I made a simple code to test the memory leak in object deletion but I couldn't find it. The memory usage is fixed. Valgrind output is also clean. I also find any increase in memory usage in your output. But you might need a couple of hours to see effects.

So your memory leak is somewhere else. You should run valrind on your debug app to spot where it is.

**Comment by ClaudioChiariello** [comment]
Hi, I have a very similar problem. Do you know if there are way to reshape the object inserted in the raisim::World? Because my idea was to remove the object and then reinsert with a different shape. But I am encountering a lot of problem doing this. Especially segmentation fault.

**Comment by jhwangbo** [comment]
The segmentation fault is often due to forgetting ``raisim::RaisimServer::lockVisualizationServerMutex``. If you want to delete or add an object and the server is running, you have to make sure that all raisim operations are executed with the mutex protection.

There is no way to reshape ``raisim::SingleBodyObject``. You have to delete an recreate it. I tested object deletion and addition with the following code. There is no symtoms of memory leak. The Valgrind output is clean. If you think that there is memory leak, you have to post reproducible code

```
    int main(int argc, char* argv[]) {
        auto binaryPath = raisim::Path::setFromArgv(argv[0]);
      
        raisim::World world;
        world.setTimeStep(0.005);
      
        while (1) {
          RS_TIMED_LOOP(int(world.getTimeStep()*1e6))
      
          /// create objects
          auto ground = world.addGround();
          ground->setName("ground");
          ground->setAppearance("grid");
          std::vector<raisim::Box*> cubes;
          std::vector<raisim::Sphere*> spheres;
          std::vector<raisim::Capsule*> capsules;
          std::vector<raisim::Cylinder*> cylinders;
      
          static const int N = 6;
      
          for (size_t i = 0; i < N; i++) {
            for (size_t j = 0; j < N; j++) {
              for (size_t k = 0; k < N; k++) {
                std::string number =
                    std::to_string(i) + std::to_string(j) + std::to_string(k);
                raisim::SingleBodyObject* ob = nullptr;
                switch ((i + j + k) % 4) {
                  case 0:
                    cubes.push_back(world.addBox(1, 1, 1, 1));
                    ob = cubes.back();
                    ob->setAppearance("blue");
                    break;
                  case 1:
                    spheres.push_back(world.addSphere(0.5, 1));
                    ob = spheres.back();
                    ob->setAppearance("red");
                    break;
                  case 2:
                    capsules.push_back(world.addCapsule(0.5, 0.5, 1));
                    ob = capsules.back();
                    ob->setAppearance("green");
                    break;
                  case 3:
                    cylinders.push_back(world.addCylinder(0.5, 0.5, 1));
                    ob = cylinders.back();
                    ob->setAppearance("0.5, 0.5, 0.8, 1.0");
                    break;
                }
                ob->setPosition(-N + 2. * i, -N + 2. * j, 1. + 1.5 * k);
              }
            }
          }
      
          for (int i=0; i<5; i++)
            world.integrate();
      
          for (auto c : cubes)
            world.removeObject(c);
      
          for (auto c : spheres)
            world.removeObject(c);
      
          for (auto c : capsules)
            world.removeObject(c);
      
          for (auto c : cylinders)
            world.removeObject(c);
        }
      }
```
