### ISSUE TITLE
Problems adding and removing object in the world

### ISSUE THREAD

**Issue by ClaudioChiariello** [raisimTech/raisimLib#429]
Hello, I am trying to train the ANYmal in raisim adding boxes in order to arrange steps. The porblem of course, is that the training time slow down drastically. Therefore I decided to insert object only after some episodes. To do this, I putted the following code in the 'curriculumUpdate' of Environment.hpp: 
```
std::vector<raisim::Box*> boxes

   if(num_episode ==100){
      for (int i=0; i<num_steps; i++){
        boxes.push_back(world_->addBox(width_step -i, width_step-i, height_step, 10)); 
        boxes[i]->setName("step" + std::to_string(i)+"-th");
        boxes[i]->setPosition(15,0,0.5*i);
        //steps_indices[it] = *it->getIndexInWorld();  ///update the indices of the steps.
      }
    }   
```
The problem is that when I launch the runner.py, when it reach the episode 100, return me this error:
```
[2023:02:07:13:12:23 Reward.hpp:46] forwardVel is nan
[2023:02:07:13:12:23 Reward.hpp:46] forwardVel is nan
Segmentation fault (core dumped)
```

I don't know how to fix, the only thing it seems to works is to put that code into the constructor and then update the shape of the blocks in the curriculumupdate() function. 
There is something that I missed?

**Comment by jhwangbo** [comment]
do you check where ANYmal is? if the boxes are piercing ANYmal unrealistically, the simulation might be unstable

**Comment by ClaudioChiariello** [comment]
yes. I estimated the position with ```anymal_->getFramePosition(baseFrameIdx, anymal_pos_);``` and then added when I make:
```boxes[i]->setPosition(15,0,0.5*i);``` but the same error still occur

**Comment by ClaudioChiariello** [comment]
I was reading your last comment in the other issue. I should manage the serve in a particular way in the curriculumupdate() function? The fact is that is not so clear to me how ```server->lockVisualizationServerMutex()``` and ```world->integrate``` work

**Comment by jhwangbo** [comment]
Your mutex code is correct. You can probably put the mutex code inside ``if (num_episode==1)...``

What I meant is that you should not place ANYmal and other objects with an overlap. You should check the position of the ANYmal and place the boxes away from it.

**Comment by ClaudioChiariello** [comment]
Hi, I am quite sure that the boxes should spawn away from the anymal. I retrieve the pose of the anymal:

```size_t baseFrameIdx = anymal_->getFrameIdxByLinkName("LF_SHANK");
   anymal_->getFramePosition(baseFrameIdx, anymal_pos_);```
I retrieve the position of the left fore shank because for some reason, it doesn't allow me the take the FrameIdx of the base, but anyway, I know approximately where the robot is.

And when I set the position I make:

```boxes[i]->setPosition(anymal_pos_[0] + 15, 0, 0.5);```

This should ensure me that the object doesn't pierce the ANYmal, shouldn't it?

**Comment by jhwangbo** [comment]
I didn't get your question. ``world.integrate`` should be between the mutex calls. This means that your main thread is locking the mutex so that the visualization thread cannot access variables of world. It can also be inside a ``for loop``

**Comment by ClaudioChiariello** [comment]
Hi, I solved the problem to add boxes in the world. But currently, when the ANYmal is trained in an environment which contains object, the simulation goes extremely slow. Just few moment before to add the boxes, the quadruped walk and trot with, but after that object have been added, it moves very very slowly.

The training algorithm is the same provided by raisim. Most likely, you know that in Environment.hpp is defined the step function for the RL algorithm:
``` float step(const Eigen::Ref<EigenVec>& action) {
    /// action scaling

    pTarget12_ = action.cast<double>();
    current_action_ = pTarget12_;  //I put the last action in the observation space

    pTarget12_ = pTarget12_.cwiseProduct(actionStd_);
    pTarget12_ += actionMean_;
    pTarget_.tail(nJoints_) = pTarget12_;

    anymal_->setPdTarget(pTarget_, vTarget_);
  
    for(int i=0; i< int(control_dt_ / simulation_dt_ + 1e-10); i++){
      if(server_) server_->lockVisualizationServerMutex();
      world_->integrate();
      if(server_) server_->unlockVisualizationServerMutex();
    }
   //code
  return reward.sum();
  }
```

**Comment by jhwangbo** [comment]
Sorry for replying late. Your simulation will slow down if you add more than 20 boxes. Raisim is not faster than other physics engines in terms of collision checking. It is designed for simulating a small number of objects really fast.
