### ISSUE TITLE
Load a mujoco xml file

### ISSUE THREAD

**Issue by YandongJi** [raisimTech/raisimLib#43]
Hi can you add some content in the documentation about how to import an articulated system from an xml file in mujoco format? This may seem important when you are using models formerly created for mujoco.

**Comment by jhwangbo** [comment]
I'll put this one on my to-do list.

**Comment by ashish-kmr** [comment]
+1. Is there an estimate of when will this happen, as in how high up in the list is it? Would be great to have this feature!

**Comment by jhwangbo** [comment]
I'll finish it by the end of this week

**Comment by ashish-kmr** [comment]
Following up to see if there is an update on this. Thanks!

**Comment by jhwangbo** [comment]
I was stuck because there are big differences in how we set up the world. Do you need to create the world or just the robot? I think it will be much easier if I just use the mujoco xml as a robot definition.

**Comment by ashishkumar1993** [comment]
I just need to load the cassie xml robot file.

**Comment by jhwangbo** [comment]
is that XML file public?

**Comment by ashishkumar1993** [comment]
https://github.com/osudrl/cassie-mujoco-sim/blob/master/model/cassie.xml

**Comment by jhwangbo** [comment]
great, this will help

**Comment by jhwangbo** [comment]
just an update on this
![Screenshot from 2021-05-09 12-14-31](https://user-images.githubusercontent.com/3340750/117559427-21127800-b0c0-11eb-8d8f-1d3bb214eb3f.png)
My first implementation is done. I still have to test it with more models and debug it.

**Comment by ashish-kmr** [comment]
Thank you!

Although there is a urdf for cassie as well, it does not support passive joints, like XML in mujoco does. Joints q5 and q6 of each leg is passive and not actuated. This is the primary reason which is forcing me to switch to XML.

**Comment by jhwangbo** [comment]
What is a passive joint? Is that a kinematic loop or unactuated joint?

**Comment by ashish-kmr** [comment]
Eq. 3 of [this paper](https://web.eecs.umich.edu/faculty/grizzle/papers/Feedback_Control_of_a_Cassie_Bipedal_Robot__Standing_and_Walking_Final.pdf) describes it. pasting it here for convenience:

"The joints (q1, q2, q3, q4, q7) are actuated. The joints (q5, q6) are passive, being formed by the introduction of (rather stiff) springs. When the springs are uncompressed, q5 = 0, and q6 = −q4 + 13°"

**Comment by YandongJi** [comment]
> just an update on this
> ![Screenshot from 2021-05-09 12-14-31](https://user-images.githubusercontent.com/3340750/117559427-21127800-b0c0-11eb-8d8f-1d3bb214eb3f.png)
> My first implementation is done. I still have to test it with more models and debug it.

Has this implementation pushed to the repo? I'm trying this. :)

**Comment by jhwangbo** [comment]
I pushed the feature. It is very first time offering this feature so I probably have to iterate it multiple times. let me know how it works for you

**Comment by ashish-kmr** [comment]
Thanks! 

The latest push contains absolute paths [here](https://github.com/raisimTech/raisimLib/blob/4dc3409d55d4db0de35473164741b613d8f04aac/raisim/linux/lib/cmake/raisim/raisim-targets.cmake#L64) and [here](https://github.com/raisimTech/raisimLib/blob/4dc3409d55d4db0de35473164741b613d8f04aac/raisim/linux/lib/cmake/raisim/raisim-targets-release.cmake#L21). This is causing cmake to fail.

**Comment by ashish-kmr** [comment]
The mjcf examples load the xml file as an argument while constructing the ```raisim::World```. I'm presently using raisimGymTorch, in which the ```Environment.hpp``` loads an articulated object with 
```addArticulatedSystem(resourceDir_+"/anymal/urdf/anymal.urdf");```. Is there an equivalent call to load an xml file inside the Environment.hpp? I was looking through the api couldn't find it.

**Comment by jhwangbo** [comment]
hard coded path + raisim unity opengl issues fixed. I moved the world instantiation to the environment class constructor. You can provide the XML file when you create the world.

**Comment by ashish-kmr** [comment]
Thanks! I tried the updated version and here is where Im stuck -- Cassie has 10 actuated joints whereas gcDim is 35. This is also the dimension that the ```pdTarget`` expects, but I'm not how to move the 10 actuated joints only.

**Comment by jhwangbo** [comment]
that part is not in the mjcf file. The cassie repo has many c++ files and I guess you can figure out how they simulated cassie there

**Comment by ashish-kmr** [comment]
I was looking through the cassie xml file and I found that line [230-242](https://github.com/osudrl/cassie-mujoco-sim/blob/1ab45636641a8d0404e4118273f3949f39997cd6/model/cassie.xml#L230) list the actuators, and line [244-267](https://github.com/osudrl/cassie-mujoco-sim/blob/1ab45636641a8d0404e4118273f3949f39997cd6/model/cassie.xml#L244)  list the sensors. Although, I'm not sure how easy/hard it is to incorporate this in the codebase.

**Comment by jhwangbo** [comment]
RaiSim does not have a concept of actuators and sensors. You can always set the torques for all joints and sense the positions of all joints. For the cassie model, the spring is not connected in the xml. I am not sure how they handle this.

**Comment by ashish-kmr** [comment]
Mujoco handles this through constraints written in Lines (223- 228)[https://github.com/osudrl/cassie-mujoco-sim/blob/1ab45636641a8d0404e4118273f3949f39997cd6/model/cassie.xml#L223]. Instead of an actual spring, they enforce these constraints which mimic a very stiff spring.

**Comment by jhwangbo** [comment]
Currently, constraints live in World, not in an articulated system. Let me think about how to implement this nicely...

**Comment by YandongJi** [comment]
Thank you again for your work! But it seems that cassie's model is still not working.

**Comment by jhwangbo** [comment]
I will push it with the next version. This is not just reading the MJCF file. I need to integrate equality constraints to ArticulatedSystem.

**Comment by christsa** [comment]
Hi

The mjcf-file reader seems to put all frames except for the root at the same location (see attached image). I've tested it across different files and it occurs with all of them.

![mjcf_reader](https://user-images.githubusercontent.com/32132810/124734425-64009880-df15-11eb-9ef6-9b4bc2b8053a.png)

**Comment by jhwangbo** [comment]
@christsa I already fixed this issue and will be included in the next push.

**Comment by jhwangbo** [comment]
I also added equality constraints for mjcf files. It is not well tested so let me know how it performs.
