### ISSUE TITLE
How to use getAngularMomentum() correctly?

### ISSUE THREAD

**Issue by Penguuuuin** [raisimTech/raisimLib#431]
I need to calculate the angular momentum of a walking humanoid robot and find out the function getAngularMomentum(), but it seems doesn't get a reasonable result when I directly call it like this:
![code2](https://user-images.githubusercontent.com/60479186/218738714-ad1d33f3-56f3-4380-b35a-a169dbf71d9e.png)
and the pic of angular momentum data gathered like this. The value of the data fluctuates and increases and it's impossible for a stable walking robot.
![ang_no_mat](https://user-images.githubusercontent.com/60479186/218743415-bf14cec0-575e-45c6-aed1-f1172d41ded2.png)

Then I find that if calls getMassMatrix() before getAngularMomentum(), the gathered data become reasonable.
![code](https://user-images.githubusercontent.com/60479186/218737760-263b8c6b-78ca-4f7b-80d2-0f4f1a22ec89.png)
![ang_with_mat](https://user-images.githubusercontent.com/60479186/218745544-8bb5a4d6-c982-4bff-8f5b-785539c91724.png)

Why it happens? Is getMassMatrix() calls other function to update any internal value? Or if I need to call any other functions such as updateMassInfo() to manually update something?

**Comment by jhwangbo** [comment]
This seems like a bug introduced after v1.1. There was a big change in the computation pipeline and probably some variables needed to compute the angular momentum are not computed. I'll push a fix to this soon

**Comment by Penguuuuin** [comment]
Thanks for you prompt reply! So do I calculate angular momentum right?

**Comment by jhwangbo** [comment]
Yes, that looks correct. The angular momentum function is unit-tested (but only after the massMatrix call)
