### ISSUE TITLE
How make `catkin build`, that I can run raisim through command `roslaunch raisim unity.launch`?

### ISSUE THREAD

**Issue by dvogureckiy99** [raisimTech/raisimLib#434]
How make `catkin build`, that I can run raisim through command?
```
# unity
roslaunch raisim unity.launch
# opengl
roslaunch raisim opengl.launch
```

**Comment by jhwangbo** [comment]
raisim visualizers are not ROS executable. I don't use launcher file but I guess you can run any executable in that script
