### ISSUE TITLE
getGeneralizedForce() Implementation

### ISSUE THREAD

**Issue by hyJung0215** [raisimTech/raisimLib#436]
Hi! I am trying to get torque information by calling function getGeneralizedForce(). 
However, in the function implementation, it uses posErr_ variable which is not initialized(or it is implicitly initialized to zero). 
Is this variable initialized and assigned its value somewhere else? or Are we assuming that positional error is zero(which means joint pose is well tracked)?
![image](https://user-images.githubusercontent.com/52847647/220508958-4505ad71-8bda-4f86-94db-06b4164f3de9.png)

Thanks!

**Comment by jhwangbo** [comment]
``posErr_`` is computed after integration step. You can get the generalized force only for the previous integration step

**Comment by jhwangbo** [comment]
Please copy paste the code and not upload the image
