### ISSUE TITLE
heightMap: how to modify it during the training

### ISSUE THREAD

**Issue by JcSack** [raisimTech/raisimLib#438]
Hello I have 2 question.

As first, I am trying to add an height map in my environment using raw data. I am trying with:
```
std::vector<double> height = {1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0.5, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1};
auto heightMap = world.addHeightMap(5, 5, 10, 10, 0, 0, height);
```
But I have no idea how the set the weights on height in order to shape the heightmap.

It's then possible to modify the parameter of the heightMap during the training? I wanted to add this part of code in a function which is called at the end of each episode, but I'm afraid that it instantiate a lot of heightMap one over the other.

**Comment by jhwangbo** [comment]
What are the "weights on height"? Do you mean the height of the grid points?

Did you check this example?
https://github.com/raisimTech/raisimLib/blob/master/examples/src/server/dynamicHeightMapUnrealOnly.cpp

This only works on RaisimUnreal.

**Comment by JcSack** [comment]
Yes, with weights I meant the number in the vector of height. There is something that I could read to figure out a way to set them properly in order to make the terrain I want? 

About that example, I am not sure is what I want because I read in the documentation that for the training is better to use raisimUnity

**Comment by jhwangbo** [comment]
You can use RaisimUnreal to visualize time-to-time. You don't have to keep it on for the whole training session. Besides, I think the mobile version raisimUnreal is as fast as raisimUnity.

**Comment by jhwangbo** [comment]
You can also use a tester file to visualize the trained policy after training. An example is in raisimGymTorch
