### ISSUE TITLE
Will simulation for deformable terrain available for RaiSim?

### ISSUE THREAD

**Issue by JewelryForge** [raisimTech/raisimLib#439]
Professor, I have read your recent publication on Science Robotics and I really appreciate your simplification and improvement on deformable terrain reaction. Would you mind telling me whether it will be a part of RaiSim in the future? Thanks for reply.

**Comment by jhwangbo** [comment]
no, unfortunately, this will require a huge change in raisim computation pipeline. It will be a nice feature but it's not in my urgent TODO list.
