### ISSUE TITLE
Error in file (urdf) import

### ISSUE THREAD

**Issue by LDL-SER** [raisimTech/raisimLib#44]
![0D124BB4D3EE2A29AFD46D6E1D192E01](https://user-images.githubusercontent.com/56706049/106387074-feaef580-6412-11eb-8321-7c313cb1f026.jpg)

I exported the Soildword model as an URDF file through the sw_urdf_exporter plug-in. Error when running: Mesh collision bodies must be in an obj format .

This is the exported file :[bouncing_balance_car.SLDASM.zip](https://github.com/raisimTech/raisimLib/files/5899932/bouncing_balance_car.SLDASM.zip)

I don't know if this export way will work with Raisim or if it needs to be modified to use it . This URDF file can be used in V-Rep, but not in Raisim.

I really hope to get your advice and help me solve the problem . Thank you very much .

**Comment by jhwangbo** [comment]
The error is somewhat clear. You have to manually convert the mesh files to the obj format if you want to use them as collision bodies. We don't support other formats because it is so painful to write a parser for mesh files.

In general, it is not advised to use mesh files as collision bodies. For fast simulation, you have to approximate them to primitive types.

**Comment by Abedcoder** [comment]
> The error is somewhat clear. You have to manually convert the mesh files to the obj format if you want to use them as collision bodies. We don't support other formats because it is so painful to write a parser for mesh files.
> 
> In general, it is not advised to use mesh files as collision bodies. For fast simulation, you have to approximate them to primitive types.

hi, I met same error, and i obeied your instruction to convert .stl to .obj files, but it didn't work, still same error info. 

And I've tried to replace Unitree a1's .stl with my own .stl, it worked in RaiSimUnity.

After that, I tried to delete every .stl and .obj files in /build/examples/myQuadruped/mesh/ and /rsc/myQuadruped/mesh/ directories, but something weird happened, it still gived me `Mesh collision bodies nust be in an obj format` error info, not infos that illustrated files not existed. 

So it seems the .urdf's falut, not the .stl file, and I really need your help , I've tried my best :(

**Comment by jhwangbo** [comment]
Can you share the model files? I will run it and check

**Comment by Abedcoder** [comment]
[myRobotModifiedFiles_20220114.zip](https://github.com/raisimTech/raisimLib/files/7867720/myRobotModifiedFiles_20220114.zip)
Of course! this is my modified files, including .stl .obj . cpp .urdf cmakelist files. thank you for your reply!!

**Comment by jhwangbo** [comment]
Your URDF is referencing STL files. You should reference obj files in the URDF
