### ISSUE TITLE
Getting the correct contact Jacobian for forward dynamics calculations

### ISSUE THREAD

**Issue by Kukhokuhle** [raisimTech/raisimLib#444]
Hi all

This may be a trivial question.

When solving for full rigid body forward dynamics M(q)*d/dt(dq/dt) + C(q, dq/dt) = S^T*tau + J^T*f in raisim, how does one get the correct contact jacobian, J, in the equation? I have tried J = robot->getSparseJacobian(contact index, raisim::ArticulatedSystem::Frame::WORLD_FRAME, contact.getPosition(), positionalJacobian) (for the positional jacobian and used getSparseRotationalJacobian() for the rotational part) but without success.

Any help would be appreciated.

**Comment by jhwangbo** [comment]
You don't need the sparse rotational jacobian because there is no contact moment in Raisim.
You are almost right but the first argument should be the body index (which you can retrieve from getLocalIndex())

**Comment by Kukhokuhle** [comment]
Thank you. 

1. I was not aware the contact moment is not necessary in Raisim. How is its effect handled then?
2. Do you mean I should use: body_index = contact.getlocalBodyIndex(); as the 1st argument in getSparseJacobian()? That is what I thought, but I am realising that I am getting better results (better matching Raisim's forward dynamics) when I use body_index = 0 i.e. the floating base as the body. Does this make any sense?

**Comment by Kukhokuhle** [comment]
Never mind. This has been solved. Thank you!
