### ISSUE TITLE
Get depth/RGB data from the added Realsense sensor

### ISSUE THREAD

**Issue by itaouil** [raisimTech/raisimLib#448]
Hi,

I read the small excerpt on the Raisim documentation about adding sensors to the URDF file, and I also saw that you added the sensor implementations in raisimUnreal #329.

My question is how can I access the RGB and depth data coming from the sensor?

Thanks,
Ilyass

**Comment by jhwangbo** [comment]
`DepthSensor::getDepthArray` and `RGBSensor::getImageBuffer` are the functions that you are looking for.

**Comment by itaouil** [comment]
Thanks for the quick response.

One last question....

Is there also a way to visualize the RGB and depth images or maybe I should do something extra to have them visible on raisimUnreal?

Because as you can see from the picture below the windows are completely black

![Screenshot from 2023-04-13 13-38-42](https://user-images.githubusercontent.com/17275225/231747617-c1c54665-818d-4c38-a585-120d3d8cb889.png)

**Comment by jhwangbo** [comment]
how about the raisim example `sensors`? Do you also see black images only?

**Comment by itaouil** [comment]
In the example I can see the sensory output.

I guess I am doing something wrong on my side on the URDF.

**Comment by jhwangbo** [comment]
If you click the checkbox, it should show the frame. From your picture, I don't see any sensor frame.

**Comment by itaouil** [comment]
Solved.

I had to pay attention to which version of Python I was compiling with, and also I did not realize I had to call these two functions inside the code:

```
auto depthSensor = robot->getSensor<raisim::DepthCamera>("depth_camera_front_camera_parent:depth");
depthSensor->setMeasurementSource(raisim::Sensor::MeasurementSource::VISUALIZER);
auto rgbCamera = robot->getSensor<raisim::RGBCamera>("depth_camera_front_camera_parent:color");
rgbCamera->setMeasurementSource(raisim::Sensor::MeasurementSource::VISUALIZER);
```

Thanks.

**Comment by wzjscut** [comment]
> how about the raisim example `sensors`? Do you also see black images only?

I use the API RGBSensor::getImageBuffer in the raisim example sensors. But i also get the completely back image with all the pixel is 0. What is the problem?
