### ISSUE TITLE
wire with custom force generation

### ISSUE THREAD

**Issue by skoo1** [raisimTech/raisimLib#45]
I can see that there are StiffLengthConstraint and CompliantLengthConstraint in the library.
Both of them have fixed parameters and their forces are calculated from the fixed parameters. 
I am wondering if you can make a wire whose force is computed by a custom function so that we can control the force depending on dynamic conditions? It would be nice for me in making a human ligament structures in the joints. 
-SK

**Comment by jhwangbo** [comment]
I pushed an `addCustomWire()` method. Doc is here https://raisim.com/sections/CustomLengthConstraint.html
