### ISSUE TITLE
Small typo in Contact and Collision API

### ISSUE THREAD

**Issue by joey156** [raisimTech/raisimLib#457]
Hi,

Not sure where to put this, but I think there is a typo in the Contact and Collision API on the RaiSim documentation site.

Under https://raisim.com/sections/Contact.html#_CPPv4NK6raisim7Contact10getImpulseEv it states that the function "returns the impulse. You have to **multiply** this number by the time step to get the force". To find the force you should be **dividing** the output of getImpulse() by the time step, rather than multiplying it.

**Comment by jhwangbo** [comment]
thx for the feedback. The typo is fixed
