### ISSUE TITLE
Get contact force between objects

### ISSUE THREAD

**Issue by RobertoRoos** [raisimTech/raisimLib#46]
I'm trying to find the contact force between two objects. 

The docs sample is already very helpful:

```
for(auto& contact: anymal->getContacts()) {
    if (contact.skip()) continue;

    std::cout << "Contact impulse in the world frame: " <<contact.getContactFrame().e() * contact.getImpulse()->e() << std::endl;
}
```

But the contact magnitude is as impulse. I'm not familiar with this, but a quick search shows this is probably part of [impulse based contact](https://en.wikipedia.org/wiki/Collision_response#Impulse-based_contact_model). Is there an easy way to convert this to a contact force in Newtons?

I'm guessing we need to define by some amount of time. Is this the simulation timestep?

**Comment by jhwangbo** [comment]
yes. You can get it from `World::getTimeStep()`
