### ISSUE TITLE
Issues understanding Enviroment.hpp

### ISSUE THREAD

**Issue by kuenem** [raisimTech/raisimLib#460]
Is there any good tutorial or instruction about how to work with RaiSimGymTorch?
I have managed to change the anymal robot with my robot but I am struggeling to get the robot to learn the things I want.
And I didn't found out yet where I can learn to work with it.

**Comment by jhwangbo** [comment]
I guess you are not asking how to work with RaisimGymTorch. RaisimGymTorch is just a framework. It doesn't make the robot learn the thing you want. You have to code it yourself.
RL coding and debugging takes long time to learn. You just have to try it many times and get experience.
