### ISSUE TITLE
ModuleNotFoundError: No module named 'raisimpy'

### ISSUE THREAD

**Issue by kuenem** [raisimTech/raisimLib#461]
RaiSim worked perfectly fine for me until today. I get the error ```ModuleNotFoundError: No module named 'raisimpy'``` when I run my Test file or one of your examples. When I try to run the runner.py file from RaiSimGymTorch which also worked perfectly fine I get the error ```ModuleNotFoundError: No module named 'raisimGymTorch.env'```.
I changed nothing in raisim and didn't used my Laptop at all since it worked yesterday.

**Comment by jhwangbo** [comment]
which test file? one of the RaisimPy examples?
All the behaviors seem like that your python environment is broken. I cannot tell why from what you wrote.
