### ISSUE TITLE
Can we change the coefficient of joint friction in c++ ?

### ISSUE THREAD

**Issue by romansabaek** [raisimTech/raisimLib#462]
Hi,
Can we change the coefficient of "joint friction and damping" in c++?
In the link below, I saw Raisim provides the function to change the 'rotorinertia'. But I am curious if we can set the joint stiffness and damping parameter in c++.

FYI: link (https://raisim.com/sections/ArticulatedSystem.html)

**Comment by jhwangbo** [comment]
``getSprings`` will return nonconst ref and you can change it in anyway you want. You can use ``setJointDamping`` to set the joint damping. 

Joint friction is not implemented in Raisim now. It creates discontinuous maping which can make the system vibrating. I am still investigating the best way to do this.
