### ISSUE TITLE
[RaisimServer.hpp:800]"Version mismatch. Make sure you have the correct visualizer version"

### ISSUE THREAD

**Issue by lihaoming45** [raisimTech/raisimLib#464]
When I click the "RaiSimUnity.exe" app in win32 folder, and then run the "heightMap.py", the terminal console reports the error as follows: "aisimServer.hpp:844] Version mismatch. Make sure you have the correct visualizer version"
![image](https://github.com/raisimTech/raisimLib/assets/44568126/42903a31-ab1d-4604-8abc-b5fd27780eeb)

**Comment by jhwangbo** [comment]
Our raisimPy packages are outdated. You have to build them yourself. Pass ``-DRAISIM_PY=ON`` to CMAKE and install the raisim library. It will install raisimPy file to your python environment.

**Comment by lihaoming45** [comment]
Thank you for the reply. I have already set the -DRAISIM_PY=ON in CMAKE command， and generated the following file:"raisimpy.cp38-win_amd64.pyd" at the folder "raisim\win32\bin\Release", but the problem still exists, I think there may be some trick ignored
![image](https://github.com/raisimTech/raisimLib/assets/44568126/7e74360a-ed7c-4849-a5e8-1f5d4441a631)

![image](https://github.com/raisimTech/raisimLib/assets/44568126/309a1ed9-92d5-42cc-9950-43909eae51b0)

**Comment by lihaoming45** [comment]
> Please do not paste an image. Image is not searchable

Thank you so much, The problem has been solved, I tried to copy the "raisimpy .lib" to the "libs" folder of the python environment and the "raisimpy.cp38-win_amd64.pyd" to the site-packages, then I copy the whole folder of of raisim/win32  (including bin, lib, include) to the "Library" folder. Finally the problem solved!

**Comment by lihaoming45** [comment]
> Please do not paste an image. Image is not searchable

Thank you so much, The problem has been solved, I tried to copy the "raisimpy .lib" to the "libs" folder of the python environment and the "raisimpy.cp38-win_amd64.pyd" to the site-packages, then I copy the whole folder of of raisim/win32 (including bin, lib, include) to the "Library" folder. Finally, the problem is solved!
