### ISSUE TITLE
How to import urdf-kind map to RaiSim

### ISSUE THREAD

**Issue by Czworldy** [raisimTech/raisimLib#478]
Hi, there!
I'm try to import map in this repo [ICRA2023_Quadruped_Competition](https://github.com/rise-lab-skku/ICRA2023_Quadruped_Robot_Challenges/tree/main) but i can not find correct API in `RaiSim::World`. So how should use those urdf-kind terrain in RaiSim?
Thanks a lot!

**Comment by jhwangbo** [comment]
Can you just load it as an articulated system?

**Comment by jhwangbo** [comment]
I saw other group loading this map in Raisim. I think they used ``addArticulatedSystem`` method

**Comment by Czworldy** [comment]
Thanks for your reply.
but when i load this map by `addArticulatedSystem` i only get `segmentation fault`

here is my code

```
#include "raisim/RaisimServer.hpp"

int main(int argc, char* argv[]) {
  auto binaryPath = raisim::Path::setFromArgv(argv[0]);
  raisim::World::setActivationKey(binaryPath.getDirectory() + "\\rsc\\activation.raisim");
  raisim::RaiSimMsg::setFatalCallback([](){throw;});

  /// create raisim world
  raisim::World world;
  world.setTimeStep(0.001);

  /// create objects
  auto ground = world.addGround(0, "gnd");
  ground->setAppearance("hidden");

  auto map = world.addArticulatedSystem("PATH_TO_WHERE_YOU_CLONE_MAP/ICRA2023_Quadruped_Robot_Challenges/urdf/map.urdf");

  /// launch raisim server
  raisim::RaisimServer server(&world);
  server.launchServer();

  for (int i=0; i<200000000; i++) {
    RS_TIMED_LOOP(int(world.getTimeStep()*1e6))
    server.integrateWorldThreadSafe();
  }

  server.killServer();
}
```

the raisim version is 1.1.7.
Am i correct or there are some steps i missed?

**Comment by jhwangbo** [comment]
Currently 0-dof articulated systems are not supported. You have to load the mesh (defined inside the URDF) and set it to static by ``setBodyType``.

**Comment by Czworldy** [comment]
i see, load the mesh meams load the *.dae inside the URDF, isn't it?
