### ISSUE TITLE
How to use Actuator Network in Raisim?

### ISSUE THREAD

**Issue by romansabaek** [raisimTech/raisimLib#480]
Hi,
I already implemented an actuator network by referring Jemin's science robotics paper.
The actuator network takes robot's position and velocity states and can estimate the actual torque properly.

But, I am wondering what is the efficient way to import this pretrained model in Raisim simulator.
Since the model is implemented with Python and Raisim environment is developed with c++, it seems like there is some compatibility issue.

Do we have to use "torchscript" to import the pretrained actuator model in Raisim?
Do you have some recommendation for it?
I highly appreciate your help and advice.

Thanks!

**Comment by jhwangbo** [comment]
sorry for my late response. The way is to implement the network in C++ yourself using Eigen. if you use torch functions, it will be very slow
