### ISSUE TITLE
raisim예제로봇 그래픽이 켜지지 않는 상황입니다.

### ISSUE THREAD

**Issue by ChoHyunjun1** [raisimTech/raisimLib#492]
안녕하세요. 특별히 error가 발생하는 것이 아니고, raisim에서 auto-connect 를 하게되면 raisimunity에서

 System.Exception: Cannot find mesh from resource directories = meshes/trunk.dae
 at raisimUnity. RsObject.Processvisuals (raisimUnity.RsUnityRemote parent, System.Boolean initialized, System.Boolean isInstanced, system.Int32 count) [0x003d2] in <0ecfe892ac504810a37771903b57c35a>:0

라는 문구가 뜨며, visual studio에서는 아래와 같이

[2023:07:14:15:05:03 RaisimServer.hpp:228] Connection to 876 is established
[2023:07:14:15:05:05 RaisimServer.hpp:228] Connection to 880 is established
[2023:07:14:15:05:06 RaisimServer.hpp:228] Connection to 884 is established

이렇게 계속 연결이 바뀝니다.

**Comment by jhwangbo** [comment]
Please write in English so that others can benefit from your post.

Which example did you run? what's your computer?

**Comment by ChoHyunjun1** [comment]
I runed aliengo and my computer is a laptop.

**Comment by jhwangbo** [comment]
which os?

**Comment by ChoHyunjun1** [comment]
window

**Comment by jhwangbo** [comment]
can you run other examples?

**Comment by ChoHyunjun1** [comment]
tried anymal but same result.

**Comment by ChoHyunjun1** [comment]
![connection](https://github.com/raisimTech/raisimLib/assets/91465505/eb4a549f-79dd-4dc9-8701-fb3269ff595a)
![raisimunity](https://github.com/raisimTech/raisimLib/assets/91465505/18117ad7-28cf-4f3f-ac53-a575222d58ce)

**Comment by ChoHyunjun1** [comment]
this is the result what I said

**Comment by ChoHyunjun1** [comment]
but the example 'dynamicHeightMap' works fine.

**Comment by ChoHyunjun1** [comment]
cartPole works fine either. but the others doesn't work

**Comment by jhwangbo** [comment]
Do you have Korean chracters in the binary path? Or do you run this on OneDrive? Can you copy paste the directory where the executable live?

**Comment by ChoHyunjun1** [comment]
my user name is Korean.

**Comment by ChoHyunjun1** [comment]
C:\Users\조현준\raisimLib\examples\src\server

**Comment by jhwangbo** [comment]
Then please move the directory

**Comment by ChoHyunjun1** [comment]
I didn't understand what file you want

**Comment by ChoHyunjun1** [comment]
system says "we don't suppot that file type.".

**Comment by ChoHyunjun1** [comment]
I made a new user name in english and then moved all raisim file to there but the connection lost

[2023:07:14:18:34:02 RaisimServer.hpp:228] Connection to 372 is established
[2023:07:14:18:34:22 RaisimServer.hpp:811] The client failed to respond in 10 seconds. Looking for a new client
[2023:07:14:18:34:22 RaisimServer.hpp:1629] Lost connection to the client. Trying to find a new client...

**Comment by jhwangbo** [comment]
Is that ANYmal example? can you run other examples?

**Comment by ChoHyunjun1** [comment]
i decided reinstall on Linux. thanks for your response to my questions
