### ISSUE TITLE
Symbol not found in flat namespace - raisimGymTorch

### ISSUE THREAD

**Issue by santurini** [raisimTech/raisimLib#495]
**OS:** Mac OS Ventura 13.4.1

I have installed raisimGymTorch without errors, but when I try to run the _runner.py_ example I get this error:
```
Traceback (most recent call last):
  File "/Users/arturo/Desktop/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 4, in <module>
    from raisimGymTorch.env.bin.rsg_anymal import NormalSampler
ImportError: dlopen(/Users/arturo/Desktop/raisim/raisimLib/raisimGymTorch/raisimGymTorch/env/bin/rsg_anymal.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_omp_get_thread_num'
```

I also tried to install openmp using brew and update the DYLD_LIBRARY_PATH but I keep getting the same error.
I tried to compile raisim both with clang and g++ but nothing changes.

**Comment by jhwangbo** [comment]
This is about openmp. Someone recently solved the issue here #479 
let me know if that works

**Comment by santurini** [comment]
I set the compiler flags to use llvm as suggested:

```
CC=/opt/homebrew/opt/llvm/bin/clang
CXX=/opt/homebrew/opt/llvm/bin/clang++

-- The CXX compiler identification is Clang 16.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/opt/llvm/bin/clang++ - skipped
```
Everything worked fine but then I have the same error in runner.py

**Comment by santurini** [comment]
I tried to add this line in the _CMakeLists.txt_ to check which OpenMP_C_FLAGS was found:
```
message("OpenMP {${CMAKE_C_FLAGS}}")
```

And I get in return this during the compilation and the same error as before when launching the program:
```
OpenMP { }
```

These are the flags I use:
```
export CC=/opt/homebrew/Cellar/llvm/16.0.6/bin/clang
export CXX=/opt/homebrew/Cellar/llvm/16.0.6/bin/clang++
export LDFLAGS="-L/opt/homebrew/Cellar/llvm/16.0.6/lib"
export CPPFLAGS="-I/opt/homebrew/Cellar/llvm/16.0.6/include"
```
