### ISSUE TITLE
 Visual dae in raisimUnity gets a wrong orientation occasionally

### ISSUE THREAD

**Issue by JewelryForge** [raisimTech/raisimLib#497]
When I try to load [unitree go1](https://github.com/unitreerobotics/unitree_ros/tree/master/robots/go1_description) in raisim, I find the trunk dae gets a wrong orientation like this:
![Screenshot-20230718125627-580x400](https://github.com/raisimTech/raisimLib/assets/66123485/74d3a97d-1690-498c-8c97-0dd7392c6d57)
The trunk of the robot gets flipped. I tried several times but it remains the same in raisimUnity. I also tried in raisimUnreal and rviz, and they both get right orientations. I never encounter the problem on other models like anymal, unitree a1 and aliengo, etc. I have no idea if this problem comes from the model or raisimUnity.
![Screenshot-20230718125554-656x484](https://github.com/raisimTech/raisimLib/assets/66123485/34d5120a-a533-474f-b806-335692a92e6d)
![Screenshot-20230718130352-616x464](https://github.com/raisimTech/raisimLib/assets/66123485/749c0729-16bc-48b3-ba64-4e9fa859ba1e)

**Comment by jhwangbo** [comment]
Thank you for posting. I'll investigate it and fix the push

**Comment by jhwangbo** [comment]
I pushed a fix for linux and windows versions. Can you test it if tou are not using MAC?

**Comment by JewelryForge** [comment]
It's fixed. Thank you!
