### ISSUE TITLE
Spurious contact with large depth

### ISSUE THREAD

**Issue by jcarius** [raisimTech/raisimlib#5]
Hi,
I'm investigating a strange issue where sometimes collisions with a large penetration appear and disappear very quickly. I suspect this is an issue with my heightmap or the robot model, but I need a bit of help for debugging. At each iteration of my algorithm, I'm checking the current state for strange collisions and then print the following snippet:
```
std::cout << "Contact depth " << contact.getDepth() << " colliding with "
                  << world_.getObject(contact.getPairObjectIndex())->getName() << " at world position "
                  << contact.getPosition().e().transpose() << " while anymal position is at (raisim_q): " << raisim_q.transpose()
                  << " and ground height at: " << heightMap_->getHeight(contact.getPosition().e()(0), contact.getPosition().e()(1))
                  << std::endl;
```
Most of the time everything is fine, but sometimes large contact penetrations are occuring, e.g.:
```
Contact depth -0.998189 colliding with  at world position    0.488771   -0.388471 -0.00393607 while anymal position is at (raisim_q):   0.265084  -0.124508   0.554875   0.982398 0.00403822 0.00967577  -0.186507  -0.228771    0.67993  -0.946103    0.19076   0.729859  -0.906762  -0.472449  -0.581529   0.812443   0.592239  -0.600427   0.676604 and ground height at: -0.00393607
```
The state of the robot (anymal) looks fine and the collision position is where I expect the foot to be. What's striking is that the contact depth is so deep. Two questions

- Is the contact object correctly filled or is this part of the code untested?
- Why is the name of the colliding object an empty string?

**Comment by jhwangbo** [comment]
Hi,
the contact is correctly filled. The contact solver uses it. The name is an empty string unless you set name (e.g., anymal->setName("anymal"));

Where is that contact object from? is it from the object or the world? It is strange that the number is negative. This only occurs for joint limit collisions.

Can you share a minimum code that can reproduce this error?

**Comment by jhwangbo** [comment]
closing this issue for now until I get further replies
