### ISSUE TITLE
raisimgymtorch example issues

### ISSUE THREAD

**Issue by najon6** [raisimTech/raisimLib#500]
https://raisim.com/sections/RaisimGymTorch.html
I trying to do the same things in here but something didn't work.
First, I made own conda space and install pytorch from homepage by linux, conda, cuda 11.7
But if I run ' sudo python3 setup.py develop', 
  
Processing dependencies for raisim-gym-torch==1.1.7
Searching for torch
Reading https://pypi.org/simple/torch/
Downloading https://files.pythonhosted.org/packages/96/28/026dc037f177d53558477931677b120f649dd5a0dcdc4b44dc38b3d75711/torch-2.0.1-cp38-cp38-manylinux1_x86_64.whl#sha256=5ef3ea3d25441d3957348f7e99c7824d33798258a2bf5f0f0277cbcadad2e20d
is occurred in terminal.

And if I just ignore it and run 'python3 raisimGymTorch/env/envs/rsg_anymal/runner.py', 

from raisimGymTorch.env.RaisimGymVecEnv import RaisimGymVecEnv as VecEnv
ModuleNotFoundError: No module named 'raisimGymTorch'
is occurred in terminal.

Is there something I missed to do it?

**Comment by jhwangbo** [comment]
you should never type sudo in conda environment. delete the folder and the workspace and try again

**Comment by jhwangbo** [comment]
Type the exact commands you can find here: https://raisim.com/sections/RaisimGymTorch.html
Use ``python`` instead of ``python3``
