### ISSUE TITLE
Cannot get the angular velocity from Object class

### ISSUE THREAD

**Issue by edward9503** [raisimTech/raisimLib#508]
Hi @jhwangbo ,

I am using this code to get the angular velocity of the object:
`auto box = world.getObject("box");`. 

However I found that there is only linear velocity inside the Object.hpp, which I cannot get the angular velocity of the "box" object. Is there anything I can do to access the angular velocity?

Many thanks.

**Comment by jhwangbo** [comment]
Hi @edward9503 
sorry for my late response. The method is called ``raisim::SingleBodyObject::getAngularVelocity``. The ``getObject`` method will return object pointer and you have to cast it to ``SingleBodyObject``
