### ISSUE TITLE
docker raisim

### ISSUE THREAD

**Issue by nfhe** [raisimTech/raisimLib#515]
Thank you very much for your work.

I used Docker's newly created ubuntu20.04 to install raisim. After installing the official files correctly. I open raisimUnity.x86_ After 64, 

Segmentation fault (core dumped).

 I installed cmake, gcc, g++, eigen3. There were no errors during the make process, and I have already installed cuda

[4.cd ~/raisimLib
5.mkdir build
6.cd build
7.sudo apt-get install cmake
8.sudo apt-get install g++
9.sudo apt-get install gcc
10.sudo apt-get install python3-pip
11.sudo apt-get install libeigen3-dev
7.cmake .. -DCMAKE_INSTALL_PREFIX=/home/raisim_build -DRAISIM_EXAMPLE=ON -DRAISIM_PY=ON -DPYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)")

](url)

I hope to receive your reply as soon as possible. Thank you.

**Comment by jhwangbo** [comment]
did you run unity in docker? that doesn't work. You should connect the port and run the unity natively
