### ISSUE TITLE
Incorrect URDF Loading

### ISSUE THREAD

**Issue by ghost** [raisimTech/raisimLib#516]
Hi,

I am using the latest master branch raisimpy to load an URDF exported from SW. It has 6 joints and a floating base. The robot cannot be correctly loded while only part of the joints can be. 
![image](https://github.com/raisimTech/raisimLib/assets/56295370/005440d3-6db5-4669-b196-2f27a04de1cd)
![image](https://github.com/raisimTech/raisimLib/assets/56295370/0ae734e2-cce8-42f5-a2e8-692fa877abf3)
![image](https://github.com/raisimTech/raisimLib/assets/56295370/c3490047-fd19-4cf5-b3ec-41b7f7664e18)

**Comment by jhwangbo** [comment]
can you share the URDF?

**Comment by jhwangbo** [comment]
Yes, someone pointed out that the name "base_link" is reserved for a fixed-base robot. But after digging into this topic, I realized that is not true.

I'll revert this change. Until then, you can use another name for the base.

Let me know if that fixes your issue
