### ISSUE TITLE
[ME491] How much is an adequate hardware performance?

### ISSUE THREAD

**Issue by iamchoking** [raisimTech/raisimLib#519]
Hello, I just set up raisimLib according to instructions posted [here](https://raisim.com/sections/Installation.html). And ran the `rsg_anymal` RL example. I am getting the follwoing output in terminal. (everything seems to work fine):

```
----------------------------------------------------
  1661th iteration
average ll reward:                       0.8640938149
dones:                                   0.000000
time elapsed in this iteration:          0.4212
fps:                                      94961
real time factor:                           950
----------------------------------------------------
```

Is a real time factor of `950` enough to run practical RL routines? or are there potential imporvments that I could make to my setup and (or) hardware?

**Comment by jhwangbo** [comment]
This is an expected speed if you have an i7 CPU
