### ISSUE TITLE
[ME491] Unity Connection Problem (Linux)

### ISSUE THREAD

**Issue by CHO0928** [raisimTech/raisimLib#523]
I finished setting for raisimLib according to instructions in Linux, and other things are fine but only visualizing problem remained.
For the anymals in  examples,

![Screenshot from 2023-10-31 16-16-00](https://github.com/raisimTech/raisimLib/assets/146946168/3286dc5f-06a1-42ae-989f-4953297d7ba0)

And also for runner.py the iteration goes well but I can't see the robot in Unity window.

![Screenshot from 2023-10-31 16-12-18](https://github.com/raisimTech/raisimLib/assets/146946168/bcc6d59a-4c8a-4ebd-aea4-3343bf5524e7)

![Screenshot from 2023-10-31 16-13-25](https://github.com/raisimTech/raisimLib/assets/146946168/66d111b4-593f-4656-a5a4-1734314efbdd)

**Comment by kim01217** [comment]
I have same problem.

**Comment by jhwangbo** [comment]
I mentioned this issue in the install instruction on the website. Please check it

**Comment by kim01217** [comment]
@CHO0928 Did you fix it?

**Comment by CHO0928** [comment]
@kim01217 No.. :(

**Comment by kim01217** [comment]
I tried various things and the problem was solved right after I typed this command.
sudo ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/x86_64-linux-gnu/libdl.so

It's from raisim install instruction
https://raisim.com/sections/Installation.html

let me know if it doesn't work.

**Comment by CHO0928** [comment]
@kim01217 Oh, now it works. Thank you so much. I didn't know where the install instruction is... ^^
