### ISSUE TITLE
[ME491] Cannot find mesh from resource directories

### ISSUE THREAD

**Issue by injoonH** [raisimTech/raisimLib#524]
I am using macOS Ventura 13.1 with Apple M1 chip to launch `/raisimUnity/m1/RaiSimUnity.app`.

I am using docker on the server with
- x86_64
- Ubuntu 20.04
- Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

Docker image is 22.04 and I use SSH local forwarding to connect and display the visualization.

However, though the connection was established, following error occurs every 200 iterations:

```bash
System.Exception: Cannot find mesh from resource directories = ../meshes/anymal_base.dae
```

<img width="711" alt="Cannot find mesh from resource directories" src="https://github.com/raisimTech/raisimLib/assets/50509417/56efb5de-fac6-4c34-ba3f-fbd6629f63a9">

**Comment by injoonH** [comment]
I found `anymal_base.dae` file in the directory `/rsc/anymal/meshes`.
I created a symbolic link for the directory and the problem was solved.

**Comment by Nickisdope** [comment]
Hi, I have encountered the same problem while running the simulation from server and try to visualize from local. 

Can you elaborate a little bit how you create the symbolic link to make it work? 

Is this issue because the visualizer try to load from the path at the remote server but what it actually need is the path of the local machine?

**Comment by injoonH** [comment]
The issue occurred because there was no directory named `meshes` in the `raisimUnity` directory.
You can create a symbolic link by running the following commands:

```sh
cd raisimUnity
ln -s ../rsc/anymal/meshes meshes
```

**Comment by injoonH** [comment]
@Nickisdope
The issue occurred because there was no directory named `meshes` in the `raisimUnity` directory.
You can create a symbolic link by running the following commands:

```sh
cd raisimUnity
ln -s ../rsc/anymal/meshes meshes
```
