### ISSUE TITLE
why  v1.1.7 is lost?  I want to get the IMU function.  Looking for your reply,thanks

### ISSUE THREAD

**Issue by geekflyfly** [raisimTech/raisimLib#531]
why  v1.1.7 is lost?  I want to get the IMU function. Looking for your reply,thanks

**Comment by jhwangbo** [comment]
Do you mean that IMU function is lost in v1.1.7? As far as I see, it's there.

**Comment by geekflyfly** [comment]
I mean why the version v1.1.7 is lost?  I want to experience the latest version because of the excellent performance of your software.  Thanks!


 ![Snipaste_2023-12-22_09-34-03](https://github.com/raisimTech/raisimLib/assets/58647939/6be31e79-bbb1-433d-a0a0-fbb31a160945)

**Comment by jhwangbo** [comment]
Somehow it was deleted. I fixed a few issues and tagged it v1.1.7. Thank you for pointing it out
