### ISSUE TITLE
Camera Api

### ISSUE THREAD

**Issue by RudeGoose** [raisimTech/raisimLib#533]
Raisim is an excellent simulator for DL. Now I want to add a camera to simulate the vision input of qual robot. Is it possible to add a camera in RaisimUnity or RaisimUnreal. I didn't find its api in doc.

**Comment by jhwangbo** [comment]
did you check ``sensors.cpp``? The API is in the server class.

**Comment by RudeGoose** [comment]
Thank you for your answer! I have seen the file. I mean that I tried to get the image buffer from camera but always got a empty vector. I checked the function ``getImageBuffer()`` and the funtion is commented with "*It is updated only if the measurement source is the visualizer and raisimUnreal is used*". Does it means the buffer can only be obtained in Unreal and Unity is not supported?

**Comment by RudeGoose** [comment]
So stupid I am! I have tested in Unreal and get the image sucessfully!
