### ISSUE TITLE
How to set body type?

### ISSUE THREAD

**Issue by Lu-Sijie** [raisimTech/raisimLib#534]
I'm using Raisim to simulate a manipulator, but I don't know how to set the “base_link” body type to raisim::BodyType::STATIC. I know there is a function "setBodyType(BodyType type)" and find the example using it.
![捕获](https://github.com/raisimTech/raisimLib/assets/56472386/c559b787-ed8d-4099-b95e-3601ec15c30a)
Now I can only get the body type of “base_link” body, whose index is 0, but can't set it:
![捕获2](https://github.com/raisimTech/raisimLib/assets/56472386/54b8b905-24e8-45f0-bb00-8cddb0eb85d3)
Best wishes!

**Comment by jhwangbo** [comment]
No, you cannot change a floating-base robot to fixed-base robot. Please check the included URDF to learn how to define a fixed-base robot (e.g., kinova arm URDF)

**Comment by Lu-Sijie** [comment]
Thank you for your reply, I found the solution by referring to the file "kinova.urdf".
