### ISSUE TITLE
After running raisimUnity.x86_64, the visual interface cannot be seen in the docker container.

### ISSUE THREAD

**Issue by Lihongjie-123** [raisimTech/raisimLib#535]
Hello, I created a Docker container with Ubuntu 20.04 on an Ubuntu server. I installed the TigerVNC service within the container. After compiling and installing raisimlib, when I run the raisimUnity.x86_64 command, I cannot see the simulation environment window on the VNC desktop. Could you please help me understand the reason? The DISPLAY environment variable is already set to :1.

**Comment by Lihongjie-123** [comment]
It seems that there is an error when running raisimUnity.x86_64 after executing "export DISPLAY=:1!".
The error message is: "Xlib: extension 'RANDR' missing on display ':1'."

**Comment by jhwangbo** [comment]
You should run the raisimUnity natively. I also have no idea how to run it on docker.
