### ISSUE TITLE
Run raisimUnity crash

### ISSUE THREAD

**Issue by Senwei-Huang** [raisimTech/raisimLib#536]
I followed the tutorial, and after installing everything correctly, when I execute the raisimUnity.x86_64 file, it shows a segmentation fault (core dumped) error and then crashes. Can you give me some advice on how to solve this problem?
The terminal printing information is:
```
xxx@xxx:~/raisim_workspace/raisimUnity1.13/linux$ ./raisimUnity.x86_64
Set current directory to /home/senweihuang/raisim_workspace/raisimUnity1.13/linux
Found path: /home/senweihuang/raisim_workspace/raisimUnity1.13/linux/raisimUnity.x86_64
segmentation fault (core dumped)
```
RaiSim1.1.5
ubuntu20.04

**Comment by Senwei-Huang** [comment]
I have solved this problem. It's a problem with the graphics card driver, you need to install a driver that is compatible with your own graphics card. Cannot use the default open-source graphics card driver nouveau when installing the Ubuntu system.

**Comment by stevenwman** [comment]
> I have solved this problem. It's a problem with the graphics card driver, you need to install a driver that is compatible with your own graphics card. Cannot use the default open-source graphics card driver nouveau when installing the Ubuntu system.

how did you change the graphics driver selection? I have the most recent nvidia-driver when I type `nvidia-smi` in my WSL terminal.

**Comment by jhwangbo** [comment]
So many people have issues with WSL+graphics. I haven't tried it myself and I don't know how it works...
