### ISSUE TITLE
Illegal Instructions in Ubuntu 20.04 Virtual Machine

### ISSUE THREAD

**Issue by mstoelzle** [raisimTech/raisimLib#54]
I had the raisimLib (together with the raisimOgre) installation working with a clone from January. Now, I pulled the most recent version, installed everything from scratch and I get the following error as soon as I import `raisimpy` (without doing anything else):
```bash
python -c "import raisimpy as raisim"
```

Then I get the following error:
```
Illegal instruction (core dumped)
```

I have a very recent CPU (and the raisimLib is running on the same system natively on macOS) and I check if the _avx_ and _avx2_ instructions are available in the Virtual Machine as well:
```bash
more /proc/cpuinfo | grep flags
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave **avx** f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 **avx2** smep bmi2 invpcid rdseed adx smap clflushopt xsaveopt xsavec dtherm arat pln pts
```

**Comment by jhwangbo** [comment]
Yes, I am aware of the bug. The best way to fix this now is to pull the latest one and build raisimPy yourself. If that doesn't work, let me know. I can fix the binaries next week.

**Comment by jhwangbo** [comment]
I am closing this issue assuming that it worked. Let me know if your problem is not solved yet

**Comment by mstoelzle** [comment]
Thanks a lot. Yes, after pulling the latest version yesterday, it worked again

**Comment by RobertoRoos** [comment]
To add to this (sorry if it's a bit far fetched), I had the same error in VirtualBox VM on Windows host. The AVX and AVX2 flags inside the VM were missing (see #94). Turns out that WSL2 (Windows Subsystem for Linux) broke parts of VirtualBox. Removing WSL2 (the "Windows Hypervisor Platform" feature) restored VirtualBox and in turn fixed my Raisim installation.
