### ISSUE TITLE
Does Raisim have the implementation of the FEE Soil Model?

### ISSUE THREAD

**Issue by Huzaifg** [raisimTech/raisimLib#548]
I am reading this paper https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/557541/RA_L_IROS_2022_Camera_Ready_RA_L.pdf?sequence=1 which uses raisim.

I was wondering where I can find the implementation of the FEE Soil Model as mentioned in the paper

Thanks!

**Comment by jhwangbo** [comment]
I also dont know. That model is not part of Raisim

**Comment by Huzaifg** [comment]
I see. Thanks for your reply!
