### ISSUE TITLE
Weird behaviour of raisim::world::rayTest

### ISSUE THREAD

**Issue by mstoelzle** [raisimTech/raisimLib#56]
@jhwangbo I experienced some weird behaviour for some cases when using the `raisim::world::rayTest` method for my raycasting. In this example I am raycasting from a vantage point one meter above ground in the center of the grid. In the first screenshot you can see the result I received with the code build on raisim. In the second screenshot you can see the result I would expect to see (the elevation of the rectangle in the upper-left is at 10m and the rest of the ground is flat at 0m) and which I received after writing my own `rayTest` code. I am not sure, maybe I used parameters for the `raisim::world::rayTest` method which failed in some edge-cases, but it was hard for me to debug without seeing the source code.

Result of raycasting using `raisim::world::rayTest` (https://github.com/mstoelzle/grid-map-raycasting/blob/raisim/src/main.cpp):
<img width="1036" alt="Screenshot 2021-02-12 at 16 04 29" src="https://user-images.githubusercontent.com/2360366/107819289-330ea400-6d79-11eb-9529-1c9baa77ca2d.png">

Result of raycasting using my own rayTest code (https://github.com/mstoelzle/grid-map-raycasting/blob/master/src/main.cpp):
<img width="909" alt="Screenshot 2021-02-12 at 21 22 31" src="https://user-images.githubusercontent.com/2360366/107819540-a31d2a00-6d79-11eb-9b0a-1ddfc5620ee7.png">

**Comment by jhwangbo** [comment]
Can you share the raisimUnity screenshot as well?

**Comment by mstoelzle** [comment]
<img width="1269" alt="Screenshot 2021-02-14 at 20 29 26" src="https://user-images.githubusercontent.com/2360366/107886995-65e4a380-6f03-11eb-95d4-772a3a53daf7.png">

Hi @jhwangbo , I attached an screenshot of the height map in raisimUnity

**Comment by jhwangbo** [comment]
You also need to visualize the scan points as well. You can check rayDemo2

**Comment by mstoelzle** [comment]
I tried to run the `rayDemo2.py` using `raisimPy` to see the visualization of the scan points, but it fails with this error:
```
Assertion failed: (index >= 0 && index < size()), function operator[], file /usr/local/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h, line 162.
zsh: abort      python raisimPy/examples/rayDemo2.py
``

**Comment by jhwangbo** [comment]
I fixed a bug in the demo file. you can run it.
Next time you should run the code in debug mode and tell me which line failed. Currently, I don't have time to resolve all issues.

**Comment by jhwangbo** [comment]
I'll close this issue until I see the visualization.
