### ISSUE TITLE
setup.py error

### ISSUE THREAD

**Issue by wyattPol** [raisimTech/raisimLib#571]
I try to run the "python setup.py develop" in the conda environment and in the raisimgymtorch folder, it keeps telling me errors:"File "/home/xxxraisim_workspace/raisimlib/raisimGymTorch/setup.py", line 66, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/xxxminiconda3/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2."
my python version is 3.11, pytorch installed useing this command"conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=12.1 -c pytorch -c nvidia"
no idea why it keeps showing error.......

**Comment by jhwangbo** [comment]
It seems like your cmake build failed. You must have received other error messages from cmake

**Comment by wyattPol** [comment]
> It seems like your cmake build failed. You must have received other error messages from cmake

here is the full error text:
(base) xxx@sidusi:~/raisim_ws/raisimLib/raisimGymTorch$ python3 setup.py develop
/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
-- pybind11 v2.9.0 
-- raisim:
--   Version: 1.1.7
--   Includes: /home/xxx/raisim_ws/raisimLib/raisim/linux/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;raisim::raisim
raisim os linux
raisim arch 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxx/raisim_ws/raisimLib/raisimGymTorch/build/temp.linux-x86_64-cpython-311
Consolidate compiler generated dependencies of target rsg_anymal
[ 33%] Building CXX object CMakeFiles/rsg_anymal.dir/raisimGymTorch/env/raisim_gym.cpp.o
In file included from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/cast.h:16,
                 from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/attr.h:13,
                 from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/pybind11.h:13,
                 from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/raisimGymTorch/env/raisim_gym.cpp:6:
/home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/detail/type_caster_base.h: In function ‘std::string pybind11::detail::error_string()’:
/home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/detail/type_caster_base.h:482:26: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
  482 |             frame = frame->f_back;
      |                          ^~
In file included from /home/xxx/miniconda3/include/python3.11/Python.h:42,
                 from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/detail/common.h:209,
                 from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/pytypes.h:12,
                 from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/cast.h:13,
                 from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/attr.h:13,
                 from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/thirdParty/pybind11/include/pybind11/pybind11.h:13,
                 from /home/xxx/raisim_ws/raisimLib/raisimGymTorch/raisimGymTorch/env/raisim_gym.cpp:6:
/home/xxx/miniconda3/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
gmake[2]: *** [CMakeFiles/rsg_anymal.dir/build.make:76: CMakeFiles/rsg_anymal.dir/raisimGymTorch/env/raisim_gym.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/rsg_anymal.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
Traceback (most recent call last):
  File "/home/xxx/raisim_ws/raisimLib/raisimGymTorch/setup.py", line 68, in <module>
    setup(
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/command/develop.py", line 109, in install_for_development
    self.run_command('build_ext')
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/xxx/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/xxx/raisim_ws/raisimLib/raisimGymTorch/setup.py", line 38, in run
    self.build_extension(ext)
  File "/home/xxx/raisim_ws/raisimLib/raisimGymTorch/setup.py", line 66, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/xxx/miniconda3/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.

**Comment by jhwangbo** [comment]
can you lower your python version, myabe to 3.9? Pybind11 doesn't support 3.11 yet

**Comment by wyattPol** [comment]
> can you lower your python version, myabe to 3.9? Pybind11 doesn't support 3.11 yet

yes, after i lower to 3.9. setup.py works. but when i run runner.py,it has error:
ch/env/envs/rsg_anymal$ python3 runner.py
/home/xxx/miniconda3/envs/python39/lib/python3.9/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /opt/conda/conda-bld/pytorch_1704987290837/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/xxx/raisim_ws/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 45, in <module>
    env = VecEnv(RaisimGymEnv(home_path + "/rsc", dump(cfg['environment'], Dumper=RoundTripDumper)))
  File "/home/xxx/miniconda3/envs/python39/lib/python3.9/site-packages/ruamel/yaml/main.py", line 1251, in dump
    error_deprecation('dump', 'dump', arg="typ='unsafe', pure=True")
  File "/home/xxx/miniconda3/envs/python39/lib/python3.9/site-packages/ruamel/yaml/main.py", line 1037, in error_deprecation
    raise AttributeError(s)
AttributeError: 
"dump()" has been removed, use

  yaml = YAML(typ='unsafe', pure=True)
  yaml.dump(...)

instead of file "/home/xxx/raisim_ws/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 45

env = VecEnv(RaisimGymEnv(home_path + "/rsc", dump(cfg['environment'], Dumper=RoundTripDumper)))

**Comment by wyattPol** [comment]
> can you lower your python version, myabe to 3.9? Pybind11 doesn't support 3.11 yet

but after i using yaml.dump() instead dump, i got new error:nit__.py:141: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /opt/conda/conda-bld/pytorch_1704987290837/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/yiting/raisim_ws/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 45, in <module>
    env = VecEnv(RaisimGymEnv(home_path + "/rsc", yaml.dump(cfg['environment'], Dumper=RoundTripDumper)))
TypeError: dump() got an unexpected keyword argument 'Dumper'

**Comment by wyattPol** [comment]
> can you lower your python version, myabe to 3.9? Pybind11 doesn't support 3.11 yet

but after i use yaml.dump instaed dump, i got new error:
nit__.py:141: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /opt/conda/conda-bld/pytorch_1704987290837/work/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/xxxraisim_ws/raisimLib/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py", line 45, in <module>
    env = VecEnv(RaisimGymEnv(home_path + "/rsc", yaml.dump(cfg['environment'], Dumper=RoundTripDumper)))
TypeError: dump() got an unexpected keyword argument 'Dumper'

**Comment by wyattPol** [comment]
> can you lower your python version, myabe to 3.9? Pybind11 doesn't support 3.11 yet

i tried this line and problem above solved:pip install "ruamel.yaml<0.18.0"
