### ISSUE TITLE
error happens while using addArticulatedSystem

### ISSUE THREAD

**Issue by ZijianWu1121** [raisimTech/raisimLib#575]
When I use the CPP API world.addArticulatedSystem("XXX.urdf"); 
it shows the error log below:

terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)

and the URDF file: https://drive.google.com/file/d/17ajNF_3T2UKmNvxqySPYllH63wv2_Ptn/view?usp=drive_link

**Comment by jhwangbo** [comment]
I cannot access that file. Did you test that urdf with other software?
