### ISSUE TITLE
Inconsistent bouncing behaviour between fixed-base object and floating base object

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#58]
I have observed an inconsistent bouncing behavior between fixed-base object and floating base object: for the same pair of fixed-base object and floating-base object, the bouncing behavior seems inconsistent. If the fixed-base object hit the floating-base object from the side, there seems to be no bouncing effect at all (although the restitution coefficient is set to be 0.95 between the pair).  If the fixed-base object hit the floating-base object from above, then the bouncing effect seems to be fine. The source code can be found here:
[RaisimAerialInteraction.zip](https://github.com/raisimTech/raisimLib/files/5984475/RaisimAerialInteraction.zip)

**Comment by jhwangbo** [comment]
I think I figured out the issue. I'll push a fix tmr.

You should check out the doc on ``getPosition``. The second argument is not output. It is the local position on the body.

**Comment by weixuanzhang** [comment]
Thanks for the heads-up!

**Comment by jhwangbo** [comment]
I pushed a fix for the Linux version. Thx for reporting and testing. Mac and Windows versions will follow
