### ISSUE TITLE
M1 compilation issue, missing SpinningLidar

### ISSUE THREAD

**Issue by Fusica** [raisimTech/raisimLib#583]
When trying to make install -j4 on the M1 system, the following error occurred:
/Users/max/Downloads/Projects/raisim_ws/raisimLib/examples/src/server/sensors.cpp:54:42: error: no member named 'SpinningLidar' in namespace 'raisim'
  auto lidar = anymal->getSensor<raisim::SpinningLidar>("lidar_link:lidar");
                                 ~~~~~~~~^
1 error generated.
Then I checked raisim/m1/raisim/sensors and found that there is no SpinningLidar.hpp. I wonder if this is a necessary file?

**Comment by Fusica** [comment]
I am currently temporarily in examples/src/server/sensors.cpp, commenting out line 54, as well as lines 83-94. After that, I can compile normally. Will this affect the functionality? 
Is SpinningLidar an important feature? I just started to get in touch with it and I'm not sure if it will be used in the future. If it will be used later, has the author considered adding relevant code in m1?

**Comment by jhwangbo** [comment]
I don't update M1 binaries everytime. But if you don't need a spinning lidar, it should not be a problem.
