### ISSUE TITLE
RaiSimUnity Autoconnect

### ISSUE THREAD

**Issue by hilario** [raisimTech/raisimLib#586]
From the [documentation](https://raisim.com/sections/RaisimUnity.html) we can read that the RaiSimUnity app has the auto connect setting on by default, but this is not our case (we are using tag: 812d50c9d7aa82f74cc1f8fa7193ad95c2b99f5e) on linux Ubuntu 20.04.

- Are there any command line arguments where you can set this option before launching the executable?
- Are there any command line arguments to pass the resource folders where meshes etc can be retrieved, instead of having to use the GUI

Our goal is to generate videos of the simulation without human intervention, thus we need to remove all the manual steps from the GUI.

Thank you!

**Comment by jhwangbo** [comment]
Hi @hilario. Sorry for getting back late.
Now the visualizers should load the configuration from ``gui_settings.xml``. Their location is slightly different from OS/Engine.
Can you try the latest tag? We had issues with GLibC compatibility before but now I build everything thru docker and there shouldn't be any issue with compatibility
