### ISSUE TITLE
Fixed-base contact force computation

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#59]
The contact force for fixed-base object is not matching what I expect it to be. Two cases are inspected:
1. The fixed-base (robot 2 in the example code) is on top of a floating base object: there is non-zero contact forces in the x- and y-direction. Although it should be zero
2. The fixed-base (robot 2 in the example code) is contacting the side of a floating base object under external force. The forces again do not cancel out. In addition, there seems to be a misalignment of the frames: the contact force is expected to be (-20, 0, 0), whereas it outputs (0, -20, 3) in the terminal.

The contact force is computed by averaging the contact impulse over a hundred time stamps, which is 200 ms.
The source code can be found here: 
[RaisimAerialInteraction.zip](https://github.com/raisimTech/raisimLib/files/5988106/RaisimAerialInteraction.zip)

**Comment by jhwangbo** [comment]
can you share a minimal code? I appreciate that you are sharing an executable but you should remove everything that is irrelevant.

**Comment by jhwangbo** [comment]
Reading at you comments, I guess you didn't convert the frame. The impulse is expressed in contact frame, not in the world frame. you can check the example here. https://raisim.com/sections/Contact.html#contacts

**Comment by weixuanzhang** [comment]
Sorry for the messy code. Here is an cleaned-up version of the code:
[RaisimAerialInteraction.zip](https://github.com/raisimTech/raisimLib/files/5988677/RaisimAerialInteraction.zip)
I have converted the frame via 'contact.getContactFrame().e()*contact.getImpulse()->e()'

**Comment by jhwangbo** [comment]
Answers to your two cases
1. this does not seem to be a bug. the robot is constrained and the constraint forces can produce x- and y- direction forces
2. This seems like an error in the doc. The correct way to get it is ``contact.getContactFrame().e().transpose()*contact.getImpulse()->e``.

Thank you again for reporting. I'll apply the fixes on the website

**Comment by weixuanzhang** [comment]
Thanks for your reply.  Is there a way of getting the constraint forces/torques?

**Comment by jhwangbo** [comment]
#3 is still open. It will take quite some time to implement it. Not sure when I'll do it

**Comment by weixuanzhang** [comment]
Okay thanks
