### ISSUE TITLE
Raisimpy Error

### ISSUE THREAD

**Issue by KurokoWD** [raisimTech/raisimLib#595]
Thanks to your excellent work.
When I import raisimpy in a python3.8 environment, a error occured as follow: 
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /raisim_ws/raisimLib/raisim/linux/lib/raisimpy.cpython-38-x86_64-linux-gnu.so)
And I found the hightest GLIBC version of my libc.so.6 is 2.31(My OS is Ubuntu20.04)
Can you help me?
By the way "import raisimpy" works in python3.11.

**Comment by jhwangbo** [comment]
The workaround for now is to build the raisimPy yourself, which is quite simple. All dependencies are provided in the thirdParty libraries. I'll think about improving my build environment in the meantime.

**Comment by KurokoWD** [comment]
Thank you so much
