### ISSUE TITLE
Fixed-base object bouncing steady state

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#60]
When a part of a fixed-base object falling to ground and with a non-zero restitution coefficient, it could have a steady state of standing on its edge. This is physically impossible (the com is not going through the edge). The floating base object appears to not have this problem. 

Source code (in the simulation one object is fixed-base and one is floating base, both falling from the same initial pose): 
[RaisimAerialInteraction.zip](https://github.com/raisimTech/raisimLib/files/5991801/RaisimAerialInteraction.zip)

**Comment by weixuanzhang** [comment]
Perhaps this has something to with #59 with existing constraint torque. I will take a look at the setup of the example.

**Comment by jhwangbo** [comment]
No, this one is different. Actually, if you play it for a very long time, it falls. I think it's the way the inertia is set up. The inertia values are not realistic. But still, I think it falls slower than what I would expect. I'll also think about it a bit more

**Comment by weixuanzhang** [comment]
I looked into the setup again. It seems that the cause is the limit I set for the revolute joint at the end effector. If I set it to 0 (no limit), then it is fine. However, in the example code, I set the upper and lower limit to be 10000/-10000 rad, which theoretically should not be active. Is this an expected behavior?

**Comment by jhwangbo** [comment]
aha, you are right. Let me check what went wrong.

**Comment by jhwangbo** [comment]
Currently, it is disabled only if you set them equal. I'll change it such that if lower_bound > upper_bound, it is disabled.

**Comment by weixuanzhang** [comment]
I just see that I confused the lower_bound with the upper_bound. This is really just a corner case for a stupid bug. Is there a way also to send a warning to the user?

**Comment by jhwangbo** [comment]
Yes, maybe a warning is better. I'll push the change tmr

**Comment by weixuanzhang** [comment]
Thanks!

**Comment by jhwangbo** [comment]
I pushed the change. Now it should raise a fatal error.
