### ISSUE TITLE
Example Code Not Working

### ISSUE THREAD

**Issue by Kenn3o3** [raisimTech/raisimLib#600]
Hello, 

I am trying to run an example code from this repository and I keep running into the same error. 
I tried running this: python /home/user1/Desktop/quadrupedal-2024/code/raisimLib/raisimPy/examples/**newtonsCradle.py**
and I got this as an output:
[2024:07:11:14:32:34 World.cpp:1397] RaiSim is in debug mode.
Segmentation fault (core dumped)
I ran it through a debugger and got this:

===============================

Starting program: /home/user1/anaconda3/envs/raisim/bin/python /home/user1/Desktop/quadrupedal-2024/code/raisimLib/raisimPy/examples/newtonsCradle.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3fff640 (LWP 47255)]
[New Thread 0x7ffff37fe640 (LWP 47256)]
[New Thread 0x7fffeeffd640 (LWP 47257)]
[New Thread 0x7fffec7fc640 (LWP 47258)]
[New Thread 0x7fffebffb640 (LWP 47259)]
[New Thread 0x7fffe77fa640 (LWP 47260)]
[New Thread 0x7fffe4ff9640 (LWP 47261)]
[New Thread 0x7fffe27f8640 (LWP 47262)]
[New Thread 0x7fffdfff7640 (LWP 47263)]
[New Thread 0x7fffdd7f6640 (LWP 47264)]
[New Thread 0x7fffdaff5640 (LWP 47265)]
[New Thread 0x7fffd87f4640 (LWP 47266)]
[New Thread 0x7fffd5ff3640 (LWP 47267)]
[New Thread 0x7fffd37f2640 (LWP 47268)]
[New Thread 0x7fffd2ff1640 (LWP 47269)]
[2024:07:11:14:31:08 World.cpp:1397] RaiSim is in debug mode.
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
0x0000000000000000 in ?? ()
 0x00007fffce4d27dd in ?? () from /home/user1/Desktop/quadrupedal-2024/code/raisimLib/raisim/linux/lib/raisimpy.cpython-310-x86_64-linux-gnu.so
0x00007fffce4c5ab9 in ?? () from /home/user1/Desktop/quadrupedal-2024/code/raisimLib/raisim/linux/lib/raisimpy.cpython-310-x86_64-linux-gnu.so
 0x00007fffce4ab2ab in ?? () from /home/user1/Desktop/quadrupedal-2024/code/raisimLib/raisim/linux/lib/raisimpy.cpython-310-x86_64-linux-gnu.so
0x00007fffce48b57d in ?? () from /home/user1/Desktop/quadrupedal-2024/code/raisimLib/raisim/linux/lib/raisimpy.cpython-310-x86_64-linux-gnu.so
 0x00007fffce48b785 in ?? () from /home/user1/Desktop/quadrupedal-2024/code/raisimLib/raisim/linux/lib/raisimpy.cpython-310-x86_64-linux-gnu.so
 0x00007fffce447cf2 in ?? () from /home/user1/Desktop/quadrupedal-2024/code/raisimLib/raisim/linux/lib/raisimpy.cpython-310-x86_64-linux-gnu.so
  0x00000000004fdc87 in cfunction_call (func=0x7fffce7d4540, args=<optimized out>, kwargs=<optimized out>) at /usr/local/src/conda/python-3.10.14/Objects/methodobject.c:543
0x00000000004f741b in _PyObject_MakeTpCall (tstate=0x7796b0, callable=0x7fffce7d4540, args=<optimized out>, nargs=<optimized out>, keywords=0x0) at /usr/local/src/conda/python-3.10.14/Objects/call.c:215
 0x0000000000509cbf in _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=0x7ffff7b29ba8, callable=0x7fffce7d4540, tstate=0x7796b0)
    at /usr/local/src/conda/python-3.10.14/Include/cpython/abstract.h:112
_PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=0x7ffff7b29ba8, callable=0x7fffce7d4540, tstate=0x7796b0)
    at /usr/local/src/conda/python-3.10.14/Include/cpython/abstract.h:99
method_vectorcall (method=<optimized out>, args=0x7ffff7b29bb0, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.14/Objects/classobject.c:53
 0x00000000004f2c16 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff7b29bb0, callable=0x7ffff7920d00, tstate=0x7796b0)
    at /usr/local/src/conda/python-3.10.14/Include/cpython/abstract.h:114
PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ffff7b29bb0, callable=0x7ffff7920d00) at /usr/local/src/conda/python-3.10.14/Include/cpython/abstract.h:123
call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7fffffffcef0, tstate=<optimized out>) at /usr/local/src/conda/python-3.10.14/Python/ceval.c:5893

====================================

It traced the error back to this: raisimpy.cpython-310-x86_64-linux-gnu.so
I tried reinstalling the repository and building it from scratch and that did not fix the issue. 

Any help would be appreciated. Feel free to reach out if you have any questions and I will try to clarify. 
Thank you!

**Comment by shendredm** [comment]
Hi @Kenn3o3 did you get solution for this issue? If yes, could you tell me?
