### ISSUE TITLE
which env does raisimUnity display within "num_envs"

### ISSUE THREAD

**Issue by PangMitu** [raisimTech/raisimLib#605]
Hello,
When running the raisimGymtorch code, there is a parameter called "num_envs" in cfg.yaml file and the initial number is 100. Does that mean there are 100 envs running parallelly, and there is no influence and interaction between different envs?
Besides, if the envs are independent, which envs is shown in raisimUnity? 
Thanks in advance.

**Comment by jhwangbo** [comment]
Its the first env

**Comment by PangMitu** [comment]
Thank you for your answer.
