### ISSUE TITLE
Convert angular rates (quaternion derivative) to angular velocity

### ISSUE THREAD

**Issue by RobertoRoos** [raisimTech/raisimLib#62]
As part of a my program I need to convert between angular rates (which is the derivative of a quaternion) to angular velocities.
Is there a provided function that does accomplishes this?

The reverse must happen at some point in the library to integrate angular velocities into new quaternions.

The context is I need an end-effector jacobian, but not with respect to the body angular velocity but to the body position. Basically the difference between:

![equation](https://latex.codecogs.com/gif.latex?%5Cbegin%7Balign*%7D%20%5Cdot%7Bp%7D_%7Bee%7D%20%26%3D%20J_v%28q%29%20v%20%5C%5C%20%5Cdot%7Bp%7D_%7Bee%7D%20%26%3D%20J_q%28q%29%20%5Cdot%7Bq%7D%20%5Cend%7Balign*%7D)

From RaiSim I can get the velocity jacobian with `getDenseFrameJacobian`. But then I need to convert the quaternion part.

**Comment by jhwangbo** [comment]
No, we don't have such a method. But I think this is quite simple to implement yourself. Take a derivative of the definition of the quaternion. Then, you will find a term axis times theta dot. The rest of the terms are Jacobian that maps the two representations

**Comment by RobertoRoos** [comment]
For completeness, I found this PDF that explains it pretty clearly: https://arxiv.org/pdf/0811.2889.pdf

![image](https://user-images.githubusercontent.com/12717020/108853497-1418d900-75e7-11eb-9b38-1ecba8e0bbb5.png)

Note that RaiSim uses fixed reference quaternions, so we need to use the right column.

**Comment by RobertoRoos** [comment]
I'm back at quaternion magic. Now I am trying to find a jacobian; the derivative of angular rates w.r.t. the quaternion. For a single quaternion this looks like:

![image](https://latex.codecogs.com/gif.latex?%5Cdot%7BQ%7D%20%3D%20%5Cfrac%7B%5Cpartial%7D%7B%5Cpartial%20Q%7D%28Q%5Cotimes%5COmega%29%20%3D%20%5Cfrac%7B%5Cpartial%7D%7B%5Cpartial%20Q%7D%28%5Ctilde%7B%5Comega%7D_Q%20Q%29%20%3D%20%5Ctilde%7B%5Comega%7D_Q)

I've made a unit test to check this with finite difference, but RaiSim gives different answers.

@jhwangbo would you share the literal definitions of the quaternions and angular velocities from inside RaiSim? I might be assuming something that is not correct.

Thank you!

**Comment by jhwangbo** [comment]
The quaternion uses ``(w,x,y,z)`` convention. The angular velocity in the generalized velocity is in the world frame, not in the body frame.  I am not sure what you mean by "the derivative of angular rates w.r.t. the quaternion". How are they related? In your euqation, is Q a quaternion? So lhs is 4X1 and the rhs is 3X3?

**Comment by RobertoRoos** [comment]
I've made a notation mistake in the equation, changing it now.

In the equation above Q is a quaternion, omega the angular velocity and Omega = [0, omega]^T (i.e. to make it 4x1).
The cross symbol represents a quaternion product.

The quaternion derivative (= angular rates) is a function of the quaternion itself and the angular velocity. Therefore the angular rates will vary with the orientation, even with a fixed angular velocity.
This is extremely niche, but I need it for my numerical optimizations (constraint jacobians and such).

**Comment by jhwangbo** [comment]
quatToRotMat(gc.ptr() + 3, rot_WB[0]);
      matTransposevecmul(rot_WB[0], angVelMid, vel2);
      vel2 *= dt;
      eulerVecToQuat(vel2, quat);
      quatMul(&gc[3], quat.ptr(), quat2.ptr());
      quat2 *= 1.0 / quat2.norm();
      gc[3] = quat2[0];
      gc[4] = quat2[1];
      gc[5] = quat2[2];
      gc[6] = quat2[3]; 

Depending on the integrators that you choose, ``angVelMid`` will change. The default is semi-implicit
