### ISSUE TITLE
Dynamics tag in URDF convention

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#63]
I am trying to understand the interpretation of rotor_inertia, stiffness, and damping. Is it basically a second-order system with rotor_inertia being the "mass"?  In addition, does this work for the prismatic joint? I noticed that the system could go unstable for some parameters as shown in this example:
[RaisimAerialInteraction.zip](https://github.com/raisimTech/raisimLib/files/6012282/RaisimAerialInteraction.zip)

**Comment by jhwangbo** [comment]
``stiffness`` and ``damping`` are for the spring and damper attached to the joint. For a prismatic joint, they are for a linear spring and linear damper.
``rotor_inertia`` is an approximation to the true rotor inertia. It simulates the inertia before the gearbox (but you have to multiply the real rotor inertia by the square of the gear ratio to get the reflected rotor inertia). For prismatic joint, you can interpret it as rotor_mass. I called this an approximation. For the true articulated system dynamics, you have to add a separate link. Simulation using ``rotor_inertia`` ignores the gyroscopic effect (which is becoming negligible as the gear ratio increases).

Can you elaborate more on the example that you sent? I am not sure what I should expect that from simulation. What should happen and what is happening?

**Comment by weixuanzhang** [comment]
Thanks for the explanation. So basically I have a link with spring and damper through the dynamics tag inserted at the joint of the end-effector (a ball) and the body (the cylinder).  When I let it drop, I expect to see the body oscillating and reduce to a constant distance to the end-effector due to the spring-damper system. However, this is not the case here, as the body bounces back to infinity after hitting the ground.

**Comment by jhwangbo** [comment]
there was a bug. I pushed the fix. I also added the ``springTest`` example.

You had four numbers for the spring_mount. You only need one number.

Thank you for reporting the bug again. It is a great contribution.

**Comment by weixuanzhang** [comment]
Thank you very much for the quick fix!

**Comment by weixuanzhang** [comment]
> You had four numbers for the spring_mount. You only need one number.
Actually, by looking into your code I am confused by this statement, since in "chainSpringed.urdf" you also assign four numbers to the spring_mount. Is it because in my example I have unit quaternion and therefore only one number?

**Comment by jhwangbo** [comment]
The spring position is represented by a generalized coordinates. The chain example is for the ball joint
