### ISSUE TITLE
python3-dev dependency in installation instruction missing (ubuntu 20.04);

### ISSUE THREAD

**Issue by PascalEgli** [raisimTech/raisimLib#64]

**Comment by jhwangbo** [comment]
It should work if you follow the instruction. Did you experience any issues?

**Comment by PascalEgli** [comment]
[ 80%] Building CXX object raisimPy/CMakeFiles/raisimpy.dir/src/articulated_system.cpp.o
In file included from /home/pasegli/clion_projects/rslgym/rslgym_ws/raisimLib/thirdParty/pybind11/include/pybind11/pytypes.h:12,
                 from /home/pasegli/clion_projects/rslgym/rslgym_ws/raisimLib/thirdParty/pybind11/include/pybind11/cast.h:13,
                 from /home/pasegli/clion_projects/rslgym/rslgym_ws/raisimLib/thirdParty/pybind11/include/pybind11/attr.h:13,
                 from /home/pasegli/clion_projects/rslgym/rslgym_ws/raisimLib/thirdParty/pybind11/include/pybind11/pybind11.h:44,
                 from /home/pasegli/clion_projects/rslgym/rslgym_ws/raisimLib/raisimPy/src/articulated_system.cpp:25:
/home/pasegli/clion_projects/rslgym/rslgym_ws/raisimLib/thirdParty/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
  112 | #include <Python.h>
      |          ^~~~~~~~~~


Works only after installing sudo apt install python3-dev.

**Comment by jhwangbo** [comment]
Thanks for reporting it. I pushed the fix
