### ISSUE TITLE
Different coefficients for static friction and dynamics friction

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#65]
Is it possible to have a different coefficient than the dynamic friction coefficient to establish a stiction threshold? Essentially, I want the stiction threshold to be larger than the dynamic friction given the same normal force, as seen in a lot of material pairs.

**Comment by jhwangbo** [comment]
This is currently not possible. I will implement this once i have some spare time.

**Comment by weixuanzhang** [comment]
Hi Jemin,  Do you have an ETA for this update? Thanks!

**Comment by jhwangbo** [comment]
I am working on this right now. I can push early next week

**Comment by weixuanzhang** [comment]
Great. Thanks!

**Comment by jhwangbo** [comment]
I pushed the feature and added a doc on it https://raisim.com/sections/MaterialSystem.html
