### ISSUE TITLE
rayTest with height map and ground

### ISSUE THREAD

**Issue by feracero** [raisimTech/raisimLib#66]
Hi, I'm playing around with rayTest and I think the function is not performing as described in the documentation. According to the docs, by default rayTest should return the closest collision only and can collide with all collision groups. For some reason, when I include a height map and ground in the same environment, rayTest always returns the collision with the ground, even if the closest collision of the ray is with the height map. This can be tested by adding a ground object to the environment in _rayDemo.cpp_ as:

```
auto hm = world.addHeightMap(0.0, 0.0, terrainProperties);
auto ground = world.addGround();
auto cube = world.addBox(1,1,1,1);
```

When there is only a height map, the ray can collide with the height map. However, when there are both height map and ground, the ray does not collide with the height map and collides with the ground instead:

<img width="958" alt="heightmap_" src="https://user-images.githubusercontent.com/46450880/109042880-988f5880-76c8-11eb-8e84-2d1461b99b0b.png">
<img width="958" alt="ground" src="https://user-images.githubusercontent.com/46450880/109042899-9e853980-76c8-11eb-955b-d90926d4d2ee.png">

Alternatively, the unmodified file _rayDemo.cpp_ shows that when there is only a height map present, rayTest does return collisions with it:

<img width="958" alt="heightmap" src="https://user-images.githubusercontent.com/46450880/109043012-c5437000-76c8-11eb-932c-90acc6077bb1.png">

**Comment by jhwangbo** [comment]
a fix has been pushed for the Linux version. other OS versions will follow. Thanks for reporting
