### ISSUE TITLE
Question regarding joint velocity limits.

### ISSUE THREAD

**Issue by vastsoun** [raisimTech/raisimLib#68]
Does using the internal PD controller of  `ArticulatedSystem` instances impose joint velocity limits?

I ask because I have a simulation of a Kinova3 loaded via URDF, and I compared using an external custom PD controller to using the internal one and observed that the internal seems to cap the joint velocity. I modified the URDF joint limits field but it had no effect. I also checked the documentation and the `ArticulatedSystem` header, but was unable to find any member function to either get or set joint velocity limits.

**Comment by jhwangbo** [comment]
The velocity limits are currently ignored. There is no velocity limit in the physical world and it is not clear to me how it should behave. Usually, they are bound by the actuators but actuator velocity limits are not just a number. They are coupled with torque. If you have a suggestion, let me know
