### ISSUE TITLE
Physical behavior has changed from old version.

### ISSUE THREAD

**Issue by mktk1117** [raisimTech/raisimLib#69]
The physical behavior has changed in the new versions.
Is there any algorithmic change in the physic engine recently?

**Comment by jhwangbo** [comment]
Yes, i am constantly improving the contact solver. What change did you notice?

**Comment by mktk1117** [comment]
The joint speed and torque seem to be different. When a controller trained with the old version is deployed in a newer version, its movement becomes different.

**Comment by jhwangbo** [comment]
Taka, I cannot do anything with what you provided. You are wasting my time here with these issues. Specify how it's different. Share videos. Analyze the torque/joint velocity profile and provide some clues.

**Comment by mktk1117** [comment]
I'll directly share videos with you then.
