### ISSUE TITLE
control_dt and Unity visualization frequency

### ISSUE THREAD

**Issue by fanshi14** [raisimTech/raisimLib#70]
Hi Jemin,

I found when I change `control_dt` in `cfg.yaml` from `0.01` to `0.02`, the Unity visualization seems to speed up `2x`.
From `0.01` to `0.005`, it seems to be `0.5x`.

Maybe some misuse from me, I wonder how to set Unity visualization frequency to be identical to `control_dt` setting.

THX

**Comment by jhwangbo** [comment]
The visualization runs as fast as your simulation. It just displays the current state and has no influence on the simulation speed.

**Comment by fanshi14** [comment]
Thx Jemin.
My question is equivalent to make simulation speed same as the real nature time.
One way is to manually add `usleep()` in `step()`.

If any better method, plz let me know as well.

**Comment by jhwangbo** [comment]
I don't know anything better than ``usleep``. You have to measure the time it starts the simulation and ``sleep`` whenever it is necessary in the loop.
