### ISSUE TITLE
multiple collision v.s. multiple links for irregular shape

### ISSUE THREAD

**Issue by fanshi14** [raisimTech/raisimLib#71]
Hi Jemin,

For a foot with irregular shape, the foot collision in `urdf` could be represented by:

1. one link with multiple `<collision>` geometry
2. or multiple one-`<collision>` links, connected by fixed joints

Since contact force of foot is critical, I wonder any difference in contact solver? 

THX

**Comment by jhwangbo** [comment]
Those two are identical
