### ISSUE TITLE
Stable PD controller， damping parameter

### ISSUE THREAD

**Issue by WoodenJin** [raisimTech/raisimLib#72]
Hello, my test found that when the PD controller actually calculates, the real damping seems to be only half of the set damping. I don’t know if there is an extra 0.5 in the implicit solution formula.

**Comment by jhwangbo** [comment]
It passes my PD controller test suite which includes damping as well. How did you test?

**Comment by WoodenJin** [comment]
--------------------------------------urdf file--------------------------------------------------
<robot name="2DrobotArm">
    <link name="world"/>
    <link name="link1"/>
    <joint name="worldTolink1" type="fixed">
        <parent link="world"/>
        <child link="link1"/>
        <origin xyz="0 0 0"/>
    </joint>
    <link name="link2">
        <inertial>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.2"/>
            <mass value="1"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>
    <joint name="link1Tolink2" type="revolute">
        <parent link="link1"/>
        <child link="link2"/>
        <origin xyz="0 0 0.3"/>
        <axis xyz="1 0 0"/>
        <limit effort="80" lower="-1" upper="1" velocity="15"/>
    </joint>
</robot>

-------------------src code -------------------------------
#include <iostream>
#include "raisim/World.hpp"
#include <Eigen/Core>

using namespace std;

int main() {
//    raisim::World::setActivationKey(raisim::Path("./activation.raisim").getString());
    raisim::World::setActivationKey(raisim::Path("activation.raisim").getString());
    raisim::World world;
    Eigen::VectorXd jointDgain;
    Eigen::VectorXd jointPgain;
    Eigen::VectorXd Ptarget;
    Eigen::VectorXd Dtarget;
    Eigen::VectorXd gc_;
    Eigen::VectorXd gv_;
    auto nunchucks = world.addArticulatedSystem("test.urdf");
    nunchucks->setControlMode(raisim::ControlMode::PD_PLUS_FEEDFORWARD_TORQUE);
    world.setTimeStep(0.002);
    int gcDim_ = nunchucks->getGeneralizedCoordinateDim();
    int gvDim_ = nunchucks->getDOF();
    jointDgain.setZero(gvDim_);
    jointPgain.setZero(gvDim_);
    gc_.setZero(gcDim_);
    gv_.setZero(gvDim_);
    Ptarget.setZero(gcDim_);
    Dtarget.setZero(gvDim_);
//    gc_ << 0, 0, 0, 0, 0, 0, 0, 0;
//    gv_ << 0, 0, 0, 0, 0, 0, 1;
//
//    // cout<< gcDim_ <<endl;
    jointDgain.tail(1) << 1;
    jointPgain.head(1) << 0;
    nunchucks->setPdGains(jointPgain, jointDgain);
    nunchucks->setPdTarget(Ptarget, Dtarget);
    nunchucks->getState(gc_, gv_);
    gv_.tail(1) << 10;
    cout<<gc_<<endl;
    nunchucks->setState(gc_, gv_);
    for (int i = 0; i < 10; i++) {
        world.integrate();
        cout << nunchucks->getGeneralizedVelocity() << " " << (nunchucks->getGeneralizedForce()) << endl;
    }
    std::cout << "Hello, World!" << std::endl;
    return 0;
}

--------------------------------printed result ------------------------------------
9.52381  -5 
9.07212  -4.7619 
8.64367  -4.53606 
8.23728  -4.32184 
7.85182  -4.11864 
7.48621  -3.92591 
7.13944  -3.74311 
6.81053  -3.56972 
6.49859  -3.40527 
6.20272  -3.24929 
Hello, World!

**Comment by jhwangbo** [comment]
I guess the doc is wrong. ``getGeneralizedVelocity`` does not provide the full generalized force when the PD controller is used. But it's applying the correct force. I will fix the doc

**Comment by WoodenJin** [comment]
You are right. I manually calculated it according to your stable PD control formula, and found that the calculated result is consistent with the set damping parameter, but the force value returned by the API seems to be wrong. Anyway, thank you for your answers, it is of great help to me.

**Comment by jhwangbo** [comment]
No problem. Thx for reporting the issue
