### ISSUE TITLE
Contact force computation for fixed-base object

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#73]
Hi Jemin,
It seems that when computing the contact force of a fixed-base object, I need to average over a longer period to get the correct result (contact_force =sum_over_1000_contact_impulse/1000*dt). The simulation dt is 0.002 seconds.
This is not the case for a floating-base object. contact_force = contact_impulse/dt outputs the expected contact force. The source code attached:

[RaisimAerialInteraction.zip](https://github.com/raisimTech/raisimLib/files/6121914/RaisimAerialInteraction.zip)

**Comment by jhwangbo** [comment]
Thx for reporting again. This looks like a natural behavior of the simulator but I'll run it tonight and check if it is not what I would expect

**Comment by jhwangbo** [comment]
btw, the urdf doesn't work. It immediately reports that
"/rsc/simpleBiCopter2.urdf' at row:159 col:10, the node 'limit'Lower joint limit cannot be higher than the upper one. If you want to disable the joint limit, remove "lower" and "upper" attributes."

**Comment by jhwangbo** [comment]
+ which means that you don't have the latest version.

**Comment by jhwangbo** [comment]
I don't see the convergence issue. I think the issue will be gone if you pull.

**Comment by weixuanzhang** [comment]
Indeed. I deleted the build and recompiled. The issue disappeared. Thank you very much for looking into this!
