### ISSUE TITLE
getGeneralizedForce when using built-in PD controller

### ISSUE THREAD

**Issue by mktk1117** [raisimTech/raisimLib#74]
In the doc, it says
```
const VecDyn &getGeneralizedForce()const
Generalized the force set by setGeneralizedForce(). This method should not be used when the built-in PD controller is used.

Return
the generalized force
```

However, I cannot find another function to get the generalized force when using built-in PD controller.
How should I get the torque of each joint of the articulated system when PD controller is used?

It just returns 0 values in this situation.

**Comment by jhwangbo** [comment]
I modified the method that it computes approximate gen force. I also updated the doc.
