### ISSUE TITLE
Lateral Light Needed

### ISSUE THREAD

**Issue by YandongJi** [raisimTech/raisimLib#75]
Hi Jemin, in our setup, sun light from above is blocked by an object above the robot so we need a lateral light in Linux Unity. The current range of sunlight that can be adjusted is not enough. Can we change the light direction like in raisimOgre? Or any possible ways to change the direction in Unity GUI? Thanks in advance.

**Comment by jhwangbo** [comment]
I slightly changed how the light works. I only pushed the changes in linux for now. other versions will follow. Try it out and let me know how you feel about it

**Comment by YandongJi** [comment]
It works well now. Just what we want. Thanks
