### ISSUE TITLE
Add color to the height map

### ISSUE THREAD

**Issue by weixuanzhang** [raisimTech/raisimLib#76]
Hi Jemin,
Is it possible to add color to the height map? The reason is that I would like my height map to contain different friction coefficients. So far as I know, the only way to do this is to add multiple height maps into the world and I would like to color them for visual convenience. Thanks!

**Comment by YandongJi** [comment]
setAppearance("r,g,b,alpha") and setAppearance("red") might be useful.

**Comment by weixuanzhang** [comment]
Somehow I missed this. @YandongJi Thanks!
