### ISSUE TITLE
Segfault with getGeneralizedForce

### ISSUE THREAD

**Issue by Mathieu-Geisert** [raisimTech/raisimLib#77]
Hi,
I've pulled master today and got a segfault when testing the example in raisimGymTorch (examples in raisim work fine). The segfault appears at commit " added getGeneralizedForce for PD controller".
The program stops at raisimLib/raisim/linux/include/raisim/object/ArticulatedSystem/ArticulatedSystem.hpp:395 
`genForce = tauFF_;`
On my computer, setting the size of genForce before this operation was enough to solve the problem.

Best,
Mathieu.

**Comment by jhwangbo** [comment]
I saw it in the unit test. I thought I pushed the fix but somehow I missed it. Thx for reporting. You can pull and try again
