### ISSUE TITLE
Constant mass assumption when solving newton's second law

### ISSUE THREAD

**Issue by christophecricket** [raisimTech/raisimlib#8]
Hi There

I was wondering (am currently testing this out myself but thought I'd make sure): does raisim make a constant mass assumption when integrating Newton's second law for the dynamics of ```SingleBodyObject```'s?

In other words, which of the differential equations I list in the attached picture below is raisim solving when an object is in free motion?

![raisim_integration](https://user-images.githubusercontent.com/31511530/95427367-bb9eb300-0947-11eb-9b22-22349d32f646.png)

**Comment by jhwangbo** [comment]
why is constant mass an assumption? Do you want to change the mass online?
In that case, the mass is changed between the simulation time steps. So the constant mass is still valid

**Comment by christophecricket** [comment]
So the integration ignores the dm/dt * v term, then, right? That's what I was asking about

**Comment by jhwangbo** [comment]
RaiSim doesn't ignore it. It is always zero.

**Comment by christophecricket** [comment]
I'm simulating something in an edge case where it might not be, but thanks! That's exactly what I wanted to know.
