### ISSUE TITLE
Raisim Unity visualization issue: freezing at initial frame

### ISSUE THREAD

**Issue by Pala-Ah** [raisimTech/raisimLib#81]
I am currently running a custom training simulation in RaisimGymTorch. When I try to evaluate/test and visualize the current policy, there is a random chance that the visualization might not work. 

The simulation itself seems to work just fine and I get an output for the new observation every time step, but the frame freezes at the initial robot position and the robot does not move at all (it does actually in the simulation, but not in the visualization. It is still possible to move the camera around). It is also not recording. After pushing the connect button several times, the visualization starts working at the current simulation time step.

![sim](https://user-images.githubusercontent.com/60257014/112042253-9beef600-8b47-11eb-8801-930f33b74c7b.gif)

I am running Raisim on Ubuntu 20.04. I also have the same problem with RaisimUnityOpenGL. Maybe there is an issue with the connection to the Raisim Server since the visualization starts working after pushing the connect button several times. Any suggestions how I can fix it? Is it maybe a network/firewall problem since RaisimUnity is working with an IP and a port, or might it be a GPU/driver problem? 

Side note: I wrote the environment and runner file according to rsg_anymal. the Environment.hpp has the same methods, so that Raisim Gym Environment can access them. I also reset and turn on the environment before I record and start the simulation. There is also no issue with GPU memory capacity, but Raisim Unity seems to be assigned to both CPU and GPU memory when I check with nvidia-smi.

**Comment by jhwangbo** [comment]
RaiSimUnity cannot freeze like that. If it doesn't receive the position for over 1.5 seconds, it will just terminate. I think it means that you are actually sending the initial position on the server side.
Do you have multiple servers? Can you check if you create only one server in the process? If you followed the ``rsg_anymal`` example, this shouldn't be the case

**Comment by Pala-Ah** [comment]
Thank you for the quick reply.
Yes, I have followed the rsg_anymal example, there is only one server for the visualizable environment. I also tried out the rsg_anymal example and I'm having the same issue.
 
![anymal](https://user-images.githubusercontent.com/60257014/112135932-9c7e9f80-8bce-11eb-982c-4a380819273f.gif)

**Comment by jhwangbo** [comment]
aha. I see what you meant now. The training example visualizes every 200 iterations. After visualizing the first example, the visualization is turned off here https://github.com/raisimTech/raisimLib/blob/d37b57f5f16c0418672689a9620624bb2018af45/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py#L110

**Comment by Pala-Ah** [comment]
That's right. But what you see in my gifs is happening inside the for-loop in Line 99-107. The visualization is still turned on, but there is no connection/visualization unless I push the connect button several times. There is a 50/50 chance I don't have to do this and the visualization starts working itself.

If I am the only one having this problem, then there seems to be an issue with my system setup. Although I upgraded recently from 16.04 to 20.04 with a clean reinstallation. I can't tell what the problem might be.

**Comment by jhwangbo** [comment]
What happens if you don't click the connect? Do you get a timeout?

**Comment by Pala-Ah** [comment]
No, I don't get any error. With the anymal example I can still see the robot at the initial position and the training loop starts iterating (Line 116-122 / Line 77-145 with update > 0).  

One more thing I noticed: I have set `eval_every_n: 2` in the cfg.yaml to reach evaluation steps earlier and if I couldn't get a connection at the first evaluation/visualization, then all the upcoming evaluation steps wouldn't be visualized. If I click on connect until a connection is established, all the upcoming evaluation steps are actually visualized. 

So what I can do for now is to start the training session and click on connect until the visualization works and I can (probably) be sure that all the upcoming visualizations will not freeze. But In my training setup I am currently reopening and closing RaisimUnity at every evaluation with `proc = subprocess.Popen('$PATH_TO_RAISIMUNITY')` and`proc.kill()` to get better time efficiency during training since letting RaisimUnity opened slows down the training about 5-10 seconds every update iteration.

**Comment by jhwangbo** [comment]
The fact that you can see the robot in a standing configuration means that there is a server sending the standing configuration. RaiSimUnity doesn't know the initial configuration at all. Actually, it doesn't even know how the links are connected. RaiSim sever sends the pose of each link separately. So I think there are multiple servers. Can you put cout, maybe in the server constructor, to see how many are instantiated?

**Comment by Pala-Ah** [comment]
I tried your suggestion and I have found out, that there seems to be not only one, but two servers for every environment in RaisimGymTorch. Not only in my own simulation, but also in the rsg_anymal example. 

I have tried two things:
1. I have put `RSINFO(server_->STATUS);` into the `reset()` method in the Environment.hpp (in my simulation and in the anymal example) too see how many servers could possible be instantiated. When `env.reset()` is called in the runner.py file, I get `2*n_envs` outputs: `2` which stands for `STATUS_TERMINATING`. Not sure what this particularly means, but at least there seems to be `2*n_envs` servers sending a feedback. Environment.hpp inherits from RaisimGymEnv.hpp and there is a `server_` already declared. So that is maybe why every environment has at least one server declared, but not connected. 
2. Then I have tried `if (visualizable_) RSINFO(server_->isConnected());` instead (`RSINFO(server_->isConnected());` alone gives segfault error) and I do get again 2 outputs for the one visualized environment instead of 1 output, with either: 

case 1:
```commandline 
[2021:03:26:16:39:50 Environment.hpp:94] 1
[2021:03:26:16:39:50 Environment.hpp:94] 0
```
or case 2:
```commandline 
[2021:03:26:16:39:50 Environment.hpp:94] 0
[2021:03:26:16:39:50 Environment.hpp:94] 1
```

I have noticed, that if the first case occurs, the visualization runs without any issues. If the second case occurs, the visualization stops at the initial position. RaisimGymTorch seems to instantiate 2 visualizable servers and if the wrong server is connected, the visualization will not turn on. 

This are only observations and I think this can't be a false implementation in my simulation since I get the exact same results with the anymal example which I did not modify.

**Comment by Pala-Ah** [comment]
one more thing: 

Case 2 can also occur when I am running RaisimUnityOpenGL. When I have RaisimUnity running alone and case 2 occurs, the simulation is visualized in RaisimUnityOpenGL after opening it as the second visualization application. It also happens in the opposite case: When RaisimUnityOpenGL is running alone and case 2 occurs, the simulation is visualized in RaisimUnity after opening it. Very weird.

I have not enough VRAM to run the simulation on RaisimUnity and open a second RaisimUnity window. But I can observe the same behavior when running one RaisimUnityOpenGL window and opening a second RaisimUnityOpenGL window. It is visualized on the second RaisimUnityOpenGL window but not on the first.

analogously when case 1 occurs and the simulation is visualized on the first RaisimUnity/RaisimUnityOpenGL window, after opening the second window the visualiation is freezed on the second window.

**Comment by jhwangbo** [comment]
Can you pull and try again?

**Comment by Pala-Ah** [comment]
The issue is fixed, thank you!
