### ISSUE TITLE
Segmentation Fault when running examples

### ISSUE THREAD

**Issue by Neotriple** [raisimTech/raisimLib#85]
Hi there,

I recently installed Raisim on MacOS Big Sur with an Intel chip. When attempting to run the examples, I get an immediate segfault. 

I've followed all the steps on the installation page here, and was wondering if there was a recent change that would be causing an issue with MacOS.  It seems to be segfaulting after this line:

raisim::World world;

in all of the examples.

**Comment by jhwangbo** [comment]
I could not reproduce it on my pc. Can you check your CPU model number? I doubt it but maybe you don't have avx2 instructions

**Comment by Neotriple** [comment]
My laptop uses an Intel Core i5-1038NG7 CPU which should have axv2 instructions.

Is there any other things to maybe troubleshoot? I had a few warnings when compiling, but only warnings, and they all seemed to be related to the python bindings and not anything inherent to the C++.

**Comment by jhwangbo** [comment]
can you delete all raisim installations and clone it again? usually, segfaults are from building/running executables with different raisim versions.

**Comment by Neotriple** [comment]
Hi, I've tried deleting everything and cloning everything again and still have the same issues. I suspect this could be down to one of two issues:

1. The activation folder on MacOS you've noted (https://raisim.com/sections/Installation.html) notes that the .raisim file should go in /home/<username>/.raisim however, it seems MacOS doesn't allow you to  create directories in the /home/ folder (even using a sudo command). Did you by chance mean /Users/<username>/.raisim ?
-  I just did a clean install and noticed that my computer is segfaulting even after I removed the .raisim file, so it could be an authentication issue. What does the error handling for the authentication look like? Will it throw an error if it doesn't find the .raisim file? 


2. I noticed my computer is compiling with the CLANG / XCode version of GCC and not the homebrew version. Do you think this could potentially also cause issues?

**Comment by Neotriple** [comment]
Hi, so the activation key was indeed the culprit in this. I had to manually point to the folder using the `raisim::World::setActivationKey()` command. You mention in the documentation that if this line of code does not find the activation key: "will search in the user directory, where you saved your activation.raisim file.". For MacOS where is this set to? It seems like perhaps because of the issue I mentioned above (regarding /home/...) on MacOS, this might be looking in the wrong place automatically. Is this hard-coded somewhere?

**Comment by jhwangbo** [comment]
I guess this is my problem. I don't use Mac and I assumed that it searches the home directory similarly to Linux. I can fix this over the weekend.

**Comment by Neotriple** [comment]
Thanks! Just to note, the equivalent place for MacOS to the Linux/Windows would be:
`/Users/<username>/.raisim`
I noticed in my comment above the formatting was off so this should help.

**Comment by jhwangbo** [comment]
I pushed a fix. It works well on my machine. Let me know how it works on yours

**Comment by Neotriple** [comment]
Everything seems to work now. Thanks for the quick fix!
