### ISSUE TITLE
raisimGymTorch

### ISSUE THREAD

**Issue by kashifzr** [raisimTech/raisimlib#9]
HI
In raisimTech/raisimlib there is one Package (folder name as raisimGymTorch) which provided with setup.py, CMakeLists.txt, __init__.py, README.md and LICENSE file. in the README.md it was stated there is no need to compile here. This only provides a header file for an environment definition.
In the same file there are two instructions which states

1) Compile raisimgym:  python setup develop
2) run runner.py of the task (for anymal example) : cd raisimGymTorch/env/envs/rsg_anymal && python ./runner.py

For the 1 step of compilation I did the following

python3 setup.py install --CMAKE_PREFIX_PATH $LOCAL_BUILD --env /raisimGymTorch/env/envs/rsg_anymal

But the compilation failed with following error like 

errorL: option --env not recognized 

If I compile without --env parameter it works fine but when i try to run the code examples runner by following the path 

then it give me error like 

Module NotFoundError: No module name 'raisimGymTorch'

How I resolve this issue

**Comment by jhwangbo** [comment]
Two things to check
1. now you are mixing "python" and "python3". They might call a different version of python.
2. you don't need `python3 setup.py install` if you call `python setup develop`. when you call the setup file, it will create binaries in env.bin folder. Check if it is really there

**Comment by kashifzr** [comment]
I am trying to run command "python setup develop" with both python3 or python, but there is an error
python3: cannot open file 'setup' : [Errno 2] No Such file or directory
Most of the time i used python3 command but in both case error is same 

In this directory there is setup.py file which is not accessible without extension .py

**Comment by jhwangbo** [comment]
.py was not the point. When you call python setup.py develop, it compiles it for your "python" version and it only works for that version. Check the name of the binary

**Comment by kashifzr** [comment]
Now its works, thanks. I considered python3 setup.py install as same as python setup develop.
