### ISSUE TITLE
Questions about the runner.py path 

### ISSUE THREAD

**Issue by jangmingyu** [raisimTech/raisimLib#91]
Hello, I am a student at Seoul National University of Science and Technology Professor Jin-Hyun Kim's lab. 

I have a problem installing and running raisim this time, so I ask a question. 

As the professor explained, I configured the Conda environment and ran setup.py in the raisimLib-master\raisimGymTorch folder to configure the environment. 

And when I tried to run runner.py, an error of "No module named'raisimGymTorch.env'" occurred. env files are located in raisimLib-master\raisimGymTorch\raisimGymTorch. 

So I changed all the paths of the modules. 

This solved the problem of not finding the module, but an error occurred in rsg_anymal saying that the property of RaisimGymEnv was missing. 

I would appreciate it if you could answer me if there is anything I missed.

**Comment by jhwangbo** [comment]
> error occurred in rsg_anymal saying that the property of RaisimGymEnv was missing.

Can you post the full error message?

**Comment by jangmingyu** [comment]
![1](https://user-images.githubusercontent.com/37793152/114166976-56189700-9969-11eb-9d50-b041a25cfcae.JPG)

**Comment by jhwangbo** [comment]
The issue is with Clion. It tries to add additional files to PYTHONPATH. In the right top drop down where you select the executable -> edit configurations -> go to runner.py -> deselect "Add content roots to PYTHONPATH" and "Add source roots to PYTHONPATH"

**Comment by jangmingyu** [comment]
Thank you. However, if you can help me with a new problem, I would appreciate it. 
![3](https://user-images.githubusercontent.com/37793152/114168761-a7298a80-996b-11eb-8022-ad4656e25a80.JPG)

**Comment by jhwangbo** [comment]
Please do not post a screenshot. They are not searchable.

Can you check if you have ``rsg_anymal`` inside the ``env`` directory? If not, then you have to call the ``python setup.py develop``

**Comment by jangmingyu** [comment]
`CMake Error at CMakeLists.txt:28 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/cygdrive/c/raisimLib-master/raisimGymTorch/cmake-build-debug/CMakeFiles/CMakeOutput.log".`

When I first create a project with clion, I get the above error. Should I solve the above problem?

**Comment by jhwangbo** [comment]
Are you using linux? then ``sudo apt-get install libeigen3-dev``

This link will help you
https://raisim.com/sections/Installation.html

**Comment by jangmingyu** [comment]
Sorry to keep asking questions. 

My environment is Windows. I set the path of Eigen3_DIR in the system environment variable.  

rsg_anymal.lib file was created in C:\raisimLib-master\raisimGymTorch\raisimGymTorch\env\bin by building through _raisim_gym_torch.sln generated through setup.py. So, we solved the previous problem.

```
C:\Users\neuro_jmg\Anaconda3\envs\raisimLib-master\python.exe C:/raisimLib-master/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py
Traceback (most recent call last):
  File "C:/raisimLib-master/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/ru
nner.py", line 2, in <module>
    from raisimGymTorch.env.bin import rsg_anymal
ImportError: DLL load failed while importing rsg_anymal: 지정된 모듈을 찾을 수
없습니다.

Process finished with exit code 1
```
 But I got the above error. In addition to the answers, we will continue to work on resolving the error. Thank you.

**Comment by jhwangbo** [comment]
You can do that by following these steps

1. “Edit the system environment variables”
2. In “Advanced tab”, “Environment Variables”
3. Click “Path” variable in the “System variables” list and click “edit”
4. Append the install directory (or just raisimLib/raisim/win32/bin)

**Comment by jangmingyu** [comment]
Thanks for solving my problem through the information above.
