### ISSUE TITLE
why my computer note raisimUnityOpengl version mismatch when I try to execute the examples

### ISSUE THREAD

**Issue by hxydebug** [raisimTech/raisimLib#92]
it notes that version mismatch,please update raisim on both server and client sides

**Comment by jhwangbo** [comment]
when did you pull? it works on my machine

**Comment by hxydebug** [comment]
I just follow the doc, and I pull at  https://github.com/raisimTech/raisimlib

**Comment by hxydebug** [comment]
my machine can't support the raisimUnity very well, so I have to use raisimUnityOpengl

**Comment by jhwangbo** [comment]
I meant "when". This bug was fixed recently

**Comment by hxydebug** [comment]
last sunday

**Comment by jhwangbo** [comment]
What I really meant is "please pull and try again"

**Comment by jhwangbo** [comment]
this was the fix: e6bc63f863d608357fe09047b70c486297d02381
I am closing this issue. Please reopen it if you still have the problem

**Comment by hxydebug** [comment]
ok,I have a try
