### ISSUE TITLE
Non-limited joint vs limited to zero in `getJointLimits`

### ISSUE THREAD

**Issue by RobertoRoos** [raisimTech/raisimLib#93]
Currently [getJointLimits()](https://raisim.com/sections/ArticulatedSystem.html#_CPPv4N6raisim17ArticulatedSystem14getJointLimitsEv) returns a limit of [0, 0] for joints that are not limited. But that cannot be differentiated from a joint limit that really is min=0, max=0.

**Comment by RobertoRoos** [comment]
I made a mistake, this is not true. Wanted to post this question anyway.

So the resulting limits for a joint without limits are [-1.7e308, 1.7e308], which are the min and max values for a double. That's a good approach.

The thing is the floating base of a robot (the first 6 degrees of freedom) have limits [0, 0]. Maybe it'd be good if those would also have the [DOUBLE_MIN, DOUBLE_MAX] limits, to match with the non-limited joints?

**Comment by jhwangbo** [comment]
that is just a convention. Why do you ever have to set the min equal to the max?

**Comment by RobertoRoos** [comment]
We want to test a model where we lock some joints, without the hassle of changing the degrees of freedom. I figured setting a range equal to zero would be a good approach.

**Comment by jhwangbo** [comment]
If you can manually set the joint limits to min=max, then this limit will be ignored. I cannot think of a better way than just setting it to a fixed joint.

The floating joint currently has no joint properties. Adding a joint limit for the floating base is not so simple now because all joints have scalar limits. I have to change many things to implement this. And it is awkward to define limits on the floating base since it is not even specified in the URDF. Users cannot set this number

**Comment by RobertoRoos** [comment]
> The floating joint currently has no joint properties. Adding a joint limit for the floating base is not so simple now because all joints have scalar limits. I have to change many things to implement this. And it is awkward to define limits on the floating base since it is not even specified in the URDF. Users cannot set this number

Right, that makes sense. But since the floating base is alway non-limited, why not let `getJointLimits` return [DOUBLE_MIN, DOUBLE_MAX] for those coordinates. You might capture it as a special case.

But regardless, I can work around it too. Thanks.

> If you can manually set the joint limits to min=max, then this limit will be ignored. I cannot think of a better way than just setting it to a fixed joint.

Oh, I didn't know that. Hadn't experimented yet. I guess I can cheat by setting a very small range instead, e.g. [-0.001, 0.001]. Or resort to fixed joints anyway.

Thank you for your replies!
