### ISSUE TITLE
Illegal Instructions error 

### ISSUE THREAD

**Issue by kirandoshi** [raisimTech/raisimLib#94]
Hi,
I installed the raisimLib with raisimOgre according to the instructions given. When trying to run the examples (any example) I get the following error
`Illegal instruction (core dumped)`
When running with the gdb debugger I get: 

> Reading symbols from ./anymal...
(No debugging symbols found in ./anymal)
(gdb) run
Starting program: /home/kirand/rslgym_build/bin/anymal 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Program received signal SIGILL, Illegal instruction.
0x00007ffff77695b8 in machineid::machineHash() () from /home/kirand/rslgym_build/lib/libraisim.so
(gdb) bt
#0  0x00007ffff77695b8 in machineid::machineHash() () from /home/kirand/rslgym_build/lib/libraisim.so
#1  0x00007ffff7771eb2 in initializeResource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /home/kirand/rslgym_build/lib/libraisim.so
#2  0x00007ffff775d049 in raisim::World::init() () from /home/kirand/rslgym_build/lib/libraisim.so
#3  0x00007ffff775d7a9 in raisim::World::World() () from /home/kirand/rslgym_build/lib/libraisim.so
#4  0x000055555555b38e in main ()

I think the issue is due to the PC having an old CPU without _avx2_ instructions. Is there a way to get raisimLib to work on such a computer? 

If this helps, here is the description of the CPU

> Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           42
Model name:                      Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
Stepping:                        7
CPU MHz:                         1627.750
CPU max MHz:                     3700.0000
CPU min MHz:                     1600.0000
BogoMIPS:                        6585.10
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditiona
                                 l, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush
                                  dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_pe
                                 rfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulq
                                 dq dtes64 monitor ds_cpl smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2
                                 apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb sti
                                 bp xsaveopt dtherm ida arat pln pts md_clear flush_l1d

Thanks for your support.

**Comment by jhwangbo** [comment]
You are right. Without AVX2, RaiSim will not work. Why do you want to run on an old computer? Nowadays, it is hard to find such a computer except for some special purpose PCs.

**Comment by kirandoshi** [comment]
Thanks a lot for the quick response. There is no specific reason, it is just the computer I have access to. If it does not work without, I'll need to find a newer machine.

**Comment by jhwangbo** [comment]
It is hard for me to maintain two versions for linux. AVX2 makes about a 10% speed boost
