### ISSUE TITLE
Import problems for new models 

### ISSUE THREAD

**Issue by jangmingyu** [raisimTech/raisimLib#95]
Hello, after running runner.py successfully, I tried to import atlas, one of the example models, instead of anymal in the existing model, and I ran into the following problem.

```
C:\Users\neuro_jmg\anaconda3\envs\raisimLib-master\python.exe C:/raisimLib-master/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/runner.py
[2021:04:23:13:45:40 C:\Users\jemin\Documents\git\raisim\src\ArticulatedSystem.c
pp:1299] ?[1;31munknown body id?[0m

Process finished with exit code 1
```
It is viewed as a problem from links and joints defined differently from the anymal model. Any comments that can solve the problem would be appreciated.

**Comment by jhwangbo** [comment]
it says "unknown body id". You used a method with the body name and that body doesn't exist in the URDF.

**Comment by Alex-Beh** [comment]
@jhwangbo Hi, I am facing the similar issue. For example, in my Environment.hpp: 
`
footIndices_.insert(a1_->getBodyIdx("FR_calf"));
`

And the **FR_calf** has been defined as one of the links of the robot in the urdf file. Anything else should I check to pass this error mesage?

**Comment by jhwangbo** [comment]
In RaiSim, links and bodies are different. Bodies can contain multiple links that are connected by a fixed joint. The name of the body is the same as that of the parent link, the link that is connected to the parent link via a movable joint (revolute, spherical, or prismatic).

**Comment by Alex-Beh** [comment]
Hi, thanks for your prompt reply.

Both the bodies and links are defined in urdf? For example the **LF_SHANK** in [anymal](https://github.com/raisimTech/raisimLib/blob/2717509d5ddcdaa2e463e8a9134b57715cdb41ad/raisimGymTorch/raisimGymTorch/env/envs/rsg_anymal/Environment.hpp#L63), it is only defined as link. I didn't see any bodies definition in the [urdf](https://github.com/raisimTech/raisimLib/blob/master/rsc/anymal/urdf/anymal.urdf).

Please correct me if I missed something.

**Comment by jhwangbo** [comment]
bodies are not defined in the URDF. the are defined only in RaiSim.

**Comment by Alex-Beh** [comment]
Thanks for the information. Can you point me to the code where you define the **LF_SHANK** as the body of anymal in RaiSim?

**Comment by jhwangbo** [comment]
No, you don't define body yourself. When RaiSim reads the URDF, it creates bodies from the links. So you don't have to do anything.

**Comment by jhwangbo** [comment]
If you want to get the kinematics of the fixed links, you should use ``frames`` instead
