### ISSUE TITLE
APIs to get rendered images

### ISSUE THREAD

**Issue by MarkFzp** [raisimTech/raisimLib#97]
I'm wondering if there is API to get rendered RGB values from a camera pose in the simulator? I know we can visualize through raisimUnity, but to enable research relying on exteroceptive inputs (e.g. vision based RL), the functionality to get the RGB observation directly in env.step() is important. Is there any plan to support it in the future if it's not currently supported for now?

**Comment by jhwangbo** [comment]
I'll check how difficult it is on this weekend

**Comment by MarkFzp** [comment]
Any update on this?

**Comment by jhwangbo** [comment]
I am working on the mjcf reader and it took longer than i expected. Probably i can start working on this this weekend.

**Comment by feracero** [comment]
Hello, curious about the status of this request? thanks

**Comment by jhwangbo** [comment]
I looked into this feature for a while. The problem is that Unity3d does not provide a good way to get a screen image. There is a built-in function but this is very inefficient and takes about ~100ms in the current system. It is not sufficient for any RL applications.

**Comment by ashish-kmr** [comment]
Related question: Is there a plan to support depth rendering from a simulated camera? Or what's the simplest way to do this in raisim? 

Any help would be greatly appreciated!

**Comment by jhwangbo** [comment]
Check out the ray test example.

**Comment by Simone-DAngelo** [comment]
Hello, are there any updates regarding the possibility of adding a camera sensor in the scene?

**Comment by jhwangbo** [comment]
I found that it is not possible to do it in Unity when I use the Vulkan backend. I have to use another game engine or rendering engine. This is not happening in a few months.

**Comment by jhwangbo** [comment]
This is finally resolved.
