### ISSUE TITLE
Actuator limits not respected by PD controller

### ISSUE THREAD

**Issue by ankit61** [raisimTech/raisimLib#98]
Hi! I am trying to control a robot (i.e. articulated system) using position, and therefore am using the provided PD controller. My robot has actuation limits described in the URDF, and I verified that these limits are being identified by RaiSim by checking the output of `robot->getActuationLowerLimits()` and `robot->getActuationUpperLimits()`. However, when I get the actual force being applied using `robot->getGeneralizedForce()`, it does not happen to be within the range of lower and upper limits. I realize that `robot->getGeneralizedForce()` can have minor errors when using a PD controller, but in my case the actual force is very far from the range (which I think a minor error cannot explain). Thoughts?

**Comment by ankit61** [comment]
Since the PD controller is computed inside `integrate2()` (for which the code is not open-source), I can't also write a hacky solution where I just manually apply the actuator limits to the output of the PD controller. Please correct me if I am wrong, or let me know if another hacky solution exists for the time being.

**Comment by jhwangbo** [comment]
The current PD controller doesn't respect the actuation limit. It computes the force implicitly and the limits cannot be respected. It is very stable due to its implicit nature but has this downside. If the actuation limit is important, you should compute the PD force and apply it using the FORCE_AND_TORQUE mode.

**Comment by ankit61** [comment]
I see! In that case, I think this should be clearly documented on the website (possibly [here](https://raisim.com/sections/ArticulatedSystem.html#pd-controller)) because this can introduce a silent bug in the code.

**Comment by jhwangbo** [comment]
I'll write a comment in that section in the next website update.

**Comment by edward9503** [comment]
> I'll write a comment in that section in the next website update.

Hi there,

thanks for the simulation!

After I went through the explanation of two different control modes (i.e., "PD+feedforward torque" control and "Force_and_torque" control) in Raisim, I still didn't get it what is the difference between these control modes? I was wondering could I have a simple example of using them? Simple equations would be very useful. Thanks in advance!

Best

**Comment by jhwangbo** [comment]
In the "FORCE_AND_TORQUE" mode, you can assume that PD gains are zero
