### ISSUE TITLE
render flag being Ture/False influence Atlas's performance

### ISSUE THREAD

**Issue by fanshi14** [raisimTech/raisimLib#99]
Hi Jemin,

I met a quite strange case when evaluating the policy of ```Atlas```.
When ```render``` in ```cfg.yaml``` being ```False```, my policy always works well.

However, when being ```True```, it totally failed immediately.
I repeat by continously relaunching ```tester.py```, it fails 9 out of 10 times, but 1 time work as expected. Strange!

I checked my code related to ```if (visualizable_)``` in ```Environment.hpp```, only visualization related codes.

Is it just because of my policy not being robust, or other system reasons?
I have never met it before. Thank you in advance!

**Comment by jhwangbo** [comment]
any update on this? is this fixed?

**Comment by fanshi14** [comment]
Still same problem, and sorry I couldn't have time for more survey in 2 months. Maybe you could close at first.

**Comment by jhwangbo** [comment]
can you check the performance in the new version? The whole backend changed and I think this issue is no longer there
